### ISSUE TITLE
Changing direction prop on the fly

### ISSUE THREAD

**Issue by gpmcadam** [bvaughn/react-window#104]
There's instances where you might want to dynamically set the scroll `direction` property, and doing so on the fly doesn't update the list until it is scrolled or otherwise observed.

Should this prop update the list, similar to how re-setting `itemSize` will cause a re-render?

**Comment by bvaughn** [comment]
Hm. Can you describe an example of this?

On the one hand, I would expect changing the prop to re-render the list. On the other hand, I never considered this an actual/valid use case. Seems like it would make for a pretty odd user experience?

Either way, I should either make it work or add a DEV warning. I'm leaning toward the latter, but let's talk about it.

**Comment by gpmcadam** [comment]
@bvaughn an example would be if you resize the window and for responsive reasons want to change the placement of a list on the screen

**Comment by bvaughn** [comment]
That still seems pretty unusual/unexpected to me. Can you show me an example of an actual website that does this?

**Comment by bvaughn** [comment]
Fixed via #112
