### ISSUE TITLE
Improving detection of scroll ended

### ISSUE THREAD

**Issue by bjm904** [bvaughn/react-window#106]
Hello, I ran into a well documented bug / browser quirk that existed in react-virtualized. It was fixed there in https://github.com/bvaughn/react-virtualized/pull/742.

Can the fix of using `requestAnimationFrame` be ported over to react-window? I can give it  a go if you'd like by referencing the code changes in https://github.com/bvaughn/react-virtualized/pull/742, but I figure @bvaughn can do it better and faster.

For me there is a 1.5 to 2.5 sec delay in stopping scrolling and the list items becoming responsive.

**Comment by bvaughn** [comment]
raf-based timer added in #112
