### ISSUE TITLE
new data won't be rendered for an item until List component will be scrolled

### ISSUE THREAD

**Issue by hyzhak** [bvaughn/react-window#118]
## Code to reproduce issue
An Example component has state list, we update this state with new values each second. Despite the fact that we are getting new list each second (and re-render Example component) we won't see those changes until we will scroll list.
Code to reproduce
https://codesandbox.io/s/l3nvyoj50l

## Quick and dirty solution
Because List is pure react component I just need to pass to List component some custom property with list state. So each time when we get new list state we will force List component to rerender content.

Do we have better solution for dynamic content?

**Comment by bvaughn** [comment]
This looks to me like it's working as expected. Generally, the `itemData` prop is used to share data between the component that owns and renders the list and the individual item renderers– which avoids the problem of data changing out from under react-window without it knowing.

Here's a fork of your sandbox with a very minor change:
https://codesandbox.io/s/3vlpxln8l6

**Comment by hyzhak** [comment]
oh! Thanks, I have really missed that prop (`itemData`) 👍
