### ISSUE TITLE
Safari scroll update while momentum is ongoing

### ISSUE THREAD

**Issue by guirip** [bvaughn/react-window#122]
Hello

Thanks for the great work you did providing us this fabulous tool using all the experience you got from `react-virtualized`. 👏 👏 👏

A very well known issue on Safari concerns updating scroll position while scroll momentum is ongoing, and I wanted to know how can we handle this using `react-window`.

On our webapp we display lists containing thousands of brands or exhibitors, with a vertical alphabetical index, e.g like on the contacts list of a phone.
Basically, if you scroll strongly to have momentum, and then select letters from the side index, you will see that the list tries to be at different positions at the same time: 
 - the position dictated by momentum
 - the position you set with `listElement.scrollTop`

This is pretty ugly and not user-friendly at all.
With basic DOM, you can get around this issue with library such as `iScroll`.

The same behavior occurs when using `react-window` and trying to update scroll position while momentum is ongoing. `this.listRef.current.scrollToItem(index, 'start');`
You can reproduce this here : http://ph-dev.mobile-spot.com

How do you suggest to handle this?

Cheers
Guillaume

**Comment by bvaughn** [comment]
Based on what I've seen online, you could try setting a ref on the scrolling container...

> **`outerRef: function | createRef object`**
> Ref to attach to the outer container element. This is an advanced property.

...and then temporarily setting the style to `overflow: hidden` to interrupt the momentum scrolling.

What you're describing, to me, sounds like a Safari bug– not really something I want to add hacks into this library for to handle.

> You can reproduce this here : http://ph-dev.mobile-spot.com

I can't reproduce the behavior you're describing. Hovering over a letter interrupts the scroll animation  for me.

**Comment by guirip** [comment]
> I can't reproduce the behavior you're describing. Hovering over a letter interrupts the scroll animation for me.

Wow this is surprising. I admit that I haven't thought about testing it on the Wk webview. This bug may be related to Ui webview only which is deprecated. In this case I totally understand that you are not going to do anything about it. Anyway thanks for the `outerRef`/`overflow` toggle tip, I will try it! Thanks

**Comment by bvaughn** [comment]
> I admit that I haven't thought about testing it on the Wk webview. This bug may be related to Ui webview only which is deprecated.

Ah. I didn't see "mobile Safari" or "iOS" anywhere in your bug report, so I was testing with desktop Safari. (I don't actually even have an iPhone to test on at the moment.)

Regardless though, I think my response would be the same– what you're describing sounds to me like a browser bug. In the case that JavaScript sets a new scroll offset while a momentum scroll is in progress– scrolling animation should either continue from the new offset (like it does in Chrome) or stop (like it does in Firefox). It shouldn't bounce back and forth. 😄

I don't think there's anything actionable to do on this issue for react-window, so I'm going to close the ticket. I'd be interested in hearing about what you find out though– if you're willing to comment back with an update!

**Comment by bvaughn** [comment]
Thanks for the update!

I'm glad you've got a workaround. Sucks that it's necessary though. 😦
