### ISSUE TITLE
Scrolling issues if style is omitted

### ISSUE THREAD

**Issue by dons20** [bvaughn/react-window#125]
Hi, it's my first time using react-window for a project of mine. You can see the current usage of it [here](https://hymnal.claytoninnovations.com/songs).

I encountered an issue where my list would start stuttering and experiencing major scrolling issues which I assumed was related to some data being re-rendered or something along that line. Days of research and experimentation later, I discovered that the issue could be replicated even in one of your examples; the [memoized list](https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/memoized-list-items). If I simply remove `style={style}` from the `Row`, then upon scrolling you'll see the issues appear. 

This seems to contradict the documentation which says 

> style: Object = null
**Optional** inline style to attach to outermost `<div>` element.

So my question is, what can be done to resolve this issue?

**Comment by bvaughn** [comment]
> If I simply remove style={style} from the `Row`

That would not be using the library correctly. It's required that you attach the `style` prop to whatever elements your item renderer returns, because that's how react-window positions them.

The docs entry you linked to about `style` is referencing an optional style that you can set _on the list itself_ (not the individual items).

Hope this clears things up!

**Comment by Unforgiven-wanda** [comment]
That the style prop **must** be set really should be emphasized more in the docs. I just spent the last hour trying to fix this.
Thank you both for this issue btw.

**Comment by bvaughn** [comment]
How would you suggest emphasizing it beyond showing it being used in every documentation example?

![screen shot 2019-02-19 at 8 45 07 am](https://user-images.githubusercontent.com/29597/53031945-b7481e00-3422-11e9-91c8-97e33998433d.png)
![screen shot 2019-02-19 at 8 45 16 am](https://user-images.githubusercontent.com/29597/53031946-b7481e00-3422-11e9-87d9-0e3629252ca9.png)
![screen shot 2019-02-19 at 8 45 24 am](https://user-images.githubusercontent.com/29597/53031948-b7481e00-3422-11e9-8c22-ca7cdf3a48b4.png)

I appreciate the feedback but there's only so much I can do here. I wrote a ton of documentation, examples, working Code Sandbox demos...

**Comment by dons20** [comment]
I think just a simple note stating that `style` is a required property for `react-window` to work would suffice. Looking at the examples won't necessarily tell a user that they need to include the style. 

E.g. If they're just getting into testing it, maybe they want to see it without any style (especially if they didn't pass a style to it). That was my thinking at least, maybe others share a similar sentiment.

**Comment by bvaughn** [comment]
Took me a bit, but I added a section to the FAQs.
