### ISSUE TITLE
Outer div is in the tab order on firefox

### ISSUE THREAD

**Issue by heyimalex** [bvaughn/react-window#130]
The outerRef div is automatically in the tab order on Firefox. I'm pretty certain that any scrollable div is actually tab-able on Firefox by default.

I use this library for select component dropdowns, so generally there will be an input, a react-window based dropdown, and then another input. Tabbing in the first input starts the focus move, but the `relatedTarget` on the focusout event is the dropdown and not the following input. The dopdown disappears on blur, so focus is just lost.

Using [`-moz-user-focus: ignore`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-user-focus) doesn't appear to stop it, but setting `tabindex="-1"` does. Right now I'm setting that manually on the outerRef in componentDidMount basically as there's no way to pass tabIndex directly through react-window.

This effects Firefox and not chrome. I haven't tested any other browsers. I'm interested in other workarounds if anyone knows of any!

**Comment by bvaughn** [comment]
> I'm pretty certain that any scrollable div is actually tab-able on Firefox by default.

Sounds potentially related to accessibility? How else would a keyboard-only user scroll a div?

> Right now I'm setting that manually on the outerRef in componentDidMount basically as there's no way to pass tabIndex directly through react-window.

You could also use the `outerElementType` prop for this:
```js
const outerElementType = React.forwardRef((props, ref) => (
   <div ref={ref} tabIndex={-1} {...props} />
));
```
I'd like to think on this a little more. I understand that just adding a `tabIndex` prop would be _convenient_ but I'm not convinced this is a common enough use case to warrant expanding the props API.

**Comment by heyimalex** [comment]
Eh, I think that workaround is good enough and very clean. It makes sense; outerElementType gives you all of the flexibility of passing through props without any increase to the api surface. Thanks for your help!

**Comment by bvaughn** [comment]
Hey no problem! 😁

**Comment by dalipkumar703** [comment]
Hello @bvaughn , Can you share how i can use ``outerElementType`` to avoid tab focus on outer div in ``VaraiableSizeList`` ?

**Comment by dalipkumar703** [comment]
I found solution in documentation. Thanks !
