### ISSUE TITLE
Are there any props to help implement infinite list?

### ISSUE THREAD

**Issue by everdimension** [bvaughn/react-window#131]
Hi!

Thank you for this library!
I like the idea of a minimal API where all necessary complexity can be added in userland.

But I find that that the docs are so minimal that I'm not sure whether the methods that would help me even exist.

I expected to implement an Infinite List based on your `FixedSizeList` component, which would invoke a callback when you scroll and reach the end of the list.

I expect your `FixedSizeList` component to have something like an `onScroll` prop which would be called with current scroll position information. But there's no mention of such prop in the docs (I mean the [website](https://react-window.now.sh), not even sure if these are "the docs")

What would the best way to approach implementing an Infinite List based on this library?

**Comment by TrySound** [comment]
@everdimension https://github.com/bvaughn/react-window-infinite-loader

**Comment by bvaughn** [comment]
> I expect your `FixedSizeList` component to have something like an `onScroll` prop which would be called with current scroll position information. But there's no mention of such prop in the docs

There is an `onScroll` prop documented here: https://react-window.now.sh/#/api/FixedSizeList 😄

@TrySound is right though. It sounds like what you're looking for is [react-window-infinite-loader](https://github.com/bvaughn/react-window-infinite-loader)!

**Comment by everdimension** [comment]
Wow, I somehow have missed that! Thank you for your quick replies!

I'll take a look at react-window-infinite-loader, too

**Comment by TrySound** [comment]
@bvaughn Perhaps you should add the link to infinite loader in react-window. I didn't found any.

**Comment by bvaughn** [comment]
Yeah I'll try to remember to update the docs later. PRs also welcome
