### ISSUE TITLE
Question about VariableSizeGrid

### ISSUE THREAD

**Issue by swifttarrow** [bvaughn/react-window#139]
I'm using VariableSizeGrid to render pdfs and want to be able to tether a page indicator next to the scrollbar as I scroll:

<img width="676" alt="page indicator" src="https://user-images.githubusercontent.com/1904947/52972660-7263af00-3370-11e9-892c-e2f56ce573ce.png">

I've cached all of the pageHeights as well as pre-calculated all the scroll positions at which I need to show a new page number. However, when I scroll, I notice that the Grid is actually getting bigger, even though I specify an accurate rowCount.

Is there any way for the scrollbar to reflect the correct proportion of what was scrolled, or it by design of virtualizing a list/grid of rows?

**Comment by bvaughn** [comment]
> I've cached all of the pageHeights as well as pre-calculated all the scroll positions at which I need to show a new page number. However, when I scroll, I notice that the Grid is actually getting bigger, even though I specify an accurate rowCount.

Sounds like you're not specifying a realistic `estimatedColumnWidth` and/or `estimatedRowHeight` values, so as the grid builds up its cache of actual items sizes, it needs to expand it's estimated total scrollable size.

Try tweaking those values.

**Comment by swifttarrow** [comment]
@bvaughn Ah! That makes sense.

Is there a Flow bug with `estimatedRowHeight` and `estimatedColumnWidth`? I'm getting the follow error when I try to use it:
`Cannot create VariableSizeGrid element because property estimatedRowHeight is missing in Props [1] but exists in
props [2].`

**Comment by bvaughn** [comment]
I haven't seen such a bug personally.
