### ISSUE TITLE
Virtualization of a large data visualization

### ISSUE THREAD

**Issue by matt-erhart** [bvaughn/react-window#141]
I have a situation where I have a lot of div elements with absolute position and known size but the user can drag them around to any coordinates, so they are not in a grid. Is this a situation that react-window could handle especially well or should I just add/remove elements based on scroll position? React-window seems to be doing quite a bit more than just add/remove, but maybe that special sauce is unnecessary for my use case?

**Comment by bvaughn** [comment]
That doesn't sound like a use case this library is meant to cover. (It sounds _a little_ like the [react-virtualized `Masonry` component](https://github.com/bvaughn/react-virtualized/blob/master/docs/Masonry.md) but not quite.)

Sorry! 😄
