### ISSUE TITLE
Enhance isScrolling with scrollStepSize

### ISSUE THREAD

**Issue by leantide** [bvaughn/react-window#143]
Hello Brian,

I have a heavy row render and thus experience scroll render tearing when scrolling fast. I do not experience this tearing when scrolling slowly. 

I have a light version of the row render, but it delivers a significantly poorer user experience. Therefore I would like to use ONLY if the user is scrolling fast. 

I understand that your isScrolling indicator is boolean and that your component by design has no concept of scroll speed. I also appreciate that 'slow' and 'fast' are relative and application specific.

Could you expose a callback with a scrollStepSize value? scrollStepSize would be the calculated difference between successive element.scrollTop values of your handling of the onScroll events?

I could then experimentally observe the tearing threshold and only use the light row rendering if isScrolling && (scrollStepSize > myApplicationSpecificThreshold).

Alternatively, if you even exported the scrollTop value at each onScroll event, I could perform the difference calculation my self.

If you see this as helpful, would like to see this in react-virtualized also ;)

Thank you.

**Comment by bvaughn** [comment]
> I have a heavy row render and thus experience scroll render tearing when scrolling fast. I do not experience this tearing when scrolling slowly.

Makes sense, as the overscan rendering is probably sufficient to keep ahead of slow scrolling.

> Alternatively, if you even exported the scrollTop value at each onScroll event, I could perform the difference calculation my self.

This is already "exported" by way of the `onScroll` callback, [mentioned in the docs](https://react-window.now.sh/#/api/FixedSizeList):

> Called when the list scroll positions changes, as a result of user scrolling or scroll-to method calls.

```js
function onScroll({
  scrollDirection,
  scrollOffset,
  scrollUpdateWasRequested
}) {
  // scrollDirection is either "forward" or "backward".
 
  // scrollOffset is a number.
 
  // scrollUpdateWasRequested is a boolean.
  // This value is true if the scroll was caused by scrollTo() or scrollToItem(),
  // And false if it was the result of a user interaction in the browser.
}
```

> Could you expose a callback with a scrollStepSize value? scrollStepSize would be the calculated difference between successive element.scrollTop values of your handling of the onScroll events?

I think you should be able to implement this using the existing `onScroll` callback and a ref (to store the current delta). If you passed this ref down via the `itemData` API then your renderer could decide whether to ignore `isScrolling` or not.

> If you see this as helpful, would like to see this in react-virtualized also ;)

I don't maintain react-virtualized anymore 😄 so you would have to reach out to whoever is maintaining it currently.

**Comment by leantide** [comment]
Sorry, I missed it. Thank you. This will work.

p.s. One of the first comparisons I do when comparing components is look at the git-hub stars. If you haven't already, I would suggest adding high level comment and link in your react-virtualized component to suggest the devs first consider react-window.

**Comment by bvaughn** [comment]
That's a good suggestion 👍 Thanks

**Comment by bvaughn** [comment]
[Done](https://github.com/bvaughn/react-virtualized#a-word-about-react-window)!

**Comment by davidpmccormick** [comment]
> I think you should be able to implement this using the existing onScroll callback and a ref (to store the current delta). If you passed this ref down via the itemData API then your renderer could decide whether to ignore isScrolling or not.

I'm trying to conditionally render a lower-res image if a user is scrolling fast and this sounds like what I need to do, but I can't quite wrap my head around how it would work – is there any danger of a pared-back demo for it?

**Comment by bvaughn** [comment]
> is there any danger of a pared-back demo for it?

I have no idea what this means 😅

**Comment by davidpmccormick** [comment]
Please can you show me how to do it? 😄
