### ISSUE TITLE
Server side rendering: SEO best practices for virtual lists

### ISSUE THREAD

**Issue by melalj** [bvaughn/react-window#144]
react-window is amazing for the client side and helps to increase the fluidity and performance of the app - but Search engines won't be able to scroll the `FixedSizeList` to get all the links to index the app properly.

One option I considered is to set:
```jsx
<FixedSizeList overscanCount={(typeof window === 'undefined') ? dataset.length : 20} ... />
```
the issue with the above option is that the output will be pretty heavy to the inline styles.

What would be the best practice for such use case?

**Comment by heyimalex** [comment]
You could try not setting styles on the rows during ssr, and then applying a className to the containing component that styles the rows to their fixed height? Seems like that plus your overscan trick would render into what you'd make without react-window, which sounds like what you want.

**Comment by bvaughn** [comment]
> but Search engines won't be able to scroll the FixedSizeList to get all the links to index the app properly

I haven't thought about this much, but my initial take would be for you to just not use react-window at all when you detect that you're being crawled (e.g. using the user agent) – just render the full list of (unstyled) data however you want.

I would recommend _against_ doing this in all other cases though, because you'd end up sending a lot of unnecessary markup down to the client and creating a lot of unnecessary DOM elements– making your initial render slower.

**Comment by bvaughn** [comment]
Since this issue isn't really actionable, I'm going to close it – but let's keep the conversation going. Maybe I'll add a section to the FAQs based on the outcome!

**Comment by kartikag01** [comment]
I may not be correct but does it matter to SEO when you are using schemas for structured data (https://schema.org/) along with a virtual list?

**Comment by kelly-tock** [comment]
@kartikag01 what schema are you thinking of in particular?  I suppose any schema that happens to support a list of things?

**Comment by pelhage** [comment]
Another question around SEO is would changing the behavior for crawlbot vs non crawlbots count as cloaking?

https://developers.google.com/search/docs/advanced/guidelines/cloaking

> Some examples of cloaking include:
> 
> Serving a page of HTML text to search engines, while showing a page of images to users
Inserting **text or keywords into a page only when the user agent that's requesting the page is a search engine**, not a human visitor

**Comment by aomini** [comment]
> I may not be correct but does it matter to SEO when you are using schemas for structured data (https://schema.org/) along with a virtual list?

I think structured data are just enhancements. With virtualization search engines only get a part of those lists.

**Comment by waliurjs** [comment]
I've found this old article from Google Developers Blog about SEO friendly Infinite Scroll:
https://developers.google.com/search/blog/2014/02/infinite-scroll-search-friendly

Demo of their infinite scroll (from the article):
https://scrollsample.appspot.com/items
