### ISSUE TITLE
Issue using FixedSizeList -- Can't seem to load more rows and scrollbar jumps a lot

### ISSUE THREAD

**Issue by JClutch** [bvaughn/react-window#145]
Hey,

I've been looking into using a virtualized window for rendering long list of data (i.e. about 5500 rows) and tried implementing following the example BUT I seem to be having a lot of issues with it. 

It rendered the first 10 rows in the small window correctly but when I try to scroll down it looks like it tries to load more but those rows start flashing empty space start to appear in the window and when I look at the DOM element tree in dev tools I realize it's just pushing up the original set of rows and it's the scroll bar oscillating up and down causing the flashing as if it's stuck and doesn't know how to grab the next set of rows (just a hypothesis). 

Also if I grab the scroll bar and drag far down past the jumping I just hit white space for the rest of it.

Any advice on this? Trying not to send screenshots as this is for an internal work project but if need be I can configure some censored ones. Any help on this would be greatly appreciated!

**Comment by bvaughn** [comment]
Bug reports need repros. I can only guess without actually seeing what's happening.

My guess though is that you're forgetting to attach the `style` (the thing that positions rows) to your rows.

**Comment by JClutch** [comment]
Ahh I didn't realize the list was passing down a style object for each of the rows. That fixed it perfectly thank you!

**Comment by bvaughn** [comment]
Yup, no problem. If you can think of suggestions for how the docs site (or README) could better emphasize this, they would be welcome. This is a fairly common source of error. :)

**Comment by JClutch** [comment]
Maybe a line emphasizing the need to use to the style prop or breaking down the necessary styles for positioning for the rows as now it's only mentioned that the child component is passed the prop and it's used for positioning but not that it's necessary.

Another idea is a maybe a common mistakes or Q&A section in the readMe/docs if you feel people have enough of these common sources or error. 

Either way thank you for your help as this has been working great in our app.

**Comment by makis-spy** [comment]
BAH! 6 hours trying to figure this out. lol. STYLE REQUIRED anyone else
