### ISSUE TITLE
Reset style cache whenever itemData changes in VariableSizeList

### ISSUE THREAD

**Issue by jancama2** [bvaughn/react-window#147]
I have the same use case as in #109 and my `itemData` may change over time. I would expect that `itemSize` will be triggered anytime `itemData` changes but I have to force it using `resetAfterIndex`.

**Current solution**
My solution with explicit cache invalidation.
``` javascript
const useResetCache = data => {
    const ref = React.useRef();
    React.useEffect(() => {
        // AutoSizer causes ref not being present on the component mount
        if (ref.current) {
            ref.current.resetAfterIndex(0);
        }
    }, [data]);
    return ref;
};

const SecretList = ({ data }) => {
    const ref = useResetCache(data);
    return (
        <AutoSizer>
            {({ height, width }) => (
                <List
                    ref={ref}
                    height={height}
                    width={width}
                    itemData={data}
                    itemCount={data.length}
                    itemSize={index => {
                        const item = data[index];
                        return ITEM_SIZE[item.type];
                    }}
                    itemKey={index => {
                        const item = data[index];
                        return item.key;
                    }}
                >
                    {ItemRenderer}
                </List>
            )}
        </AutoSizer>
    );
};
```
**Proposed solution**
I would rather have implicit cache invalidation on `itemData` change to make the component simpler.

``` javascript
const SecretList = ({ data }) => (
        <AutoSizer>
            {({ height, width }) => (
                <List
                    ref={ref}
                    height={height}
                    width={width}
                    itemData={data}
                    itemCount={data.length}
                    itemSize={index => {
                        const item = data[index];
                        return ITEM_SIZE[item.type];
                    }}
                    itemKey={index => {
                        const item = data[index];
                        return item.type === 'group' ? item.name : item.id;
                    }}
                >
                    {ItemRenderer}
                </List>
            )}
        </AutoSizer>
    );
```

**Comment by bvaughn** [comment]
I don't think this change would be a good idea for default behavior. It's expensive to throw out cached item sizes, and often it's unnecessary, since `itemData` can just contain e.g. function callbacks.

We can keep chatting about this but I don't currently plan on taking any action on this issue.

**Comment by andrew-aladev** [comment]
This issue is result of series of mistakes.

1. Users are using inline functions like `itemSize={(index) => 1}` instead of `useCallback`.
2. `VariableSizeList` receives new `itemSize` function on each render.
3. Author of `react-window` can't use effect based on `itemSize` to reset sizes cache, because inline `itemSize` is too popular.
4. Users have to clear cache manually.

This issue may be fixed only by full refactoring, example:

User code:

```js
const getLineHeight = useCallback(
  (index) => heights[index],
  [heights]
);

<VariableSizeList itemSize={getLineHeight}>
```

`react-window` code:

```js
useEffect(
  () => { resetCachedSizes() },
  [itemSize]
)
```

But this change will never happen in this project, it breaks too much. It can only happen in new project, fork, etc.
