### ISSUE TITLE
scrollToItem doesn't change index prop

### ISSUE THREAD

**Issue by sshmyg** [bvaughn/react-window#151]
Hi, on component load I should scroll it to some row, but when I invoke 'scrollToItem' prop `index` from Row, doesn't change. I have some logic connected with this index, so right now everything is ok until I invoke `scrollToItem`. This `index` prop doesn't update.
![image](https://user-images.githubusercontent.com/1410608/53642662-f7857880-3c3a-11e9-9fe8-3aa80a9f83ac.png)

Imho, this is current index of visible row and it should be updated when  `scrollToItem` invokes, doesn't it?  It's like we scroll manually to some item but very fast.

Thank you.

**Comment by bvaughn** [comment]
I'm sorry but I don't understand what you're asking, and since there is no repro code, I can't do much with it.

The index prop is different for each row.

Provide a repro (Code Sandbox) that shows the but you're describing and I'll re-open this issue and take a look.

**Comment by sshmyg** [comment]
My fault, sorry. Works as expected;

**Comment by bvaughn** [comment]
S'ok
