### ISSUE TITLE
Question: arguments data for onScroll callback

### ISSUE THREAD

**Issue by sshmyg** [bvaughn/react-window#152]
Hi, is it possible to add `index` param to `onScroll` callback?

Extend this data:
```
function onScroll({
  scrollDirection,
  scrollOffset,
  scrollUpdateWasRequested
}) {
```

To be like this:
```
function onScroll({
  index,
  scrollDirection,
  scrollOffset,
  scrollUpdateWasRequested
}) {
```

**Comment by bvaughn** [comment]
What would an `index` param represent?

If you want to know which items are visible, there's an `onItemsRendered` function. `onScroll` is just about scroll offset.

Closing for now since I've done my best at answering this question. 😊

**Comment by sshmyg** [comment]
Thanks ;)
