### ISSUE TITLE
How to fill parent in primary scroll direction?

### ISSUE THREAD

**Issue by cmeeren** [bvaughn/react-window#154]
react-window requires a numeric `height` for vertical lists. I'd like my list to vertically fill all available space. Is this possible with react-window? Is that what #5 is about? (I'm new to the React world and haven't heard of AutoSizer.)

**Comment by bvaughn** [comment]
You can use the [`react-virtualized-auto-sizer` package](https://www.npmjs.com/package/react-virtualized-auto-sizer) for this. Here's an example:
https://codesandbox.io/s/3vnx878jk5

**Comment by cmeeren** [comment]
Just what I needed, thanks! :)
