### ISSUE TITLE
What is the best way to circumvent itemSize memoization? 

### ISSUE THREAD

**Issue by Rom325** [bvaughn/react-window#161]
Hi @bvaughn and thank you for react-window! I'm having an issue with the use case which can be reduced to the following gist https://codesandbox.io/s/0q33jnx07n
How to repro:
1. Observe that only 'expandable' items are expected to have an increased height.
2. Observe that item titled "three" has correct height
3. Press "expand" button at the bottom.
4. Observe that item previously titled as "three" has an increased height despite being non-expandable.
What should I do to avoid this, resetAfterIndex?
Thanks in advance.

**Comment by bvaughn** [comment]
> What should I do to avoid this, resetAfterIndex?

Yes. That's what that method is for. 😄
