### ISSUE TITLE
React-window not working with React.lazy()

### ISSUE THREAD

**Issue by nik72619c** [bvaughn/react-window#164]
React.lazy() requires to give a Suspense tag as its parent but cannot be provided when implementing windowing in react. How can I lazy load the row component that is rendered by FixedSizeList??

Could anyone help me with this issue?
@bvaughn @jgoz @moroshko @pluma

**Comment by bvaughn** [comment]
> React.lazy() requires to give a Suspense tag as its parent

`Suspense` does not need to be the _parent_, just an ancestor (somewhere above the `lazy` component in the tree).

Example:
https://codesandbox.io/s/vn27kjv3r7

**Comment by nik72619c** [comment]
the problem is i am rendering something like:-
`  <List
    height={150}
    itemCount={this.state.todoArray.length}
    itemSize={35}
    width={300}
    itemData={this.state.todoArray}
    Complete={this.Complete}
    
  >
    {ListItem}
  </List>`

**Comment by nik72619c** [comment]
the problem is i am rendering something like:-

  <List
    height={150}
    itemCount={this.state.todoArray.length}
    itemSize={35}
    width={300}
    itemData={this.state.todoArray}
    Complete={this.Complete}
    
  >
    {ListItem}
  </List>

**Comment by nik72619c** [comment]
The ListItem component is lazy loaded...what should I do in this case?

**Comment by nik72619c** [comment]
I added suspense to the  top of List but it throws an error

**Comment by bvaughn** [comment]
I literally showed an example of a lazy-loaded list item / row component in the sandbox I linked to.

**Comment by nik72619c** [comment]
Resolved it...my bad
Thanks a tonne for the guidance @bvaughn :)

**Comment by bvaughn** [comment]
Glad you got it solved 👍

**Comment by nik72619c** [comment]
How should I pass a function down to the row?

**Comment by bvaughn** [comment]
`itemData` – https://react-window.now.sh/#/examples/list/memoized-list-items

**Comment by nik72619c** [comment]
Is it the absence of refactoring shouldComponentUpdate that the list flickers or re-renders on scrolling?
