### ISSUE TITLE
WindowScroller performance

### ISSUE THREAD

**Issue by nick-keller** [bvaughn/react-window#165]
Let me start off by a huge thank you for this library, awesome work here 👏 
I want to have a full page list but I am wondering if the perfs are great...

As explained in #30 I started implementing WindowScroller this myself.
Basically, I am doing two things:
1. Force the style height to 100% `<FixedSizeList style={{ height: '100%', }}>`
2. Add a ref `<FixedSizeList ref={this.listRef}>` and call `scrollTo` like so: `this.listRef.current.scrollTo(scrollTop)`

The first part I'm not too worried about, but the second part is not so obvious. 

- Am I missing on a lot of optimisations from react-window?
- Is `window.addEventListener('scroll', this.onWindowScroll, { capture: true, passive: true })` the best way to do this?
- How is the `isScrolling` working?

I hope this is clear, thanks in advance for your help on this topic ;)
Cheers

**Comment by bvaughn** [comment]
This question is a bit too broad for me to be able to tackle right now. 😦

The suggested/supported way of rendering a full page list/grid is using the [`react-virtualized-auto-sizer`](https://www.npmjs.com/package/react-virtualized-auto-sizer) component, like so: [codesandbox.io/s/3vnx878jk5](https://codesandbox.io/s/3vnx878jk5)

If you're writing your own custom solution, I'm afraid you're on your own for now. I'd like to help but I just can't keep up with all of the issues I'm pinged on lately.

**Comment by kgregory** [comment]
@bvaughn Sorry to necro this thread, but I wanted to add a forked version of your codesandbox: https://codesandbox.io/s/8p8r03788

The list's border was sizing it 2 pixels taller than the height handed down from `AutoSizer`, resulting in a window scrollbar that overlayed the list's own scrollbar.
