### ISSUE TITLE
VariableSizeList doesn't support onWheel event?

### ISSUE THREAD

**Issue by despagito** [bvaughn/react-window#169]
My original list works fine with onWheel, but when I change pure HTML list into VariableSizeList, the onWheel event stopped working.

**Comment by bvaughn** [comment]
Provide a repro (Code Sandbox with instructions) and I'll re-open and look

**Comment by bvaughn** [comment]
Oh sorry, I think I misunderstood your question 

There is no onWheel property. You'll need to use the outerElementType to attach arbitrary custom event listeners like that.

**Comment by bvaughn** [comment]
FYI I added an FAQ entry about this
https://github.com/bvaughn/react-window#can-i-attach-custom-properties-or-event-handlers
