### ISSUE TITLE
Error in console slows down browser

### ISSUE THREAD

**Issue by nick-keller** [bvaughn/react-window#171]
When scrolling stops you can see an error in the console:
```
Uncaught TypeError: Converting circular structure to JSON
```
This can be seen even in the exemple here: https://react-window.now.sh/#/examples/list/fixed-size

On complexe list it even takes a while for the user to be able to interact again, interaction is disabled until the error pops in the console.

**Comment by bvaughn** [comment]
> When scrolling stops you can see an error in the console:
`Uncaught TypeError: Converting circular structure to JSON`

Sounds like you're trying to `console.log` a JSON structure that has circular references somewhere in your application.

> This can be seen even in the exemple here: https://react-window.now.sh/#/examples/list/fixed-size

Sorry, but no such error shows in the console on the demo site.

> On complexe list it even takes a while for the user to be able to interact again, interaction is disabled until the error pops in the console.

See the reason for the interaction bit here: https://github.com/bvaughn/react-window/issues/128#issuecomment-460163077
