### ISSUE TITLE
Preload a second screenfull?

### ISSUE THREAD

**Issue by withintheruins14** [bvaughn/react-window#175]
I made a blazing fast and complex infinite scroll with this. Thank you. Right now, I have one question, could this API support rending a second screenful? I am hopeful that this would keep less unpainted space from appearing when someone scrolls super fast. I moved from `react-infinite` and I could do that with that. I ask because even though my infinite scroll component hierarchy is well optimized - I can still scroll really fast and see unpainted rows.

**Comment by bvaughn** [comment]
I don't think this would actually help much with the case you're describing. Typically when someone scrolls slow-to-medium speed, the overscan items are enough to keep ahead. When someone scrolls "fast" – they swipe through more than a page of items.

If you would like to open a PR (including tests, docs, etc) I'll review a proposal. I'm initially a little skeptical of the change though.

Convince me!

**Comment by bvaughn** [comment]
(By the way I don't intend to act on this issue, so I'm going to close it. That's just how I keep issues manageable. But we can keep talking here, and I'll review PRs~)

**Comment by bvaughn** [comment]
Wanted to add a bit more context to this issue too. The general topic (pre-rendering offscreen elements) is something we (React team) are thinking about and plan on working on in the future at some point. It's not clear to me yet how much a library like react-window will own this, and how much will be built into React, but it is something we're thinking about just FYI 😄

**Comment by ronag** [comment]
@bvaughn any updates on this topic?

**Comment by withintheruins14** [comment]
i believe this was added under a different name and is in the docs now
