### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by impzero** [bvaughn/react-window#176]
I was reading the docs about the **FixedSizeList** [here](https://react-window.now.sh/#/api/FixedSizeList).
What caught my attention was that the author of the package advises us to extend the PureComponent class when we render "compex items".
Whats unclear to me is what "complex items" are?

**Comment by bvaughn** [comment]
There isn't really a simple rule for this. I'm going to just point you at the React docs themselves:
https://reactjs.org/docs/react-api.html#reactpurecomponent

I think the team's general rule is to profile (using the React profiler and/or the Chrome profiler) and try memoization techniques like `PureComponent` if you see performance problems. Profile before and after to verify that it actually does improve the speed of your app. (It might not in some cases.)
