### ISSUE TITLE
the react-virtualized-auto-sizer demo is broken

### ISSUE THREAD

**Issue by rannuo** [bvaughn/react-window#179]
[https://codesandbox.io/s/3vnx878jk5](https://codesandbox.io/s/3vnx878jk5)

browser always is bling

**Comment by bvaughn** [comment]
Works for me.

You'll need to provide more info (e.g. which browser are you using, are there any errors in the console). Otherwise I assume this is just a random, temporary Code Sandbox error.

**Comment by petersendidit** [comment]
If you try it out in Safari v12.0.3 the rows seem to be bouncing left and right.
[Screen Recording 2019-03-15 at 9.16.33 AM.zip](https://github.com/bvaughn/react-window/files/2971463/Screen.Recording.2019-03-15.at.9.16.33.AM.zip)

**Comment by bvaughn** [comment]
Give it another look.

**Comment by rannuo** [comment]
@petersendidit 
The same behavior to me. My browser is Chrome72.0.3626.121. But it's working normally, I just open it.
Thanks to you. @bvaughn
