### ISSUE TITLE
build problem in windows 10

### ISSUE THREAD

**Issue by glromeo** [bvaughn/react-window#181]
[1st console in D:\Workspace\react-window]
>git clone ...
>npm link
>yarn install 
>cd website
>yarn install 
>npm link react-window
>cd ..
>yarn build
>yarn start

[2nd console in D:\Workspace\react-window]
>yarn website:build

At this point I have this issue when on windows 10 which I have not when on OSX Mojave:

> $ yarn website:build
> yarn run v1.13.0
> $ cd website && yarn build
> $ node scripts/build.js
> Creating an optimized production build...
> Failed to compile.
> 
> Module not found: Error: Can't resolve './VariableSizeGrid.js' in 'D:\Workspace\react-window\dist'
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I can see that the windows junctions work fine

**Comment by glromeo** [comment]
To get to this problem I had first to fix the test regexp in webpack to cater for forward slashes like the others do

**Comment by bvaughn** [comment]
This is a hobby project that I work on in my spare time. I don't use (or have) Windows 10, so I can't support it.

Sorry mate.
