### ISSUE TITLE
[Feature] height="content-height"

### ISSUE THREAD

**Issue by natew** [bvaughn/react-window#189]
This would basically solve a fairly tricky problem.

Say you want your table to be the height of the inner content (rows). AutoSizer doesn't do this because it's based on the parent. With react-virtualized you can do this using a CellMeasurer cache and then looking at rowHeights after renders.

This would go hand-in-hand with a maxHeight:

```ts
<List height="content-height" maxHeight={600} />
```

Useful for flex layouts where otherwise it gets squished down to invisible without having an explicit height, but where you also want to show it at it's "natural size".

**Comment by bvaughn** [comment]
Can you provide an HTML example demonstrating what you're referring to?

**Comment by bvaughn** [comment]
Closing due to lack of a response.

**Comment by natew** [comment]
Ah, I think this is only relevant with https://github.com/bvaughn/react-window/issues/6. Without it you can calculate it pretty easily.
