### ISSUE TITLE
VariableSizeList dynamic item height

### ISSUE THREAD

**Issue by muhaimincs** [bvaughn/react-window#190]
I am not sure how to implement this as from the example you fix the height. How do I measure the height of the item element? Perhaps I miss something in this repo. FYI, I'm implementing chat list which has dynamic height.

**Comment by Gajesh-LH** [comment]
+1

**Comment by bvaughn** [comment]
That's not yet supported (unless you want to just in time measure the content, which I wouldn't really recommend).

Check out issue #6 for support status though.

**Comment by lazarnikolic1983** [comment]
Hi @bvaughn, sorry to write on a closed issue. I would just like to clarify this...
Does this mean that if I do not know upfront the height of my list items, there is no way for me to use VariableSizeList to render list items that have dynamic content? For example, if some of my list items have various size images in them, which I do not know upfront, I will not be able to use VariableSizeList to render windowed/virtualized list?

**Comment by willsmanley** [comment]
So there aren't any other packages that can measure the proposed content before rendering?

One of my use cases is to virtualize a messages window. In advance, I know the font, size, and text content. 

If I know that my message bubble is going to be 500px wide, there's no way for me to figure out the height of the bubble unless I render it in the browser?

Just in time measurement kind of defeats the purpose of virtualization... 

By the way thanks for the amazing package! I am using it very nicely for media feeds.

**Comment by henrique-smr** [comment]
> So there aren't any other packages that can measure the proposed content before rendering?
> 
> One of my use cases is to virtualize a messages window. In advance, I know the font, size, and text content.
> 
> If I know that my message bubble is going to be 500px wide, there's no way for me to figure out the height of the bubble unless I render it in the browser?
> 
> Just in time measurement kind of defeats the purpose of virtualization...
> 
> By the way thanks for the amazing package! I am using it very nicely for media feeds.
> 
> EDIT: Well as it turns out, just-in-time rendering actually isn't that bad, especially for simple text.
> 
> This example works perfectly: https://codesandbox.io/s/dynamic-size-of-react-window-list-items-64o9p
> 
> Per this comment: [#6 (comment)](https://github.com/bvaughn/react-window/issues/6#issuecomment-538261156)

Can you please explain to me, how this works?
`<List
            height={listHeight}
            itemCount={chatHistory.length}
            itemSize={getSize}
            width="100%"
            ref={listRef}
>`

getSize is a function, and itemSize expects a number.

**Comment by NadiaIdris** [comment]
Solution I implemented to get `VariableSizeList` row height based on text content:

See the responsive design - https://github.com/NadiaIdris/ts-log-viewer#logs-are-responsive
`VariableSizeList` - https://github.com/NadiaIdris/ts-log-viewer#variablesizelist

```tsx
<AutoSizer
  onResize={() => {
    if (listRef.current !== null)
      listRef.current.resetAfterIndex(0, true);
  }}
>
  {({ height, width }) => {
    return (
      <List
        height={height}
        width={width}
        itemCount={logs.length}
        itemSize={(index) => getItemHeight(logs, index)} // itemHeight in pixels
        itemData={logs}
        ref={listRef as any}
        onScroll={(args) => handleScroll(args)}
      >
        {Row}
      </List>
    );
  }}
</AutoSizer>
```

```tsx
// Function to get the height of each row in the list.
function getItemHeight(logs: LogLine[], index: number) {
  if (logs[index] === undefined) return 30;
  const { msg, ts } = logs[index];
  const formattedTs = formatDateTimeAMPM(new Date(ts * 1000));
  hiddenRowRef.current!["textContent"] = formattedTs + ": " + msg;
  const hiddenRowHeight = window
    .getComputedStyle(hiddenRowRef.current as Element)
    .getPropertyValue("height")
    .slice(0, -2);
  rowHeightsRef.current.push(Number(hiddenRowHeight));
  return Number(hiddenRowHeight);
}
```

**Comment by MaRuifeng** [comment]
I landed on a very similar implementation at https://codesandbox.io/s/react-window-dynamic-row-height-8ftbq, compared to the solution @willsmanley posted. But this example works with a static data list too responding to only window resizing events. The key to is to call the `resetAfterIndex` function of the `VariableSizeList` component upon each row size change!

**Comment by imadx** [comment]
This issue discussion was helpful. I created a CodePen example demonstrating dynamic content height with VariableSizeList at https://codepen.io/Ishan-Madhusanka/pen/abrYjoa

**Comment by usersina** [comment]
I compiled all of the answers above into a somewhat decent solution. It would be used directly as follows:

```tsx
import DynamicRow from '../shared/DynamicRow'
import useDynamicItemSize from '../hooks/useDynamicItemSize'

interface MyListProps {
  items: {id: number, other: string}[]
  onClick: (item: {id: number, other: string}) => void
}

const MyList = ({ items, onClick }: MyListProps) => {
  const { listRef, setSize, getSize, resetAfterIndex } = useDynamicItemSize({
    itemCount: items.length,
  })

  return (
    <div style={{ height: "100%", width: "100%" }}>
      <AutoSizer
        onResize={() => {
          resetAfterIndex(0, true)
        }}
      >
        {({ height, width }) => (
          <List
            ref={listRef}
            height={height}
            itemCount={items.length}
            itemSize={getSize}
            width={width}
            itemData={{ items, onClick }}
          >
            {({ data, index, style }: ListChildComponentProps<MyListProps>) => (
              <div style={style}>
                <DynamicRow
                  data={data.items}
                  index={index}
                  setSize={setSize}
                  windowWidth={width}
                  renderItem={(item: unknown) => (
                    <AyahCard
                      key={item.id}
                      data={item}
                      onClick={() => data.onClick(item)}
                    />
                  )}
                />
              </div>
            )}
          </List>
        )}
      </AutoSizer>
    </div>
  )
}

export default MyList
```

And here's the custom component and hook:

- `DynamicRow.tsx`

```tsx
import React, { useEffect, useRef } from 'react'

interface DynamicRowProps<T> {
  data: T[]
  index: number
  setSize: (index: number, size: number) => void
  windowWidth: number
  renderItem: (item: T) => React.ReactNode
}

const DynamicRow = <T,>({
  data,
  index,
  setSize,
  windowWidth,
  renderItem,
}: DynamicRowProps<T>) => {
  const rowRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (rowRef.current) {
      setSize(index, rowRef.current.getBoundingClientRect().height)
    }
  }, [setSize, index, windowWidth])

  const item = data[index]
  return <div ref={rowRef}>{renderItem(item)}</div>
}

export default DynamicRow
```

- `useDynamicItem.ts`

```tsx
import { useCallback, useRef } from 'react'
import { VariableSizeList as List } from 'react-window'

interface UseDynamicItemSizeProps {
  itemCount: number
}

interface UseDynamicItemSizeReturn {
  listRef: React.RefObject<List>
  setSize: (index: number, size: number) => void
  getSize: (index: number) => number
  resetAfterIndex: (index: number, shouldForceUpdate?: boolean) => void
}

const useDynamicItemSize = ({
  itemCount,
}: UseDynamicItemSizeProps): UseDynamicItemSizeReturn => {
  const listRef = useRef<List>(null)
  const sizeMap = useRef<{ [key: number]: number }>({})

  const setSize = useCallback((index: number, size: number) => {
    sizeMap.current = { ...sizeMap.current, [index]: size }
    if (listRef.current) {
      listRef.current.resetAfterIndex(index)
    }
  }, [])

  const getSize = (index: number) => sizeMap.current[index] || 50

  const resetAfterIndex = (index: number, shouldForceUpdate = true) => {
    if (listRef.current) {
      listRef.current.resetAfterIndex(index, shouldForceUpdate)
    }
  }

  return {
    listRef,
    setSize,
    getSize,
    resetAfterIndex,
  }
}

export default useDynamicItemSize
```

**Comment by Lenur29** [comment]
@usersina Thank you for sharing your implementation. I tested it carefully in my case. It works, but it is quite "expensive" when you need to render chat messages with different content and diffrent height(which you do not know in advance). Calling methods like Element.getBoundingClientRect() cause performance issues when you work with a big list of data. But for simpler cases your solution works. Again thank you 🙏 
I found this artcile - https://gusruss89.medium.com/super-simple-list-virtualization-in-react-with-intersectionobserver-ca340fe98a34. It is quite good and worth attention.
