### ISSUE TITLE
Publish .d.ts files

### ISSUE THREAD

**Issue by MarkFalconbridge** [bvaughn/react-window#194]
Any chance you could add a typescript .d.ts file to the dist folder?

**Comment by leahaense** [comment]
Just install `@types/react-window` package from DefinitelyTyped

**Comment by MarkFalconbridge** [comment]
I have but unfortunately they don't match the actual API. I was hoping that by getting a d.ts file published here then any changes to react-window would be automatically reflected in the associated d.ts file.

**Comment by leahaense** [comment]
I see, they are working fine for me so far

**Comment by MarkFalconbridge** [comment]
The direction prop is missing from GridProps and the layout prop is missing from ListProps. I have to support RTL languages so the direction prop is important to me.

**Comment by martynaskadisa** [comment]
If something is not working correctly with `@types/react-window` or is out of date, feel free to either submit an issue or (even better) a PR to the DefinitelyTyped repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-window/index.d.ts

@bvaughn has already expressed that he's not willing to maintain type definitions for TypeScript in this repo https://github.com/bvaughn/react-window/pull/52#issuecomment-419649277.

**Comment by MarkFalconbridge** [comment]
For completeness - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34396
