### ISSUE TITLE
README.md: Sticky Grid Demo doesn't use bvaugh/react-window

### ISSUE THREAD

**Issue by thielium** [bvaughn/react-window#197]
Not sure if this is intentional or not, but the current demo referenced in the [docs](https://github.com/bvaughn/react-window/commit/061841032662110b3d96d3adba0bed7b1622136b) for the sticky grid (https://codesandbox.io/s/vqk32863wy) uses a fork of `react-window`. I would have expected encouraging custom code in the implementation, not encouraging forking to get custom behavior, but I could be mistaken. 

Just wanted to make the issue so that if it is intentional, any confusion can be put to rest by referencing this issue. If it's not intentional, then maybe it could be updated to be using the official codebase instead? (It was really confusing to me when I first encountered it, but the demo is very exciting).

**Comment by bvaughn** [comment]
Ahh! No, this was an oversight. Thanks for pointing it out.

I'll revert that commit.
