### ISSUE TITLE
Synchronizing a grid and a list in RTL has unexpected behavior

### ISSUE THREAD

**Issue by MarkFalconbridge** [bvaughn/react-window#198]
In the sandbox linked to below, the top list has its scroll position set whenever the grid below is scrolled. If you change the direction props of both the list and the grid to `"ltr"`, all works fine.

If you use it as provided with the list and grid direction props set to `"rtl"` in Chrome the list doesn't appear to render anything, then when you scroll horizontally items do appear but only some of them and they appear to scroll the wrong way. In Firefox the list is initially rendered correctly but as soon as you start to scroll the grid horizontally the list items don't scroll and then disappear.

https://codesandbox.io/s/1077qx12n3

This issue is probably related to #159 .

**Comment by MarkFalconbridge** [comment]
A work around for this is to use the outerRef props for the grid and the list and set the scrollLeft attribute directly on the raw HTMLDivElement. This can be seen here - https://codesandbox.io/s/4qljy74oo7.

Unfortunately, this only partially works when the list used is a VariableSizeList as seen here - https://codesandbox.io/s/x2y1k5p5z4.

**Comment by MarkFalconbridge** [comment]
A further workaround for the VariableSizeList part of this issue is to manually set the width of the style attribute of the innerRef div when setting the outerRef scrollLeft. This is possible in my case because I know how big in total the innerRef needs to be to accommodate the individual items. I'll create a sandbox tomorrow to illustrate this.

**Comment by bvaughn** [comment]
Just an FYI, I don't have the bandwidth to look into this any time soon. Particularly if it is related to #159 (browser bug). If you need this fixed, you'll probably need to  dig into it yourself.

**Comment by bvaughn** [comment]
This was also fixed by #251!

Tested in Chrome, Firefox, and Safari.

**Comment by bvaughn** [comment]
Bug fix released in 1.8.2 - https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md#182
