### ISSUE TITLE
VariableSizeList cache should be invalidated if the list gets modified

### ISSUE THREAD

**Issue by MastroLindus** [bvaughn/react-window#202]
I use a VariableSizeList to render a list. I specify the itemKey prop to ensure that the list knows if a row has changed.

However the computed size for each row is cached and is not cleared if the row itself has changed.

I have noticed in the docs the "resetAfterIndex" method that should clear the cache, but I would expect not to have to call it manually if the row itself (its key) changed, instead of only its size.

**Comment by bvaughn** [comment]
Please take a moment to search other GitHub issues before filing a new one 😄 

This is a duplicate of #199 (filed four days ago). Check out [my answer there](https://github.com/bvaughn/react-window/issues/199#issuecomment-479957451).

Have a good day!
