### ISSUE TITLE
Style object has numbers instead of correct CSS?

### ISSUE THREAD

**Issue by c-dante** [bvaughn/react-window#203]
I'm using this with `preact-compat` -- I don't know if it's a convenience that react's create element provides, but you need to specify the unit when using non-zero values for the `top, bottom, left, right` style properties.

I'm seeing this as an example:
```
style = {
  top: 25,
  height: 25,
  width: '100%',
  position: 'absolute',
};
```

If we generate this directly, we get: `style='top:25;height:25;width:100%,position:absolute` which is invalid css -- it should be: `...top:25px; height:25px;...`

Not sure if that's something you want to address here or if I should open it up with wherever that compat layer is mis-matched. I can see it being useful to propagate the numbers down. I just manually transformed them.

**Comment by TrySound** [comment]
@c-dante This is expected to work in react. Compat package should do the same I think.
https://reactjs.org/docs/dom-elements.html#style

**Comment by c-dante** [comment]
Yep! Looks good. I'll take my issue over there. Thanks for showing me! I haven't dug into React's spec for attributes yet.
