### ISSUE TITLE
Maybe use cross-end for script 'build-flow'

### ISSUE THREAD

**Issue by ealexseen** [bvaughn/react-window#205]
Current problem to branche `issues/6`:
http://prntscr.com/na4i3s

I tried install with OS Window 10:
i think it can will make so 
`"build:flow": "cross-env cp flow-template dist/index.cjs.js.flow && cp flow-template dist/index.esm.js.flow"`

**Comment by bvaughn** [comment]
This is a hobby project that I work on in my spare time. I don't use (or have) Windows, so I can't support it. You're welcome to submit PRs like #180 that fix things about the Windows dev setup, and I'll review them– but this is not something I'm going to invest any time in.
