### ISSUE TITLE
List Randomly Scrolling to Top

### ISSUE THREAD

**Issue by syntithenai** [bvaughn/react-window#207]
I am having a problem with the VariableSizeList. At seemingly random scroll events, it scrolls back to the start of the list.

If I put debug into the onScroll event, I see that the scroll events with gradually increasing scrollOffset and then for no obvious reason I see a scroll event with scrollDirection="backward" and scrollOffset=0

I've added debug to componentDidMount and componentDidUpdate and neither are called prior to the 'bad event' so I don't think it is to do with property updates.

I have put an ugly hack in my onScroll function to save the offsets (except the bad one) and restore the offsets when the component mounts or when the scroll to zero event occurs.

That works (and I want restore scroll on remount between different paths in my application) but I don't feel good leaving the scroll back to position hack in place.

Any thoughts why that 'bad' event is popping up?
 onScroll({scrollDirection,scrollOffset,scrollUpdateWasRequested}) {
        //// save scroll position and restore on remount
		//// avoid random? back to zero scroll events
		if (scrollDirection === 'backward' && scrollOffset === 0) {
			let scrollOffsetString = localStorage.getItem('scrollOffsets');
			let scrollOffsets = {};
			try {
				scrollOffsets = JSON.parse(scrollOffsetString);
			} catch (e) {}
			scrollOffsets = scrollOffsets ? scrollOffsets : {};
			let restoreScroll = scrollOffsets[this.props.location.pathname];
			console.log(['RESTORE SCROLL',restoreScroll,this.props.location.pathname,listRef.current]);
			listRef.current.scrollTo(restoreScroll);
		} else {
			let scrollOffsetString = localStorage.getItem('scrollOffsets');
			let scrollOffsets = {};
			try {
				scrollOffsets = JSON.parse(scrollOffsetString);
			} catch (e) {}
			scrollOffsets = scrollOffsets ? scrollOffsets : {};
			scrollOffsets[this.props.location.pathname] = scrollOffset;
			console.log(['SAVE SCROLL',listRef.current,scrollOffsets,this.props.location.pathname]);
			localStorage.setItem('scrollOffsets',JSON.stringify(scrollOffsets));
			this.listOffset = scrollOffset;
			this.setState({listOffset:scrollOffset});
		}
		
		
cheers

Steve

**Comment by TrySound** [comment]
Please provide codesandbox example. It's hard to provide a good feedback for unformatted piece of code.
