### ISSUE TITLE
Grid or List with Images and Browser Image cache

### ISSUE THREAD

**Issue by lipoolock** [bvaughn/react-window#208]
Hello @bvaughn 
I was looking at this type of implementation : http://pitchfork.highforthis.com/ which displays images in a Grid component.
I noticed that already loaded images are downloaded again and again if you move the scroll up and down many times. I know, this is not a "real user behaviour", but what does this reveals ?

`react-window` handle the DOM to replace displayed items by new ones when scrolling. I guess this is interpreted by the browser like a new DOM item each time and could be the reason why the browser is not (cannot?) using its cache to avoid making calls for media already loaded.

If I'm true, what could be the best way to ask to browser to not remove media from its cache when DOM item is removed ? The idea is to reduce bandwidth if a lot of users are navigating and requiring again and again same images.

Thanks for your reply.

`react-window` is awesome by the way ;-) !

**Comment by bvaughn** [comment]
The browser caches (on disk) recent image requests, provided the resources aren't marked as no-cache. You can see by recording network traffic on the page you sent that the browser serves the duplicate requests with caches from disk.

![Screen Shot 2019-04-12 at 7 58 20 AM](https://user-images.githubusercontent.com/29597/56046733-c350ad80-5cf8-11e9-974a-8fed76df0154.png)

You can always add a second layer of resource caching on top if you want, but I wouldn't think that's necessary or worth doing in most cases.

Glad you're enjoying react-window :)

**Comment by pavle-lekic-htec** [comment]
I agree with @bvaughn, however another in-memory cache might be beneficial for smooth scrolling, because it's faster to load those images from ram memory than it is from disc. So if you encounter scroll performance issues than you might consider investigating.

**Comment by stephyswe** [comment]
Hi, Ive the same issue. Is there a solution? Otherwise you can easily rank up hundred thousands of network requests in an half of hour.

**Comment by waleedshkt** [comment]
I had a similar case where images were reloading upon scrolling backup and down again. This certainly adds up to the GET requests. But if there's some sort of caching implemented for images e.g. CDN is used, then the images will be loaded from in-memory without hitting and making the backend servers go crazy.

Now most browsers (except when in-cognito/ private mode) automatically cache the content loaded for certain period of time set by the user. This cache controlling ability is provided by almost all CDNs. So when next time scrolling infinitely in browser w/o private mode with CDN cache expiry set to (let say 24hrs), the images will be fetched once from CDN, and will then get cached in browser. Then all the remaining requests will be loaded from browser in-memory storage. 

BUT DO NOTE: 
Large items' caching will definitely adversely affect browser performance. Therefore, add some logic to tackle this. May be partially store images locally and load from there

**Comment by paulm17** [comment]
I had this same issue with whatever virtual component that I used.

I'm using Box.com to store my images and I had hundreds of http requests just by scrolling up and down a small sample set.  It would have been bonkers to try with a sample of 1000 images or more.  My use case is for a DAM which may have 10k images or more.  Each scroll basically requires another new http request to get the data. 

To resolve this issue.  I am hitting an endpoint in the backend to request the image and return a base64 string.  Once I have the string I then store it using idb-keyval.  To update component, I'm setting a local state.

Here is my code, feel free to adjust to your own use case:

```
import { useCallback, useState } from "react"
import { useEffectOnce } from "react-use"
import { get, set } from "idb-keyval"
import { DamFile, DamImage } from "../../../../types/file"
import { useRef } from "react"

interface imageComponentProps {
  item: DamFile
}

function ImageComponent({ item }: imageComponentProps) {
  const isAliveRef = useRef(true)
  const [base64Img, setBase64Img] = useState("")

  const genImage = useCallback((type: string, images: DamImage[]) => {
    const filterFunc = (image: DamImage) => {
      if (image.size) {
        if (image.size.name === type) {
          return image
        }
      }
    }

    if (type === "Gallery") {
      return images.filter(filterFunc)[0].url as string
    } else if (type === "Drag Icon") {
      return images.filter(filterFunc)[0].base64 as string
    }

    return ""
  }, [])

  const getImage = useCallback(() => {
    if (item.type.name === "folder") {
      return
    }

    const url = genImage("Gallery", item.DamImages)
    const id = Buffer.from(item.id).toString()

    get(id).then(async (val) => {
      if (val !== undefined) {
        if (isAliveRef.current) setBase64Img(val)
      } else {
        const response = await fetch(
          `http://${process.env.NEXT_PUBLIC_DAM_HOST}:${process.env.NEXT_PUBLIC_DAM_PORT}/api/dam/proxyFile?url=${url}&type=base64`,
          {
            method: "get",
          }
        )
        const data = await response.json()
        set(id, data.base64)

        if (isAliveRef.current) setBase64Img(data.base64)
      }
    })
  }, [item, genImage])

  useEffectOnce(() => {
    getImage()

    return () => {
      isAliveRef.current = false
    }
  })

  return (
    <>
      {base64Img != "" && (
        // eslint-disable-next-line
        <img className="w-full h-full" src={base64Img} alt={item.name} />
      )}
    </>
  )
}

export default ImageComponent
```
