### ISSUE TITLE
Document standalone libs built using react-window

### ISSUE THREAD

**Issue by pupudu** [bvaughn/react-window#213]
Thank you for creating react-window. And I apologise if a similar issue has already been created, I searched and failed to find. 

This is a request to **add the list of standalone libraries built using react-window to the documentation of RW**. As you might have already guessed, I myself made one recently, https://github.com/pupudu/window-table. (released on npm, but is under heavy development atm).

If you are cool with the idea, I can make a PR for that.

Thank you very much.

**Comment by bvaughn** [comment]
Hey. I don't know if I want the hassle of maintaining such a list right now, to be honest. I'd probably just redirect people to [the NPM list of dependents](https://www.npmjs.com/browse/depended/react-window).

Maybe at some point in the future when I'm not falling so far behind on everything, I'll add such a list.

Thanks for your understanding 🙇

**Comment by pupudu** [comment]
All good Brian. I understand

**Comment by JESii** [comment]
Thanks for the NPM dependency list -- never knew about that!
