### ISSUE TITLE
How to use max-height instead of height for FixedSizeList

### ISSUE THREAD

**Issue by ajayns** [bvaughn/react-window#214]
In the case that the list has the possibility of being of very few items that it doesn't even fill the specified fixed height, it keeps rest of the space empty. I'd prefer if it automatically wrap itself as per the height of the content, much like how max-height would work. 

Any suggestions on how to implement this? For the library maybe it'd be great if it took care of this internally.

**Comment by nihgwu** [comment]
that should not be builtin, you could implement it by `<List height={Math.min(containerHeight, itemHeight * itemCount) />`

**Comment by bvaughn** [comment]
The approach @nihgwu shows above is correct.

**Comment by ajayns** [comment]
Thank you!
