### ISSUE TITLE
How to implement Scroll Memory?

### ISSUE THREAD

**Issue by Vrq** [bvaughn/react-window#216]
I recently switched to react-window but noticed my old solution for restoring scroll memory doesn't work anymore. 
Previously used: https://www.npmjs.com/package/react-router-scroll-memory

What is the proper way of restoring scroll position with react-window? 

Currently, I have a workaround with **initialScrollOffset** prop (passing index*row_height) but it feels hacky.

**Comment by bvaughn** [comment]
The library offers an `initialScrollOffset` prop as well as `scrollToItem` and `scrollTo` (offset) API methods. Seems like these should be sufficient?

If not, please provide a link to a sandbox showing what you've tried and why it's not sufficient and we can talk more.

**Comment by Vrq** [comment]
Is there a standard way of doing it?
For example, can I somehow get the current position of the list or do I have to find out the offset value myself?

**Comment by bvaughn** [comment]
> For example, can I somehow get the current position of the list

The docs show that an `onScroll` prop is supported. Have you checked out the docs? 😄

> I also noticed that when the initialScrollOffset value changes the list doesn't re-render

As its name suggests, it's only used for the _initial_ render.

![Screen Shot 2019-04-17 at 8 42 56 AM](https://user-images.githubusercontent.com/29597/56301514-d2ff3600-60ec-11e9-8808-72588a70b1b6.png)

**Comment by Vrq** [comment]
I read through, but apparently to quick. 
Gotta check again, thanks!

**Comment by mperezguendulain** [comment]
Thanks @bvaughn, I was looking for this functionality too. I have a question, where I can find more documentation like this?, because I searched [https://react-window.now.sh/](https://react-window.now.sh/) and only I found an example for `scrollToItem`, not `initialScrollOffset` or `scrollTo`.

**Comment by mperezguendulain** [comment]
Sorry, I didn't look hard enough, I've already found documentation: [https://react-window.now.sh/#/api/FixedSizeList](https://react-window.now.sh/#/api/FixedSizeList)
