### ISSUE TITLE
Scroll To Item on React.useEffect mounting with AutoSizer

### ISSUE THREAD

**Issue by kcunanan** [bvaughn/react-window#219]
Hi,

I'm using the React.useEffect` hook to attempt to initiate a `scrollToItem` function call on a `FixedListComponent` wrapped in the virtualized `AutoSizer` library. However, it appears that the `ref` doesn't have a `current` component yet due to being wrapped within `AutoSizer`.

Is there a `react-window` alternative to `AutoSizer` that allows me to use scrollToItem on mount?

Here's a sandbox:
https://codesandbox.io/s/j4v1v28519

Thanks in advance!

**Comment by kcunanan** [comment]
Hi,

I was able to resolve this using state instead `AutoSizer` (sandox: https://codesandbox.io/s/m353m03jo9)

But now my issue is that the `scrollToItem` scrolls to the `index + 1` element instead of just the `index`. Wondering if there's a workaround for this as well.

**Comment by kcunanan** [comment]
Using `start` on `scrollToItem` has resolved my issue🥇

**Comment by rawadrifai** [comment]
@kcunanan I am stuck trying to scroll to the bottom when a react native page loads. It has a <Content> component, which I get a ref for using useRef as such.

`const content = useRef(null)`
`<Content ref={content}>`

then I do the following in useEffect:
```
useEffect(() => {
    content.current._root.scrollToEnd();
});
```

It doesn't work. It works if I do `content.current._root.scrollToEnd();` on a button click or something. But I want the page to be scrolled all the way to bottom on load.
