### ISSUE TITLE
If scrollbars are visible by default in OS horizontal scrollbar appears in vertical FixedSizeList

### ISSUE THREAD

**Issue by istarkov** [bvaughn/react-window#22]
If scrollbars are visible by default in OS horizontal scrollbar appears in vertical FixedSizeList at least in Chrome browser

![image](https://user-images.githubusercontent.com/5077042/43064997-2d17e760-8e69-11e8-868f-c53cc5724421.png)

How to reproduce
Set show scrollbars always 
![image](https://user-images.githubusercontent.com/5077042/43065052-51948d96-8e69-11e8-97d3-9652f4cbaa9b.png)

open 
https://react-window.now.sh/#/examples/list/fixed-size

scroll a little bit down and you will see a horizontal scrollbar (scroll overflow is on scrollbar width)

**Comment by istarkov** [comment]
Setting width=100% of inner viewport seems like solves the issue

![image](https://user-images.githubusercontent.com/5077042/43065206-c4338b4a-8e69-11e8-9944-c6beee1467e1.png)

**Comment by istarkov** [comment]
But width:100% doesnt help if inner row has big uwrapable content like

here https://codesandbox.io/s/k56mm6301o

**Comment by istarkov** [comment]
The other way is to set `position: "relative",` on inner viewport

**Comment by bvaughn** [comment]
> But just width:100% doesnt help if inner row has big uwrapable content like
here https://codesandbox.io/s/k56mm6301o (scrollbar appears again)

I think the horizontal scrollbar _should_ appear in this case.

**Comment by TrySound** [comment]
Do you mean non-mac users should work with ugly ui?

**Comment by bvaughn** [comment]
Come on man, don't put ridiculous words in my mouth.

@istarkov said that in the second case– if a row contained content that was too wide to fit within 100%, horizontal scrollbars would still appear. I said this _should_ happen, because I know of some cases where people _intentionally_ want a vertically windowed list to scroll horizontally.

**Comment by bvaughn** [comment]
The fix will go out with 1.0.4

**Comment by bvaughn** [comment]
Fix has been deployed. You can verify it on the website.

**Comment by TrySound** [comment]
Thanks, Brian!
