### ISSUE TITLE
onItemsRendered shouldn't be call while scrolling

### ISSUE THREAD

**Issue by MatthieuCoelho** [bvaughn/react-window#222]
Hello,

I'm using react-windows with react-window-infinite-loader.

When user is scrolling it keeps calling onItemsRendered which trigger a new fetch of data, which results into a lot of HTTP request.

How do you solve this problem ?

**Comment by bvaughn** [comment]
`onItemsRendered` _should_ be called when scrolling 😄

> **onItemsRendered: function**
> Called when the range of items rendered by the list changes.
>
> This callback will only be called when item indices change. It will not be called if items are re-rendered for other reasons (e.g. a change in isScrolling or data params).

I'm not sure why you would be fetching data in `onItemsRendered`. Happy to give a suggestion if you can provide a little more context 😄 Going to close this issue though since it's not actionable

**Comment by MatthieuCoelho** [comment]
It seems like InfiniteLoader from react-window-infinite-loader is fetching data when FixedSizeList trigger onItemsRendered.
So when I'm scrolling, onItemsRendered is called and InfiniteLoader fetch data for the new index. If I use a small  minimumBatchSize on InfiniteLoader, it will trigger a lot of HTTP request.
I was thinking that InfiniteLoader should only fetch data on scrollend event, after a fixed timer to debounce it.

**Comment by bvaughn** [comment]
Ah. Maybe you could implement your own debounce logic in your `loadMoreItems` callback.

Realistically, I don't think I'll be spending any time in `InfiniteLoader`, other than what I've already done to port it over to work with react-window. And I don't think it makes sense to debounce `onItemsRendered` itself. That would be a breaking change that would require a new major version release (and I don't think it would be a good change).

Sorry mate.

**Comment by MatthieuCoelho** [comment]
@bvaughn Thanks for your help.
I ended using a debouncing library (awesome-debounce-promise) to debounce loadMoreItems.

**Comment by bvaughn** [comment]
Nice, nice. I'm glad that worked out for you then! I like the idea of debouncing logic being done (or not) in application code, since that leaves the possibility of no-debounce behavior for those that prefer it. Thanks for the update!
