### ISSUE TITLE
How to use react-window on mobile to hide menu bars?

### ISSUE THREAD

**Issue by Vrq** [bvaughn/react-window#224]
Normally when a website is scrolled down on mobile the menu bar hides automatically. 
However, with react-window, the scroll happens inside a div and the whole page doesn't scroll which makes the menu bar to stay.

Is there a known workaround to make it possible? 
The goal is to make the user be able to hide menu bar when scrolling the list.

**Comment by bvaughn** [comment]
Essentially you're asking about support for a component like react-virtualized WindowScroller, which this library does not have. There may be a way you could rig something up, but it's not something the library supports out of the box. Sorry!
