### ISSUE TITLE
Data attributes are not being forwarded to rendered HTML elements

### ISSUE THREAD

**Issue by mackness** [bvaughn/react-window#225]
This is probably not a bug but I thought I would bring it up anyway because it might be nice to have. 

I have started using [react testing library](https://testing-library.com/react) recently and one of the suggested patterns for selecting elements is to add a `data-testid` attribute to the element you're targeting in a test. 

I tried to add `data-testid` attribute to `FixedSizeList` but the rendered `div` did not have the `data-testid` attribute.

I would be more than happy to submit a PR if you think it is a good idea to forward data attributes to rendered HTML.

For reference here is the [component](https://github.com/mackness/React-Testing-Library-Sandbox/blob/5c9257e353717d543c4d5fd4f4eb16b562ad8ecd/client/src/components/PokeList.tsx#L66) and the [test](https://github.com/mackness/React-Testing-Library-Sandbox/blob/5c9257e353717d543c4d5fd4f4eb16b562ad8ecd/client/src/components/__tests__/PokeList.spec.tsx#L92).

**Comment by bvaughn** [comment]
I don't think this is something I want to add direct support for, but you should be able to use the `outerElementType` prop for. You can attach any arbitrary props you want with it. 😄 

> **`outerElementType: React$ElementType = "div"`**
Tag name passed to document.createElement to create the outer container element. This is an advanced property; in most cases, the default ("div") should be used.

**Comment by mackness** [comment]
Ya that works for me, thanks!

**Comment by LucianABC** [comment]
This is not working for me, data attributes are not being forwarded.
