### ISSUE TITLE
overscanRowsCount vs overscanRowCount

### ISSUE THREAD

**Issue by nihgwu** [bvaughn/react-window#226]
it's `overscanRowCount` in `react-virtualized`, but now it's `overscanRowsCount`, while we have `rowCount`, I'm not a native speaker so I'm just wondering which is proper?  Right now I have to map `overscanRowCount` to `overscanRowsCount` https://github.com/Autodesk/react-base-table/pull/19/files#diff-4177f614bd864f6344923aed07c2edeaR91

**Comment by bvaughn** [comment]
I don't know if either one is more or less proper. Sorry! 😄

**Comment by nihgwu** [comment]
So I'm wondering if we could make the naming consisitency? like `overscanRowCount`

**Comment by bvaughn** [comment]
No. react-virtualized is not a library I support anymore, so I don't plan on releasing an update to it.

And I don't think it's worth making a breaking change to react-window to better mirror react-virtualized API. That isn't really a goal this library has.

**Comment by nihgwu** [comment]
I understand you concern, I think we could deprecate `overscanRowsCount` in flavor of `overscanRowCount`, just like `tagName` to `elementType`, I'm not saying to mirror the RV's API, but the prop's name itself is confusing with `rowCount`

**Comment by bvaughn** [comment]
Ah. I don't really care about mirroring RV's API naming conventions at this point, but `overscanRowsCount ` vs `rowCount ` is a stronger argument.

I would be willing to accept a PR that deprecates the name with a warning, similar to https://github.com/bvaughn/react-window/blob/f2b2106cc828e9828cf2940411e5eab67f1d7aa6/src/createGridComponent.js#L787-L795

Interested in contributing? 😄
