### ISSUE TITLE
pointer-events: none never clears after scrolling when used w/ Preact

### ISSUE THREAD

**Issue by aaronjensen** [bvaughn/react-window#227]
I don't know if this is preact specific, but 1.8.1 is broken and 1.8.0 is not, likely https://github.com/bvaughn/react-window/commit/59df8ddfc97c7f3dd1d3063eb4d905a578e90455 is the culprit.

The problem is that as soon as you scroll, `pointer-events: none` gets set and never gets unset.

**Comment by bvaughn** [comment]
Sounds like a Preact bug. React Window documentation site works correctly, and I haven't heard any other reports of this issue. (Seems like it would be a pretty major breakage.)

**Comment by aaronjensen** [comment]
It is likely the same issue as this: https://github.com/developit/preact/issues/853 which is fixed in (the unreleased) Preact X

See repro: https://jsfiddle.net/deo8cahw/

`null` works, is there a reason [you changed it to `undefined` instead of `null`](https://github.com/bvaughn/react-window/commit/58c8c6a89f9a24525d23d52a78a87534e1b8dc6d)?

We can stay on `1.8.0` or `1.7.2` until we move to Preact X, so we're not blocked by this. Feel free to close since it's not really a `react-window` issue unless you want/can switch back to `null`. Thanks!

**Comment by bvaughn** [comment]
> is there a reason you changed it to `undefined` instead of `null`?

Not if I recall. Probably just an assumption that `undefined` more closely mirrored the unset value.

**Comment by aaronjensen** [comment]
Would it make sense to revert that change since they should be effectively the same thing but one works w/ the current version of Preact? If not, we can close this. Thanks!

**Comment by bvaughn** [comment]
Cleaning up GitHub issues today. The [commit](https://github.com/bvaughn/react-window/commit/58c8c6a89f9a24525d23d52a78a87534e1b8dc6d) you linked to was from PR #210.

Given that this change makes the validator happy, and will also work for the upcoming Preact release, I think I'm going to leave it in place. If you would like to open a PR that satisfies both Preact and the validator though- I'd be happy to tweak it! 😄

Thanks for understanding!
