### ISSUE TITLE
Codesanbox examples has useless key in children function

### ISSUE THREAD

**Issue by istarkov** [bvaughn/react-window#23]
Codesandbox examples contains key in children function

![image](https://user-images.githubusercontent.com/5077042/43066696-023a56ea-8e6e-11e8-9bb7-583b7cd039db.png)

It's not needed.

Also version set is alpha
fixed in #24

**Comment by bvaughn** [comment]
Ah, right. Looks like this didn't get removed when I converted the children prop from a regular function to a React element.
