### ISSUE TITLE
If you have itemData, do you need itemCount?

### ISSUE THREAD

**Issue by janhesters** [bvaughn/react-window#231]
If you have `itemData`, do you still need `itemCount`?

Because the code would look like this

```js
<List
  className="List"
  height={height}
  itemCount={items.length}
  itemSize={35}
  itemData={items}
  width={width}
>
  {Row}
</List>
```

**Comment by bvaughn** [comment]
Yes, as the docs will confirm.

`itemData` is untyped. It can be anything (including undefined)
