### ISSUE TITLE
Support UMD Release

### ISSUE THREAD

**Issue by stunaz** [bvaughn/react-window#232]

**Comment by bvaughn** [comment]
I would accept a PR that adds a UMD build, if you'd like to submit one.

**Comment by stunaz** [comment]
I wish I could help.Could you flag it as `help wanted`, hopefully somebody would help.

**Comment by bvaughn** [comment]
Honestly, it's not something I care about supporting. If you have a use case for it,  PRs are welcome though 😄

**Comment by bvaughn** [comment]
Cleaning up issues today. Don't intend to actively support this one so I'm going to close it.

**Comment by bvaughn** [comment]
v1.8.5 adds a UMD build

**Comment by stunaz** [comment]
@bvaughn thanks a lot :-)
