### ISSUE TITLE
react: All visible rows are re-rendered on update when Row function depends on state

### ISSUE THREAD

**Issue by warmar** [bvaughn/react-window#236]
I am displaying a large, dynamic data set, each row of which is stored in the state of a react component. My Row function is thus dependent on that state. This causes all visible rows to be re-rendered every time a row is added or removed.

I originally noticed this problem when I discovered that the tool tips on each row would flicker on state change, and I've created a demo on codesandbox to illustrate that issue:
https://codesandbox.io/s/2zk5q6344r
Note 1: The tooltips flicker every time a row is added
Note 2: Each visible row is re-rendered (in devtools) every time a row is added.

Is this known and expected behavior?
Is there a straightforward way around this?
Is there a fundamental problem with the Row function being dependent on state?

Thank you in advance.

**Comment by TrySound** [comment]
FixedSizeList child is a component. In your example row is recreated on every render as a result it's remounted on every render.
Here's how you may optimise this. All rows are still updated because you change itemData but at least not remounted.
https://codesandbox.io/s/5k095o3n1p

**Comment by bvaughn** [comment]
Thanks for the answer, Bogdan!

**Comment by warmar** [comment]
Woops, I must have missed this page in the documentation:
https://react-window.now.sh/#/examples/list/memoized-list-items

Thanks so much for your help!

**Comment by LoganArnett** [comment]
Is there an easy way to implement the solution from @TrySound with a VariableSizeList? Currently trying to use this with a basic list that gets added to and have to be able to pass additional props to each row item to handle the item size
