### ISSUE TITLE
[documentation] Is this supposed to be "start" instead of "smart"?

### ISSUE THREAD

**Issue by ricokahler** [bvaughn/react-window#241]
Is this supposed to be "start" instead of "smart"?

![image](https://user-images.githubusercontent.com/10551026/57746993-a0237000-76a1-11e9-83c0-dd769e091cac.png)

[From here](https://react-window.now.sh/#/examples/list/scroll-to-item)

I stared at this page for a while wondering what "smart" alignment was and then I realized it's probably "start"!

Just thought I'd bring it up. Thanks for the amazing library!

**Comment by bvaughn** [comment]
No. Smart is correct. It's in the docs

**Comment by bvaughn** [comment]
"smart" is an option 🙂 check the docs
