### ISSUE TITLE
TypeScript support 

### ISSUE THREAD

**Issue by stephenotalora** [bvaughn/react-window#245]
this is more of a questions and as such it can be flagged as so. As the trend is to continue to move towards TypeScript are there any plans to add TS support to react-window?

**Comment by bvaughn** [comment]
Nope.

Definitely Typed repo is the place to go for libdefs of this library

**Comment by lishine** [comment]
why not, why not let somebody type it ?

**Comment by bvaughn** [comment]
Nope. Because I don't want to maintain it. DefinitelyTyped works for a lot of libraries. It can work for this one too.

**Comment by stephenotalora** [comment]
@bvaughn @lishine there’s already an npm module that can be used independently. Please take a look at / `npm i` @types/react-window https://www.npmjs.com/package/@types/react-window

**Comment by bvaughn** [comment]
Thanks for sharing the line, @stephenotalora !

**Comment by lishine** [comment]
Thanks all
