### ISSUE TITLE
[Feature Request] Reverse direction support

### ISSUE THREAD

**Issue by GonzaloRizzo** [bvaughn/react-window#247]
Is there any plans to implement something like reverse direction support? I'm currently implementing a chat application and it would be very handy

There seems to be some work done here https://github.com/corupta/react-window/tree/npm

**Comment by bvaughn** [comment]
No current plans, no

**Comment by joshfarrant** [comment]
@bvaughn Would you be open to a PR that adds reverse direction support, possibly behind a `reversed={true || false}` prop?

**Comment by bvaughn** [comment]
@joshfarrant Feel free to create a PR. I'll be happy to review it, but I won't make any promises about it landing.

I would say that I think `layout="vertical-reverse"` (or something similar) would maybe make more sense. We already have `direction` and `layout` props. I don't want to be in a place where someone could set `layout="horizontal" direction="rtl" reverse={true}` because I don't even know what that would mean.

**Comment by joshfarrant** [comment]
Thanks for the quick response. Agree that `layout="vertical-reverse"` makes more sense. I'll have a look into it and let you know if I make any progress.

**Comment by kindmind** [comment]
@GonzaloRizzo what did end up moving forward with for your chat application? I'm looking for ideas as I go about implementing chat-like functionality that requires reverse virtualized-list functionality.

**Comment by vinujan59** [comment]
Anyone working on this feature? is there any workaround for this?

**Comment by michaeljguarino** [comment]
I'd be interested if anyone has done this in a fork as well.  There's react-window-reversed, but it appears to use css transforms which seems far less than ideal.

**Comment by getnashty** [comment]
@michaeljguarino @vinujan59  sorry for the old thread, but did either of you find a solution you liked for reverse direction? I'm currently using a dynamically sized header, but it makes things pretty complex.

**Comment by ljs19923** [comment]
The reverse mode has been added? Really useful for a chat mode

**Comment by henrycjchen** [comment]
looking forward to vertical-reverse

**Comment by neokofg** [comment]
after 6 years, still no reverse?

**Comment by corupta** [comment]
Back in the day, I implemented it for myself for some specific case, [https://github.com/corupta/react-window/tree/npm](corupta/react-window)
It did work but wasn't polished for a PR I think (check out npm branch) can be used with `npm install --save react-window-reversed`
If new version features are not needed for you, you can use that, I don't have any plans to merge latest version.
