### ISSUE TITLE
Sporadic scroll jumping to the top without error message 

### ISSUE THREAD

**Issue by mattch** [bvaughn/react-window#248]
I have a FixedSizeList that works perfectly (stops scrolling at the bottom of the list) most of the time, but sporadically will jump to the top of the list while scrolling (usually towards the bottom but sometimes in the middle).   From what I've read in other issues and what I've seen, this is normal behavior if the list scrolls past the itemCount.   My itemCount is set to the myArray.length - 1, so I don't believe itemCount is being set incorrectly.

This problem happens independently of setting itemKey and/or itemData. When I do set the key, I verified it's not a duplicate.

This is on Chrome/OSX. There are no error messages when the jump happens.

My itemData is an array that gets generated in ComponetWillUpdate and the constructor from the props.  The rows of my list are one of two types of components UserRow or ItemRow.  

The problem seems more likely to occur when I have a shorter list followed by a longer list.  For example, if I have a list of 200 followed by a list of 1000, the scroll will jump to the top around 200 of the 1000 list.  It seems like itemCount is not being updated properly, tho I'm setting it to the array length in the render.

Any suggestions would be greatly appreciated?  Is this being caused by a corrupt itemCount or itemData?  Is any of the FixedSizedList required to be in the parent state? 

Unfortunately, I can't put a working version in codesandbox, but here's all the relevant code:

```
    let itemCount = measureRegJson.perPatient ?  patientList.length -1 : this.tableEncounters.length - 1;
    let itemData = measureRegJson.perPatient ? patientList : this.tableEncounters;   //array of objects.
```
```
        <AutoSizer >
          {({ height, width }) => (
            <List
              className="List"
              itemData={itemData}
              itemCount={itemCount}
              itemSize={40}
              width={width}
              height={height}
              overscanCount={10}
              onScroll={this.handleOnScroll}
              itemKey={ (index, data) => measureRegJson.perPatient ? `${measureRegJson.name}${data[index].name}${data[index].dateOfBirth}` : this.generateEncKey(data[index])}
            >
              {tableBody}
          </List>
          )}
        </AutoSizer>
```

```
    let tableBody;
    if (measureRegJson.perPatient) {  // One row per patient
      tableBody = ({data, index, style }) => {
        console.log(data, index)

        const patient = data[index];
        //console.log(patientList.length, index)
        return <UserRow style={style} statsCallback={this.handleRowChange.bind(this)} rowIndex={index} rowSelected={rowSelected} showByMeasure={true} patient={patient} measureDef={measureRegJson} questionName={questionMeta.name} />
      }
    } else {                        // One row per eligible encounter
      tableBody = ({data, index, style}) => {
        console.log(data, index)
        const enc = data[index];
        //console.log(this.tableEncounters[index].patient.dateOfBirth, this.tableEncounters[index].dateofservice)
        return <ItemRow style={style} statsCallback={this.handleRowChange.bind(this)} rowIndex={index} rowSelected={this.state.rowSelected} showByMeasure={true} patient={enc.patient} encounter={enc} measureDef={measureRegJson} questionName={questionMeta.name} />
      }
    }
```

**Comment by bvaughn** [comment]
> Unfortunately, I can't put a working version in codesandbox, but here's all the relevant code

If you provide a repro case (actual working code, in Code Sandbox) I'd be happy to take a look. I don't really have time to look at partial code examples and guess though. Hope you understand!

**Comment by mattch** [comment]
Yeah, I understand.  I'll try.   Can you answer one question tho?  Do I need to clear a cache with FixedSizedList when changing between list data (new itemData and itemCount)?

**Comment by bvaughn** [comment]
> Do I need to clear a cache with FixedSizedList when changing between list data

What cache are you referring to?

You would need to reset `VariableSizeList` cache:
https://github.com/bvaughn/react-window/issues/199#issuecomment-479957451

But shouldn't need to clear `FixedSizeList`.

**Comment by chris-fran** [comment]
@mattch did you find a solution for this?

**Comment by mattch** [comment]
I solved this by manually detecting when it jumps to the top, and then manually moving the scroll position back to where it's supposed to be. It's not a perfect solution, but it worked well enough for my needs.

**Comment by jmrossy** [comment]
In case it helps others, I used some persisted state (i.e. outside the component) and the initialScrollOffset prop to solve this problem
