### ISSUE TITLE
Is there any way to have an :hover css modifier at the row level ?

### ISSUE THREAD

**Issue by jeremieroy** [bvaughn/react-window#252]
Assuming a multi-columns table, it is often interesting to be able to highlight the whole row under the cursor with an :hover css modifier.
I didn't find any clean way to achieve this...
I can highlight a single cell but that is not very helpful ^^'
Any idea is welcome :D

**Comment by TrySound** [comment]
You may highlight row manually with javascript for grids. Or you may just use list which allows you to render the whole row. My tables are all FixedSizeList based.

**Comment by jeremieroy** [comment]
I am using VariableSizeGrid, but there is no "row"  element.
> You may highlight row manually with javascript for grids
Not sure what you have in mind, something like keeping track of the current row index under the mouse icon on a onMouseMove event ?
Then keeping it in the state and manually setting a "is-hovered" class modifier on every cell item in the row ?
Would work I guess, itl feels a bit heavy for such a feature :/

**Comment by TrySound** [comment]
Yes, you may use `onMouseEnter` and `onMouseLeave` for that. Or use VariableSizeList instead.

**Comment by bvaughn** [comment]
You could use the `itemData` prop to share the current row and a callback, e.g.:
https://codesandbox.io/s/bvaughnreactwindow-grid-row-hover-9j28g

**Comment by NexxLuo** [comment]
Can I add an outter row element ? How to do it ?

**Comment by bvaughn** [comment]
No, not to a grid

**Comment by sonofjack** [comment]
@NexxLuo I wasn't happy with the performance by storing the hovered row index in state.
What I did instead was to give every rendered cell a class associated with the `rowIndex`
example. `cell--hover${rowIndex}`.

Then on `onMouseEnter` you can add class to each cell with a specific `rowIndex`.

```
const onCellMouseEnter = (rowIndex) => {
    const cells = document.getElementsByClassName(`cell--hover${rowIndex}`);
    if (cells.length > 0) {
      for (const cell of cells) { cell.classList.add('tablegrid__cellhovered'); }
    }
  };
```

Hope this helps.

**Comment by bvaughn** [comment]
Thanks for sharing another solution, @sonofjack 😄 

I suppose you could also use a descendant selector and just add/remove classes from the grid itself.

**Comment by sonofjack** [comment]
@bvaughn Yes that would be even better, thank you!

**Comment by episodeyang** [comment]
Just want to say this thread is awesome. Thank you all for your comments!

**Comment by NexxLuo** [comment]
This way just solve the hover class problem. If I want to make the row draggable , there is not row element, can`t achieve it. Is there any other way ?

**Comment by TrySound** [comment]
Then you should not use grid. Use list component instead.

**Comment by NexxLuo** [comment]
> Then you should not use grid. Use list component instead.

But I really want to use the grid features , columns  lazy load .

**Comment by NexxLuo** [comment]
> No, not to a grid

Is it possible to provide an options to make the grid cell wrapped a row element ? I think it`s very useful.

**Comment by thupi** [comment]
> I suppose you could also use a descendant selector and just add/remove classes from the grid itself.
> @bvaughn  

For now, I went with the solution from @sonofjack but could you share a snippet or a bit more details on how to do something like your suggestion above :-) ?

**Comment by jhoneybee** [comment]
```tsx

<Grid>
                {({ style, rowIndex, columnIndex }) => {
                    const cellElement = (
                        <Cell
                            style={style}
                            className={`summer-cell--hover-${rowIndex}`}
                            onMouseEnter={() => {
                                innerRef.current.querySelectorAll(`.summer-cell--hover-${rowIndex}`).forEach((element: HTMLDivElement) => {
                                    element.style.backgroundColor = 'hsl(0deg 0% 96%)';
                                })
                            }}
                            onMouseLeave={() => {
                                innerRef.current.querySelectorAll(`.summer-cell--hover-${rowIndex}`).forEach((element: HTMLDivElement) => {
                                    element.style.backgroundColor = 'unset';
                                }) 
                            }}
                            key={`row-${rowIndex}col-${columnIndex}`}
                        />
                    )

                    return cellElement
                }}
</Grid>
```

1. add className "prefix-${rowIndex}"
2. onMouseEnter => change the background color according to rowId
3. onMouseLeave => restore background color

> My English is not good, this is the use of translation software. There may be grammatical problems

**Comment by Damian-LW** [comment]
```css
// style.css

.tablegrid__cellhovered {
  background-color: red;
}
```

```ts
import AutoSizer from 'react-virtualized-auto-sizer'
import { FixedSizeGrid as Grid } from 'react-window'
import './style.css'

const onCellMouseEnter = (rowIndex: number) => {
  const cells = document.getElementsByClassName(`cell--hover${rowIndex}`)
  if (cells.length > 0) {
    for (const cell of cells) {
      cell.classList.add('tablegrid__cellhovered')
    }
  }
}

const onMouseLeave = (rowIndex: number) => {
  const cells = document.getElementsByClassName(`cell--hover${rowIndex}`)
  if (cells.length > 0) {
    for (const cell of cells) {
      cell.classList.remove('tablegrid__cellhovered')
    }
  }
}

const Cell = ({
  rowIndex,
  style,
  columnIndex,
}: {
  style: React.CSSProperties
  rowIndex: number
  columnIndex: number
}) => {
  return (
    <div
      style={{
        ...style,
      }}
      className={`cell--hover${rowIndex}`}
      onMouseEnter={() => onCellMouseEnter(rowIndex)}
      onMouseLeave={() => onMouseLeave(rowIndex)}
    >
      row{rowIndex} col{columnIndex}
    </div>
  )
}

const VirtualGrid = () => {
  return (
    <AutoSizer>
      {({ width, height }) => {
        return (
          <Grid
            columnCount={100}
            columnWidth={100}
            height={height}
            rowCount={1000}
            rowHeight={35}
            width={width}
          >
            {({ style, rowIndex, columnIndex }) => (
              <Cell
                style={style}
                rowIndex={rowIndex}
                columnIndex={columnIndex}
              />
            )}
          </Grid>
        )
      }}
    </AutoSizer>
  )
}

export default VirtualGrid


```
