### ISSUE TITLE
[Question] Recommended way to make FixedSizeGrid responsive?

### ISSUE THREAD

**Issue by pkacprzak** [bvaughn/react-window#253]
I was previously working with React Bootstrap Col and Row elements to make my grid responsive, and now, since the number of elements in the grid is too large for non-windowing rendering to be both allow users to filter the list and be efficient at the same time, I found react-window to be good for my needs but I'd like to make it responsive somehow. Is recalculating manually values for columnCount, rowCount, columnWidth above the component in the tree and then passing them a good way of handling this?

**Comment by bvaughn** [comment]
I'm not sure I understand this question, sorry. You will need to manually calculate the number of columns and rows, as well as their size, yes. This library is not a data-grid. Check out the examples on the docs website? If you have a more specific question, please show me what you've tried (with a Code Sandbox or similar) and I could maybe provide more helpful feedback.
