### ISSUE TITLE
Integration with react-select when there is no options left

### ISSUE THREAD

**Issue by sally4388you** [bvaughn/react-window#255]
Hi there!

I have a problem with integration with react-select. Really hope anyone can help me here!! Thanks in advance!!!

Example in
https://codesandbox.io/s/01k87orqzn

If you change the number of options to 0, there will be an error showing up in the console that says `NaN is an invalid value for the height css style property`.

This happens when you set `removeSelected` in Select to true. If there is no option left, how do I show noOptionsMessage and stop the errors?

**Comment by sally4388you** [comment]
Anyways. Guess I will use AutoSizer. Seems it works.

Didn't want to import another library tho...

**Comment by sally4388you** [comment]
And also the error could come from `initialScrollOffset`, `height` and `itemCount`

**Comment by bvaughn** [comment]
This library does not have any support for react-select. Sorry but you'll have to decide how to handle props coming from it  on your own.
