### ISSUE TITLE
FixedSizeGrid.scrollToItem sometimes scrolls the item only half into view

### ISSUE THREAD

**Issue by MarkFalconbridge** [bvaughn/react-window#257]
If the to scroll to is at the bottom of the grid and is already in view, calling scrollToItem actually scrolls the grid so that the item is only partially visible.

Here (https://codesandbox.io/s/bvaughnreactwindow-scrollingtoagriditem-d8cc4) is a sandbox to illustrate the issue. If you manually scroll the grid so that cell "r9, c5" is fully visible then click the "scroll to row 9 column 5" button you'll see that the grid scrolls so that you can only see half of the cell. (alternatively just keep clicking the button and you'll see the cell scroll into view and then scroll halfway out of view)

**Comment by bvaughn** [comment]
Works for me. What browser/OS?

**Comment by MarkFalconbridge** [comment]
I'm using Windows. It has that behavior on Chrome, Firefox and Edge. I'm guessing that it's because of the scrollbars which if you on a Mac won't be there?

**Comment by bvaughn** [comment]
Perhaps, although I usually try to test with scrollbars turned on in OSX as well. I'll look into it when I have time.

**Comment by bvaughn** [comment]
Fix published as 1.8.3 and verified just now
