### ISSUE TITLE
UMD builds for CDN

### ISSUE THREAD

**Issue by umphy** [bvaughn/react-window#258]
Are there any plans to create UMD builds for CDNs?

**Comment by bvaughn** [comment]
No, I have no plans to add a UMD build.

As mentioned on issue #232, if you'd be interested in contributing a PR then I can commit to reviewing and considering it, but that's it 😄

**Comment by umphy** [comment]
FYI, there is now a CDN providing both ESM and UMD builds of npm packages called Pika. For react-window it's here: [https://www.pika.dev/packages/react-window](https://www.pika.dev/packages/react-window)
