### ISSUE TITLE
react-window.now.sh blocked by Norton Safe Web agent

### ISSUE THREAD

**Issue by JESii** [bvaughn/react-window#259]
FYI... this just started happening... Norton Safe Web claims this is a "known dangerous web page" with the following display:
![image](https://user-images.githubusercontent.com/486/59204813-4c982b00-8b56-11e9-8011-2869c9f41115.png)

This is obviously related to now.sh ([here's the Norton report](https://safeweb.norton.com/report/show?url=https://react-window.now.sh/&ulang=en)) and other folks on the site...

**Comment by bvaughn** [comment]
Thanks for the heads up!

Going to close this issue since I can't do anything about it directly. I'll check to make sure Zeit is aware of it.

**Comment by bvaughn** [comment]
Zeit is in contact with Norton about this

**Comment by bvaughn** [comment]
Zeit says it is resolved now and they have monitoring setup to ensure it doesn't happen again.
