### ISSUE TITLE
IOS Safari elasticity

### ISSUE THREAD

**Issue by istarkov** [bvaughn/react-window#27]
May be it's well known issue, but for safari IOS all the controls with both scroll (horizontal and vertical) allowed in one div become a pain.
Scrolling because of scroll elasticity looks like
![kapture 2018-07-24 at 2 00 29](https://user-images.githubusercontent.com/5077042/43107456-c63224c0-8ee5-11e8-811a-a0da03d5c82f.gif)

It's reproduced on real devices, and all that jumps too. Unfortunately safari has no some kind of `directionalLockEnabled` feature, and does not support `overscroll-behavior` css prop. 

To avoid we splitted scrolls across 2 different divs (one with y scroll enabled and other with x), in that case scroll works in one general direction, and there is no such jumps.

The problem of such solution that it hides right scroll from a window (horizontal scroll is placed at the right of table which is wider than window)

Just a question haven't you think about this problem and possibly know the solution? 

Thank you for this lib, amazing!

**Comment by bvaughn** [comment]
@istarkov Can you reproduce the same jittery behavior with react-virtualized?

**Comment by istarkov** [comment]
Yep, I can reproduce it for any div with both scroll active 

![kapture 2018-07-24 at 18 14 32](https://user-images.githubusercontent.com/5077042/43148202-7bedf6d6-8f6d-11e8-9ad1-22bdd63e87c8.gif)

**Comment by bvaughn** [comment]
Gotcha. That's what I thought but thanks for confirming.

I've been aware of this issue for a long time with RV. No idea how to fix it. Seems to only happen if you overall past the start/end of the container.

**Comment by istarkov** [comment]
Ok thank you! Ill close this having that workaround is known and this is mostly safari issue having nothing with this library. I thought that may be there is other workaround known ;-) and here is the best place to ask (sorry ;-))

**Comment by bvaughn** [comment]
No problem. Totally worth asking about. I just have no idea how to fix it! 😁

**Comment by TrySound** [comment]
I would reopen it just to be visible to others. The solution above does not allow to use sticky columns since the closest scrollable parent does not have horizontal scroll. Maybe somebody will find a better solution.

**Comment by TrySound** [comment]
Here is the solution with separate horizontal scroll in parent wrapper.
```
<div style={{ overflowX: 'auto' }}>
  <div style={{overflowY: 'auto' }}>
    {/* doesn't work because the closest parent does not have horizontal scroll */}
    <div style={{ position: 'sticky', left: 0 }}></div>
  </div>
</div>
```

**Comment by bvaughn** [comment]
> The solution above does not allow to use sticky columns since the closest scrollable parent does not have horizontal scroll.

I still have no idea what solution you're referring to, or what this has to do with sticky.

**Comment by TrySound** [comment]
With common scroll position sticky works but we have inertia problem
```js
<div style={{overflow: 'auto' }}>
  {/* row */}
  <div style={{position: 'absolute', top: 100, left: 0 }}>
    {/* sticky column  */}
    <div style={{ position: 'sticky', left: 0 }}></div>
  </div>
</div>
```

I meant maybe somebody could propose a solution if we will open this issue.
