### ISSUE TITLE
Off-by-one error in onItemsRendered reports visibleStopIndex that's not visible

### ISSUE THREAD

**Issue by justingrant** [bvaughn/react-window#270]
My app uses react-window like a carousel: there's only one item visible at a time, and `size === itemSize`. I was surprised to see that `onItemsRendered` reports that `visibleStopIndex` is always one larger than `visibleStartIndex`, even though that's not what's actually being shown to the user. I traced the issue to this code:

https://github.com/bvaughn/react-window/blob/aa71ef99990eb3e559a0afafb3a09fa2f90eefc4/src/FixedSizeList.js#L77-L96

If `size` is an even multiple of `itemSize` (including my case where they're the same), and if the item is snapped to the edge (I use `scroll-snap-type` and `scroll-snap-align` to guarantee this), then the code above reports a `stopIndex` that's not actually a visible item.

I'm happy to PR a fix, but I wanted advice because this would technically be a breaking change for users who are relying on current behavior, e.g. they're subtracting one from the stop index, perhaps assuming that `visibleStopIndex` is intended to be that way, like the way C++ standard library collections always expect `end` to be one index more than the index of the last element in the collection.

In theory a less-breaking change could be to make *all* `onItemsRendered` calls return one more than the real stop index, even if items aren't snapped to the edge or if the `size` isn't an even multiple of `itemSize`.  At least then the behavior wouldn't change depending on the ratio of the item to container size.  I admittedly don't like this idea-- seems like a bad tradeoff to make the API permanently more confusing to avoid a major revision bump.

Got ideas for how this should be addressed?

**Comment by bvaughn** [comment]
If it's a bug, as you say, then a failing test (with a fix) as a PR would be a welcome next step. I will try to make time to review a PR in the near future.  I will likely otherwise not work on this.

**Comment by justingrant** [comment]
Cool, I'll do tests & a fix in a PR. Before I start, I have two quick questions about what the expected behavior was for this event:
* Should `visibleStopIndex` be the index of the last visible item, or the index of the first non-visible (overscanned) item immediately after the last visible item? I assumed the former, but after looking at the test snapshots (which use the latter behavior) I wasn't sure. 
* When there are partial items displayed before and/or after fully-visible items, should they be considered "visible"?  I assume yes.
* If `itemSize` is larger than `size` (if this is allowed) and the item extends past both ends of the visible list, should `visibleStartIndex === visualStopIndex`?  I assume yes.

**Comment by bvaughn** [comment]
Indexes should be inclusive. So `visibleStartIndex` and `visibleStopIndex` should be the first and last partially visible items.

Yes. Yes.

**Comment by justingrant** [comment]
Cool. BTW, I'm also assuming that `overscan[Start|Stop]Index` should be inclusive too.

**Comment by bvaughn** [comment]
Yup, all indices should be inclusive.

**Comment by justingrant** [comment]
BTW, as I'm editing snapshots I noticed that the [docs](https://react-window.now.sh/#/api/FixedSizeList#props) say that the default `overscanCount` is 1, but the source has the default being 2.  Which is correct?
![image](https://user-images.githubusercontent.com/277214/59939495-fc01b700-940c-11e9-903f-76102c02968a.png)

https://github.com/bvaughn/react-window/blob/aa71ef99990eb3e559a0afafb3a09fa2f90eefc4/src/createListComponent.js#L164-L170

**Comment by justingrant** [comment]
Sorry for all the questions!  Here's another two I came up with while adding tests for partially-visible items:

1. When `size` isn't an even multiple of `itemSize`, how should `scrollToItem` behave with option `auto` when you're scrolling **forward** and the desired index isn't already visible?
    * A: Align first visible item with the start of the list container and hang a partial item off the visible end of the list.  `visibleStopIndex === index+1`. Exception: if the last item (`itemCount-1`) is visible, then show the partial item at the start of the list because there's no partial item available to show after it.
   * B: Align last visible item with end of list, leaving a partial item visible at the start of the list. `visibleStopIndex === index`. In theory this is the "scroll as little as possible" option, but IMHO it may look weird to have partials at the start of the list unless you're scrolling to the end of the list items.

2. When `size` isn't an even multiple of `itemSize`, how should `scrollToItem` behave with option `smart` and the current position is more than one viewport away?
    * A: Align first visible item with start of list container (same as 1A)
    * B: Align last visible item with end of list (same as 1B)
    * C: Center the item in the list, leaving partial items visible on both ends of the list, unless it's at the beginning or end of the list in which case align to the edge where there's no partials available.
    * D: Scroll as little as possible. Put the partial on the edge in the direction that you're scrolling.
    * E: If only one item is visible (e.g. carousel), then center it with partial items on both ends, aka C. If there are multiple items visible, then left-align the items with the container, aka A.

My assumption is that 1A is correct, and either 2A or 2E seem best.  But I don't have a strong preference either way.  Holler if you have an opinion.

**Comment by justingrant** [comment]
Update: in the PR I'm about to file, I used 1A above (because it looks best) and 2C (because I realized that this is the current behavior for all item sizes-- including even multiples-- so having a different behavior for uneven-multiple item sizes didn't make sense).

For the `FixedSizeList` `overscanCount` default, I updated the docs to match the implementation.

Filing a PR now.

**Comment by bvaughn** [comment]
Fixes published in 1.8.4
