### ISSUE TITLE
Item size not computed

### ISSUE THREAD

**Issue by userbq201** [bvaughn/react-window#273]
How to change itemSize in VariableSizeList ? I want to change elements size (Add custom header to list and etc)

**Comment by bvaughn** [comment]
What have you tried?

Did you check out [the `VariableSizeList` docs](https://react-window.now.sh/#/api/VariableSizeList)? Specifically look at the `resetAfterIndex` method:

> **`resetAfterIndex(index: number, shouldForceUpdate: boolean = true): void`**
> VariableSizeList caches offsets and measurements for each index for performance purposes. This method clears that cached data for all items after (and including) the specified index. It should be called whenever a item's size changes. (Note that this is not a typical occurrance.)
>
> By default the list will automatically re-render after the index is reset. If you would like to delay this re-render until e.g. a state update has completed in the parent component, specify a value offalsefor the second, optional parameter.

If you show me a Code Sandbox with what you've tried, I'm happy to take a look and point out what you may have overlooked. 😄

**Comment by Zertz** [comment]
Hi Brian, I ran into the same issue and noticed this question has been asked a lot. Would you accept a PR to add an example?
