### ISSUE TITLE
How to add padding to row wrapper ?

### ISSUE THREAD

**Issue by userbq201** [bvaughn/react-window#276]
[Can you add position relative for inner div ?](https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L363)
I cant use padding for list

**Comment by userbq201** [comment]
@bvaughn

**Comment by TrySound** [comment]
You may pass custom component to `innerElementType` with any customisations you need.

**Comment by userbq201** [comment]
@TrySound How do it ? Can you make example ?

**Comment by userbq201** [comment]
I did it. Thanks

**Comment by ratnabh-classic** [comment]
@dmitryshelomanov can you tell how ?
