### ISSUE TITLE
[DynamicSizeList] Rending items on top of each other if height is the same as estimatedItemSize

### ISSUE THREAD

**Issue by brunolemos** [bvaughn/react-window#278]
Found a bug on https://github.com/bvaughn/react-window/pull/102, if my items are exactly height `50` (the `estimatedItemSize` value) they will all render on top of each other:

![image](https://user-images.githubusercontent.com/619186/60388786-9193eb00-9a8c-11e9-9db1-f924cae93722.png)

If they have any different height (e.g. `49` or `51`) it works:

![image](https://user-images.githubusercontent.com/619186/60388783-85a82900-9a8c-11e9-8a8d-17ab8c4b9ca7.png)

**Comment by bvaughn** [comment]
Ah, interesting edge case. This only holds true if _every_ item is the exact same size as the estimated size. In this case, the list assumes there are no updates to be made. It's not handling the case where content has been rendered for the first time though.

**Comment by bvaughn** [comment]
Fixed in 13d48ad.

**Comment by anton6** [comment]
@bvaughn is this fix part of 1.6.0-alpha.1?
