### ISSUE TITLE
VariableSizeGrid expand last column

### ISSUE THREAD

**Issue by zebbedi** [bvaughn/react-window#279]
Hi, 

I'm using a VariableSizeGrid. When the width of the entire grid is smaller than the viewport of all the columns everything renders as I'd like. 

When the width of the entire grid is larger than the widths of all of the columns I'd like the last column to consume all the remaining space. It currently doesn't look very good in our app when this happens. 

I've been experimenting with onItemsRendered and a window resize listener but it doesn't seem a terribly nice or efficient way of doing it. 

Do you have any suggestions on the best way to do this?

**Comment by bvaughn** [comment]
Off the top of my head, my only suggestion would be to share width and columnCount with your item rendered using itemData, then the renderer would have to be smart enough to know if it's the last one (columnIndex === columnCount - 1) and resize itself.

This isn't something the library supports directly though. It would require you to add some logic to your renderer. 😁 Good luck!

Sounds vaguely related to #121.
