### ISSUE TITLE
Question: How to calculate itemSize for a VariableSizeList?

### ISSUE THREAD

**Issue by rmisio** [bvaughn/react-window#282]
Forgive me if it's bad form to ask this on GH, but the react-virtualized slack didn't seem so active nor did there seem to be much react-window action on StackOverflow.

Anyhow, I would like to virtualize a potentially long list of chat messages. The thing is the height of the elements could differ dramatically based on the content and also based on the container width which varies depending on what responsive break point you're on.

I know it was mentioned in another issue that the item is not rendered at that point, so you can't really go to the DOM to get the actual height. Given that... how would one go about coming up with the height calculation to return from `itemSize`?

(FWIW, I'm not opposed to using react-virtualized if it offered a solution to this)

**Comment by bvaughn** [comment]
What you're describing is not really supported yet. See #6.

**Comment by efdotjay** [comment]
@bvaughn Is this supported yet?
