### ISSUE TITLE
[Question] Passing custom props to an item renderer via List

### ISSUE THREAD

**Issue by jancama2** [bvaughn/react-window#285]
Is there any way how to pass custom props to an item renderer from the List? The props are not data like, they are modifications of the item renderer. I would like to avoid some conditional creation of the item renderer.

**Comment by bvaughn** [comment]
The itemData prop.

I don't know what you mean by "they are not data like". Almost anything can be considered "data", no?

**Comment by jancama2** [comment]
I would like to reuse the list component across multiple pages, with different item renderers, but the difference of the item renderers is only in details. Let's say on one page the renderer displays a topic of an article in the list and on the other page it doesn't. So, I was hoping for an ability to set some prop on the list and pass it to the renderer.

Something like:
```
const ItemRenderer = ({ index, data, customProps }) => <Article {...data[index]} {...customProps} />
...
const List = ({ data, displayTopic }) => <FixedSizeList rendererCustomProps={{ displayTopic }} data={data}>{ItemRender}</FixedSizeList>;
....
<List data{data} displayTopic />
```

**Comment by bvaughn** [comment]
`itemData` _is_ the way of passing "customProps"

**Comment by jancama2** [comment]
Oh, now I get it, I was so used to use itemData as the data source that I've mistaken it with "listData" :)

**Comment by bvaughn** [comment]
Ah, I see. Maybe the name is less clear than it could be. :smile: You can wrap anything you want up in it, as [this docs example shows](https://react-window.now.sh/#/examples/list/memoized-list-items).
