### ISSUE TITLE
scroll-linked positioning effect in Firefox

### ISSUE THREAD

**Issue by jazkh** [bvaughn/react-window#287]
Firefox 67.0.4 (64-bit)
Windows 10

I am using FixedSizeGrid and I see this warning in firefox.

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

What should I do to remove this warning? should I ignore it for now?

**Comment by bvaughn** [comment]
Yes, you can safely ignore it.
