### ISSUE TITLE
Weird scrollbar behaviour when List has `display: flex`

### ISSUE THREAD

**Issue by silverwind** [bvaughn/react-window#288]
See https://codesandbox.io/s/bvaughnreact-window-fixed-size-list-vertical-53j2l

All I changed here was add `style={{ display: "flex", flexDirection: "column" }}` to `List` and if you start scrolling up or down the scrollbar's height seems to behave rather weirdly, it grows and shrinks based on scroll offset.

Scrolling itself appears to work normally, so it's probably something about the calculation of the scrollable area.

**Comment by bvaughn** [comment]
You shouldn't set the `display` style of list to anything other than the default (block). It doesn't make sense to do this, given the way list (and grid) work (e.g. absolute positioning of children). Items aren't even added as children of list directly, but rather they are added to an inner div, so this wouldn't have any actual impact on the layout of children anyway. :smile:

**Comment by silverwind** [comment]
Yeah, it's useless with absolutely positioned children. I just happened to integrate `react-window` into a existing application that happened to set `display: flex` on the container. Took me like 2 hours to figure out what was wrong. 😢
