### ISSUE TITLE
[DynamicSizeList] Wrong positions after adding/removing items from the list

### ISSUE THREAD

**Issue by brunolemos** [bvaughn/react-window#289]
I’m experimenting with the branch #102.

Almost everything works well. 

I’m facing a problem when the list items change:

1. Render list with initial items (ok)
2. Remove the second item 
3. See some items get positioned wrong

See the blank space between items after filtering out the item that contains the word “progress”:

![Kapture 2019-07-11 at 21 59 27](https://user-images.githubusercontent.com/619186/61094873-6c599200-a427-11e9-9bb2-4e88e374341c.gif)

After I scroll past this blank space and go back, it get’s fixed.

I also noticed the items get wrong positions if new items are added to the list.

See wrong spacing after first item and cut off bottom buttons of the second item:

![image](https://user-images.githubusercontent.com/619186/61096443-f0167d00-a42d-11e9-9dbf-99554786195a.png)

_I don’t have a small reproducible demo, but the gif above is from [this branch](https://github.com/devhubapp/devhub/pull/152)_

I check and confirmed the props being passed to `DynamicSizeList` are being updated correctly (`itemCount` changes and `this.getItemKey(2)` get the the new id), so I believe it’s some react-window internal, probably related to the cache.

**Comment by brunolemos** [comment]
https://github.com/bvaughn/react-window/issues/6

**Comment by nihgwu** [comment]
did you call `resetAfterIndex` after removed item?

**Comment by graphee-gabriel** [comment]
@nihgwu `resetAfterIndex` does not exist for `DynamicSizeList`
https://react-window-next.now.sh/#/api/DynamicSizeList

**Comment by tootiny** [comment]
@brunolemos by any chance are your list items class components that override shouldComponentUpdate?

**Comment by brunolemos** [comment]
> are your list items class components that override shouldComponentUpdate?

nope

**Comment by ealexseen** [comment]
@brunolemos 
I think need install polyfill ResizeObserver

**Comment by brunolemos** [comment]
I use the polyfill already

**Comment by bustEXZ** [comment]
Hi there. Same problem, can i drop cache of items? Maybe add `resetAfterIndex` to DynamicSizeList?
Thanks
ps. i'm using ResizeObserver polyfill too

**Comment by ttamminen** [comment]
Just wanted to inform that I have the same issue. 

In my case, the dimensions of a list item change due to the filtering. I think the `itemSize` calculation should re-triggered somehow.

**Comment by divate** [comment]
Good afternoon. I used DinamycSizeList in your demo project. Everything was fine, but after a while I noticed that the list component began to work incorrectly. At first I thought it was some library on which react-window depends. But looking at your demo 
[https://react-window-next.now.sh/#/examples/list/dynamic-size](url)
noticed about the same result, although in the past it also worked perfectly. Could you suggest the cause of these bugs?

**Comment by hidai** [comment]
How about adding `key={Math.random()}` to your `DynamicSizeList`? It forces to initialize the component at every rendering.

**Comment by Alino** [comment]
> How about adding `key={Math.random()}` to your `DynamicSizeList`? It forces to initialize the component at every rendering.

This actually works but with one flaw. If you are adding items to the list and you are scrolled down (not on top of the list) then each addition/change to the list will rerender the List and reset the position to top. So unusable for my use case where I am sequentially fetching data from an API while the user should be able to scroll in the list and use filters for the list.

**Comment by zachbryant** [comment]
Any news on this getting fixed? Having this rerender doable but less than ideal
