### ISSUE TITLE
what's difference with react-virtualized?

### ISSUE THREAD

**Issue by jsu93** [bvaughn/react-window#29]
We already have react-virtualized, So I want know why build another library again;
I believe many people want know the reason.. thank you @bvaughn

**Comment by TrySound** [comment]
https://twitter.com/brian_d_vaughn/status/1021084411561881601

**Comment by carlosagsmendes** [comment]
I'm still trying to figure it out but here are some of the goals shared by Brian on Twitter:
 
- Faster
- Smaller, since it has fewer non-essential components
- Easier to use, with a more intuitive API
- More easily maintainable

**Comment by jsu93** [comment]
@TrySound  @carlosagsmendes thank you!

**Comment by rdsedmundo** [comment]
I really think this information should be present in the README. I had the exact same question once I opened this repository as I knew `react-virtualized` already. Googling didn't help me pointing to this issue, so I was a bit confused until I tried to search in the Issue Tracking. Without this being present in the README, I still expect more duplicated questions being created as the time goes.
