### ISSUE TITLE
[Documentation request] List features not in react-window

### ISSUE THREAD

**Issue by Secretmapper** [bvaughn/react-window#296]
Hello! Great library! I also really like the insight with the difference between react-window/virtualized.

However, it doesn't really list the features that are not in react-window, which leads me to a pretty hard decision of not knowing if react-window will be enough for my use cases.

I think if it listed out a couple of features not present in react-window (but present in virtualized) it would be really helpful in making a decision.

**Comment by bvaughn** [comment]
I appreciate the feedback!

If I find time and feel like doing some more docs writing, I may take a pass at it. Going to close this issue though because I don't see it as something that _must_ get done, just a nice to have.
