### ISSUE TITLE
List not rendering after scrollTo

### ISSUE THREAD

**Issue by acobol** [bvaughn/react-window#298]
I have maybe a too specific use case. I'll try to explain, i have a list that its constantly updated, initially it have autoscroll enabled, so after the render i scrollToItem to last item, if user scroll up it disable autoscroll, but table it's still updated, so after the number of items change i scrollTo to scrollTop value that i store after user scroll. If i do that, table its not re rendered because FixedSizeList checks if scrollOffset its the same as previous before update state.
By now im extending the class and overriding scrollTo, is there any other way to do that or can we have some option to allow re render even with same scrollOffset?.

**Comment by bvaughn** [comment]
This probably needs a repro case for me to understand what you're trying and what you're asking. Share a Code Sandbox or something that I can see and run and I'll take a look :smile: (and re-open the issue)
