### ISSUE TITLE
List flickers only when scrolling with laptops mouse pad

### ISSUE THREAD

**Issue by YoavHortman** [bvaughn/react-window#300]
List flickers when scrolling on laptop with the mouse pad, easy to see [here](https://react-window.now.sh/#/examples/list/fixed-size), just scroll on the top list with a mouse pad, any way to fix that?

**Comment by bvaughn** [comment]
Sorry for the canned answer, but I've talked about this a lot in the past and I don't have the energy to write a long response again. :smile: Hope you'll understand.

Check out this slide for an overview of how libraries like this generally work:
https://bvaughn.github.io/forward-js-2017/#/12/5

Check out these slides for why it "flickers":
https://bvaughn.github.io/forward-js-2017/#/23/2
https://bvaughn.github.io/forward-js-2017/#/23/6

**Comment by AbeHandler** [comment]
Thanks for the link to the presentation. @YoavHortman and future people with this issue: did you forget to include `style={style|`?
