### ISSUE TITLE
Better Documentation ？

### ISSUE THREAD

**Issue by GeorgeZhangZHY** [bvaughn/react-window#303]
It seems that many props hasn't been documented. For example, which props should I use if I want to call certain callback when a new item enters(leaves) from bottom(top).

**Comment by bvaughn** [comment]
> For example, which props should I use if I want to call certain callback when a new item enters(leaves) from bottom(top).

There is no such prop.

To my knowledge, the props are all documented on the docs site:
https://react-window.now.sh/#/api/FixedSizeList

If you find a specific one missing, shoot me a PR or an issue. 😄
