### ISSUE TITLE
Sticky demo doesn’t work

### ISSUE THREAD

**Issue by ThaddeusJiang** [bvaughn/react-window#304]
I am seeing the demo https://codesandbox.io/s/0mk3qwpl4l in readme, but if I change `stickyIndices` from [0,1] to [10. 11], the demo won’t work.

**Comment by bvaughn** [comment]
In this demo the sticky columns are only meant to be the first few (aka top/left aligned). Not really sure what you would expect from a value of [10,11] but that's now how the demo is setup.
