### ISSUE TITLE
Wrong behaviour on scroll item to center

### ISSUE THREAD

**Issue by Flyover-ArtSk** [bvaughn/react-window#306]
Wrong behaviour on scroll item to center

Example:
https://codesandbox.io/embed/bvaughnreact-window-scrolling-to-a-list-item-q4jli

Click on "Scroll to row 2" or "Scroll to row 3" - items not in center.
Click on "Scroll to row 5" - item in center

**Comment by sharcastic** [comment]
Hi @bvaughn I faced this issue too and I want to raise a PR to fix this. Is that ok?

**Comment by bvaughn** [comment]
Sure

**Comment by sharcastic** [comment]
@bvaughn Let me know if the PR requires some more changes! Cheers!

**Comment by ramneekhanda** [comment]
@sharcastic @bvaughn where are we on merging this?

**Comment by kramarmm** [comment]
@bvaughn any updates?

**Comment by christowiz** [comment]
I'm seeing the same issue.  Any update on this getting merged?

**Comment by cathykc** [comment]
Thanks for the PR @sharcastic - would love this fix to merged in :) Are there any updates that need to be made before approval @bvaughn. Happy to take over if needed.
