### ISSUE TITLE
When is version 2 releasing ? I want to use dynamic size list

### ISSUE THREAD

**Issue by ShivamJoker** [bvaughn/react-window#311]
hey i want to use dynamic size list where can i download version 2 or i will have to use react virtualise ?
![image](https://user-images.githubusercontent.com/23727670/63217001-082f9980-c15c-11e9-9c64-c72e8ba39d84.png)

this is how my list is looking with variable size list

**Comment by bvaughn** [comment]
This is a project I work on in my spare time, as I have time. I don't have a release date.
