### ISSUE TITLE
scrolling up automatically after scrolling down manually

### ISSUE THREAD

**Issue by Julian-Chu** [bvaughn/react-window#313]
![apply-react-window](https://user-images.githubusercontent.com/7224544/63850546-98f44980-c994-11e9-8f67-e869a30588d7.gif)

Thanks for amazing library.

We are trying to apply react-window to our project, but there is a weird issue. When we scroll down(forward) list, the list itself scrolls back a little automatically(please see git).  

We use redux and redux-saga to manage state and data,  data is pushed from backend server per second, and use FixedSizeList to render the data. 

I am sorry I can't provide source code here. After some testing and debug, I can't find where this problem comes from , now I have no idea how to debug.  Does someone have experience? any suggestions are welcome. Thanks.

**Comment by emersonsiega** [comment]
@bvaughn I'm having this same issue. I'm sure that I'm not calling scrollTo 

```jsx
<AutoSizer>
        {({ height, width }) => (
          <FixedSizeList
            height={height}
            width={width}
            itemSize={displayedItems}
            itemCount={totalItems}
          >
            {({ index, style }) => (
              <ListRow
                item={items[index]}
                displayData={displayData}
                style={style}
                onItemClicked={onItemClicked}
              />
            )}
          </FixedSizeList>
        )}
</AutoSizer>
```

```jsx
import { ListItem, ListItemText } from '@material-ui/core'

const ListRow = ({ item, onItemClicked, displayData: { titleName, subtitleName } }) => {
  return (
    <ListItem key={item.id} button divider onClick={() => onItemClicked(item)}>
      <ListItemText primary={item[titleName]} secondary={item[subtitleName]} />
    </ListItem>
  )
}
```

**Comment by emersonsiega** [comment]
Now I see what's wrong... I'm passing an incorrect `itemSize`. Changing it to the right value, works fine!

**Comment by bvaughn** [comment]
That example looks broken. You don't seem to be using the style prop.

**Comment by emersonsiega** [comment]
Yep, you're right. This was wrong too! Thanks!

**Comment by bvaughn** [comment]
Without having a way to view a repro of this, I'm going to assume it's something similar causing the problem that @Julian-Chu reported. (Check to make sure you _are_ using the `style` param and that you _aren't_ accidentally calling `scrollTo`.)

**Comment by Julian-Chu** [comment]
Hi @bvaughn  and @emersonsiega ,
Thanks a lot for your feedback.
Finally, my colleagues found how to it.  

Here are what we did:
1.  remove another animation library may call scrollTo
2.  change ul + li to div only
