### ISSUE TITLE
Can I add margin to the top and bottom of a list? 

### ISSUE THREAD

**Issue by krishna724** [bvaughn/react-window#315]
Actually I am using react 15 so in that version there is no forwardRefs. Can you please provide any alternative solution.

**Comment by bvaughn** [comment]
> Can I add margin to the top and bottom of a list?

The FAQs show an example of how to do this.

> Actually I am using react 15 so in that version there is no forwardRefs. Can you please provide any alternative solution.

No, sorry. Don't know of a way off the top of my head.

**Comment by krishna724** [comment]
@bvaughn  Thanks. If I will find a way I will raise the PR.

**Comment by etiennejcharles** [comment]
To anyone coming across this 
```
 <div
      style={{
        ...style,
        top: style.top + GUTTER_SIZE,
        height: style.height - GUTTER_SIZE,
      }}
    >
 ```
 Based on: https://github.com/bvaughn/react-window#can-i-add-gutter-or-padding-between-items
