### ISSUE TITLE
Support applying paddings for safe area support

### ISSUE THREAD

**Issue by brunolemos** [bvaughn/react-window#316]
When adding proper support for the iPhone X safe area in the browser I noticed there wasn't any way to add the paddings to beginning/end of the list in `react-window`.

To enable the safe area add `viewport-fit=cover` to the viewport meta tag:
```diff
-<meta name="viewport" content="width=device-width, initial-scale=1">
+<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
```

The solution could be something equivalent to `FlatList`'s `contentContainerStyle`, but it needs to take the paddings into account when calculating the items positions.

**Comment by bvaughn** [comment]
>  I noticed there wasn't any way to add the paddings to beginning/end of the list in react-window.

Check out the FAQs: [**Can I add padding to the top and bottom of a list?**](https://github.com/bvaughn/react-window#can-i-add-padding-to-the-top-and-bottom-of-a-list)

**Comment by brunolemos** [comment]
hum... I need to pass the padding values as props, since I get the safe area insets runtime and they can change (landscape/portrait, etc). 

Will I need to use `itemData` for that?

**Comment by bvaughn** [comment]
Context probably.

**Comment by brunolemos** [comment]
Context worked!

Almost perfect, now I just need to use `scrollTo` instead of `scrollToItem` to take these paddings into consideration.

Thanks.

**Comment by bvaughn** [comment]
No problem!
