### ISSUE TITLE
Custom `getScrollbarSize`

### ISSUE THREAD

**Issue by MikeYermolayev** [bvaughn/react-window#319]
Hello,

Currently I'm trying to migrate from react-virtualized to react-window. Everything's fine except one thing:

We use custom CSS styles for the scrollbar of table, e.g.:
```
---css---

.table {
    &::-webkit-scrollbar {
        width: 8px;
        height: 8px;
    }
}

---js---

<Grid
    className="table"
    ...
/>
```

The problem is that `getScrollbarSize` from react-window doesn't use any knowledge about Grid's styles and by default scrollbar size on chrome will return 0 instead of 8.

With react-virtualized we were able to pass `getScrollbarSize` which takes in to account the classname too.

I guess that it's not desired to extend API but maybe we can pass Grid's styles to scrollbar measurer node?

Thanks in advance

**Comment by bvaughn** [comment]
Initial reaction is that I don't want to add any complexity to support this use case because I think it's _extremely_ uncommon. I could allow list/grid to accept a `scrollbarSize` or a `getScrollbarSize` fn prop like react-virtualized did, but an "everything is customizable" approach like react-virtualized is kind of difficult to maintain.

**Comment by MikeYermolayev** [comment]
Thanks for the reply.

I fully understand your motivation about extending API and looks like I kinda found a workaround for my use case.
But still, what do you think about passing Grid's className to the scrollbarSize? Then it will measure scrollbar size taking into account the styling of the grid

**Comment by bvaughn** [comment]
Hm. Put together a PR for me that does that and let's see?

**Comment by MikeYermolayev** [comment]
Uh, sorry, analyzed source code of react-window again and found out that scrollbar size is only used in `scrollToItem` which is not my issue for now. My use-case was related to width calculation depending on scrollbar size but I already workarounded it and just set `width - scrollbarSize()` as Grid's width.

I can still prepare a PR since it can be an issue for someone who is using custom scrolls with `scrollToItem` but a little bit later. (At a weekend maybe)

I think issue can be closed
