### ISSUE TITLE
Scroll instability

### ISSUE THREAD

**Issue by twall** [bvaughn/react-window#326]
I'm using a VariableSizeList, where I pull the height of each rendered item as it's rendered (via ResizeDetector), storing the value for later use in the itemSize callback, and calling List.resetAfterIndex if the size has changed.  The initial size is set to something smaller than the row is likely to be.

When I subsequently scroll, as soon as the second item not initially visible enters the visible space, the scrollbar starts toggling between two states (independent of overscan setting).  The list elements may or may not flash depending on how far down the list I've scrolled.  The gap between the scrollbar toggle gets increasingly wider the farther I scroll down.  There seems to be a lot of extra empty space at the bottom of the list.

I've tried to track this down, but I can't determine what is causing the scroll event at the beginning of each toggle.  All of the offset calculations seem to be correct based on the scroll event offset, yet after the final `onScroll` client callback is invoked, another native scroll event is triggered with a new scrollTop value.

The height of the List and its inner div do not change, nor do the heights of the list elements.  The only setState call I can see is an update to the scrolling properties (including scrollOffset).

![capture](https://user-images.githubusercontent.com/756909/64458722-15d5a080-d0c4-11e9-8e5c-d28bc50c7e08.gif)

**Comment by bvaughn** [comment]
An issue like this really needs a repro case (e.g. Code Sandbox).

**Comment by twall** [comment]
Working on it, never done one of those before

**Comment by twall** [comment]
There was a `<div>` around the primary list item which should have been receiving the `style` property instead of the inner item (`<div><div style={style}>item</div></div>`).

**Comment by bvaughn** [comment]
Gotcha. That's why a repro is so helpful 😁 thanks for the update.
