### ISSUE TITLE
Can I change the number of rendered lists or dynamically automatically generate the height of each element

### ISSUE THREAD

**Issue by JinJieTan** [bvaughn/react-window#329]
Sorry, my English is not very good

But my project is similar to telegram

We really need your technical support

When I apply it full screen,
![image](https://user-images.githubusercontent.com/47209029/64677668-97ee0c80-d4aa-11e9-923d-5c80be3042a6.png)

I want to render the same number of items as before to fill the entire list, instead of leaving empty space, and can I have the height of the item automatically render? Because I use virtual lists elsewhere

![image](https://user-images.githubusercontent.com/47209029/64678083-780b1880-d4ab-11e9-946e-ee1f5a77b6d6.png)

**Comment by bvaughn** [comment]
Automatic item height is not yet supported (see  issue #6).

**Comment by JinJieTan** [comment]
But how do I change the number of renderings in full screen?

**Comment by bvaughn** [comment]
Sorry. Not sure what you're asking.

**Comment by JinJieTan** [comment]
正常情况下，列表渲染的是10个

Now normally, the list is rendered with 10

![image](https://user-images.githubusercontent.com/47209029/64705014-c935ff00-d4e1-11e9-9208-48ca923ffd00.png)

现在全屏后，列表渲染的还是10个，但是我想添加一个，变成11个充满整个列表，该如何操作？

Now, after the full screen, the list is still 10, but I want to add one to make it 11. How do I do that?

![image](https://user-images.githubusercontent.com/47209029/64705098-f5ea1680-d4e1-11e9-855f-10bcddda45d1.png)

他们的高度都是动态计算的，但是渲染的个数不是动态的

Their heights are calculated dynamically, but the number of renderings is not

![image](https://user-images.githubusercontent.com/47209029/64705247-3e093900-d4e2-11e9-90fb-bb24833b28bf.png)

**Comment by JinJieTan** [comment]
Sorry to bother you, but I need to solve this problem, because my project all USES this library for refactoring

**Comment by bvaughn** [comment]
In your screenshot, you can see that the list's height is 536px for all three screenshots. List only renders to fill its height. If you want it to be taller, to fill the page, you need to increase its height when the page resizes.

I suggest checking out this FAQ entry:
https://github.com/bvaughn/react-window#can-a-list-or-a-grid-fill-100-the-width-or-height-of-a-page

**Comment by JinJieTan** [comment]
The height of 536 has been replaced ， They are all dynamic in height, but still render 10 elements

高度都是用计算的方式去展现，但是渲染出来的个数就是10
![image](https://user-images.githubusercontent.com/47209029/64707663-ea98ea00-d4e5-11e9-89f9-f27c1813a1f3.png)

**Comment by bvaughn** [comment]
Read the FAQ I linked, please. Look at the code. This has nothing to do with CSS. `height` is passed in to list as a prop.

**Comment by JinJieTan** [comment]
Thank you. I'll try it right away.
