### ISSUE TITLE
[DynamicSizeList] Incorrect List Dimension When Size of Item Data is Reduced

### ISSUE THREAD

**Issue by jnishiyama** [bvaughn/react-window#333]
I'm using branch `issues/6`, and I am experiencing a problem similar to #289 but not quite the same. Here's my best attempt at explaining the issue (codesandbox: https://codesandbox.io/s/bugreact-window-dynamic-size-list-djegq)

Let's say you have `n` items in your `itemData` and you scroll past `l` items. If `itemData` is reduced to `m` items where `m < l` then the height/width of the list will be incorrect.

I am not very well-versed with the code in `react-window`, but from what I can tell, the issue stems from this calculation in `DynamicSizeList.js`:

```
const getEstimatedTotalSize = (
  { itemCount }: Props<any>,
  {
    itemSizeMap,
    estimatedItemSize,
    lastMeasuredIndex,
    totalMeasuredSize,
  }: InstanceProps
) =>
  totalMeasuredSize + (itemCount - lastMeasuredIndex - 1) * estimatedItemSize;
```

When `getEstimatedTotalSize` is called after scrolling and reducing `itemCount`, `(itemCount - lastMeasuredIndex - 1) * estimatedItemSize;` will likely be negative.

When `getEstimatedTotalSize` is negative, the height/width set on the innerElement will remain as the last `estimatedTotalSize` value because you can't set a negative height. From createListComponent.js: `height: isHorizontal ? '100%' : estimatedTotalSize`. 

To fix this, I would propose just returning `itemCount * estimatedItemSize` when `totalMeasuredSize + (itemCount - lastMeasuredIndex - 1) * estimatedItemSize` is negative.

I will make a PR with this code change.

**Comment by Freak613** [comment]
While the issue got stuck, here is ridiculous hack to update height directly:
```javascript
const maxHeight = 300;
const itemHeight = 30;

<List height={Math.min(maxHeight, itemHeight * items.length)}  ...>
```

**Comment by OmkoBass** [comment]
> While the issue got stuck, here is ridiculous hack to update height directly:
> 
> ```js
> const maxHeight = 300;
> const itemHeight = 30;
> 
> <List height={Math.min(maxHeight, itemHeight * items.length)}  ...>
> ```

Didn't fix my issue. Anyone got an idea? As soon as i resize the list it just cuts itself in half.

**Comment by OmkoBass** [comment]
Actually fixed my issue. `Math.min(maxHeight, itemHeight * items.length)` GOES TO itemSize not to height.
