### ISSUE TITLE
strange flickering (style.top jumping between two values)

### ISSUE THREAD

**Issue by tomaszrondio** [bvaughn/react-window#335]
Any ideas how to debug that kind of behaviour?
![captured](https://user-images.githubusercontent.com/4939724/64955882-a01ec100-d889-11e9-8e38-bcfc02516eac.gif)

**Comment by bvaughn** [comment]
Not without a repro, sorry.

I'm going to close this issue since it's just a video and no repro code. Hope you understand.

**Comment by jkbailey** [comment]
I am experiencing this as well, no repro code though :( @bvaughn

**Comment by gupta-ji6** [comment]
Experiencing the same flicker when we reach the last item, will try to provide a cosesandbox link in some time.

**Comment by bogdanoff2049** [comment]
Im also experiencing this issue, how did you guys fix this?
