### ISSUE TITLE
The itemSize of one item is too large, resulting in caton. How can I solve it?

### ISSUE THREAD

**Issue by JinJieTan** [bvaughn/react-window#339]
![image](https://user-images.githubusercontent.com/47209029/65419406-2494b500-de31-11e9-91d5-2dff5fcb380b.png)

我使用的是 ` DynamicSizeList ` ，但是每个item高度内容数量不一致，例如这种情况，我进来后渲染的内容就非常多，导致卡顿

I used 'DynamicSizeList', but the amount of height content of each item is not consistent. For example, in this case, I would render too much content after coming in, resulting in a lag
```
 <AutoSizer>
                    {({ width, height }) => (
                      <List
                        className="list"
                        height={height}
                        itemCount={Object.keys(group).length}
                        ref={this.ref}
                        width={width}
                        itemData={{ group, list, keys: Object.keys(group) }}
                      >
                        {Row}
                      </List>
                    )}
                  </AutoSizer>
```

Dear author, can you tell me how to optimize?

**Comment by bvaughn** [comment]
As I mentioned on another issue you filed (#320) partial code snippets aren't sufficient when asking a question. You need to provide **full code example** of what you're doing. Since this issue is just another partial, I'm going to close it.
