### ISSUE TITLE
[Question] VariableSizeList - Scroll to top of element by code

### ISSUE THREAD

**Issue by iazO** [bvaughn/react-window#341]
We are using the VariableSizeList to show a filtered list of data. In some cases the following might happen:
  - User opens page;
  - Data is retrieved and shown in the list
  - User scrolls, extra data is fetched and rendered.
  - User applies new filter, resultset is different
  - => This is where the problem lies, the position of what is shown is no longer in sync with the newly fetched data.

Potential solution would be to automatically scroll to the top of the VariableSizeList element upon certain trigger points, e.g. applying a new filter resulting in new data.
However, I'm currently unable to find a proper way to achieve this behavior.

Thanks in advance!

**Comment by bvaughn** [comment]
`VariableSizeList` doesn't know anything about your filters or application logic. It only knows about the total number of items you want it to display. If things change in a way that might invalidate the previous data- you need to explicitly tell it.

(For example, if you were to reverse the list- none of `VariableSizeList` props would even change, but you would expect that list's contents to be changed.)

The way to do this is using the `resetAfterIndex ` method mentioned [on the docs page](https://react-window.now.sh/#/api/VariableSizeList):

> **`resetAfterIndex(index: number, shouldForceUpdate: boolean = true): void`**
>`VariableSizeList` caches offsets and measurements for each index for performance purposes. This method clears that cached data for all items after (and including) the specified index. It should be called whenever a item's size changes. (Note that this is not a typical occurrence.)
>
> By default the list will automatically re-render after the index is reset. If you would like to delay this re-render until e.g. a state update has completed in the parent component, specify a value of `false` for the second, optional parameter.

Hope this helps!
