### ISSUE TITLE
Size limitations

### ISSUE THREAD

**Issue by scott-fleischman** [bvaughn/react-window#345]
Are there inherent size limitations with the fixed-size components? I am seeing a limit of 762600 items in Chrome for both FixedSizeList and FixedSizeGrid.

The way the scrollbar works on Chrome it makes it easy to go to the bottom. It doesn't seem as easy on Firefox or on iOS Safari.

**Comment by scott-fleischman** [comment]
It seems related to itemSize, because with an itemSize of 22 I get 762600 items, but with itemSize of 20 I get 838860, and itemSize of 35 shows 479348 items.

**Comment by bvaughn** [comment]
Yes. This is browser specific.

See this comment:
https://github.com/bvaughn/react-window/issues/108#issuecomment-447489217
