### ISSUE TITLE
[VariableSizeList] How to reset estimatedItemSize ?

### ISSUE THREAD

**Issue by cosloli** [bvaughn/react-window#346]
I'm working on a `VariableSizelist` which list item is expandable. I expect to change `estimatedItemSize` after the `expand all` button is clicked. There seems no method can be used for this goal.

**Comment by bvaughn** [comment]
Try searching other issues. This question is asked often. 🙂

Here:
https://github.com/bvaughn/react-window/issues/344#issuecomment-540583132
