### ISSUE TITLE
CodeSandbox Examples don't seem to work

### ISSUE THREAD

**Issue by kpennell** [bvaughn/react-window#347]
![image](https://user-images.githubusercontent.com/1060385/67014830-cee0bf00-f0f5-11e9-915c-91b92bd5120f.png)

https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/fixed-size-list-vertical

**Comment by bvaughn** [comment]
Code Sandbox has bugs sometimes. :) The examples are fine. (Working again just now when I checked.)

**Comment by kpennell** [comment]
ah cool
