### ISSUE TITLE
Enforce itemSize recalculation in VariableSizeList

### ISSUE THREAD

**Issue by alex-mironov** [bvaughn/react-window#348]
I have a list of items which are loaded asynchronously. What I'm trying to achieve is to load the items with some initial height set up, and then update it's size as the async task is completed. Any help about the direction I should take to make it work would be super handy, thnx.

**Comment by bvaughn** [comment]
Have you searched issues about this? Seems like the same thing as #346, #344, etc.

**Comment by bvaughn** [comment]
Pretty sure this is a duplicate and the asnwer can be found on those issues so I'm going to close it :)
