### ISSUE TITLE
Broken Accessibility in iOS.

### ISSUE THREAD

**Issue by essar123** [bvaughn/react-window#349]
Hi,

I am using this great library for our mobile web app. Everything seems to be working great until I tried accessibility (voiceover/ talkback). For Android things are working as expected, but when **it comes to iOS I am not able to access all the list items by gesture at all. On initial load, accessibility is working great but as soon as the user clicks any item from the list (which opens details page for the clicked item) and comes back to list, After that user will only able to access items that are in the current viewport and rest of the item will be ignored by voiceOver**

I have **created a sample app on codesandbox** https://codesandbox.io/embed/gifted-ramanujan-h8jd9. I have tried my best to match HTML semantics of this demo app as our current app. 

**Here is a video of the same on iOS safari (12.1)**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16559472/67034524-74675300-f135-11e9-9957-981126ceecaa.gif)

**Comment by bvaughn** [comment]
> After that user will only able to access items that are in the current viewport and rest of the item will be ignored by voiceOver

Sounds like you're describing *how* a library like this intentionally works. To improve render time and memory impact, items that wouldn't be in the viewport are never rendered. This means no DOM elements are created (so there would be nothing for voiceover to read).

The reason this is different for initially load, presumably, is that you are starting at the top of the list and scrolling down- which will render things in order. When you go *back*, your app jumps to the previous scroll position, and react-window does not render things that would have been above it.
