### ISSUE TITLE
FixedSizeList data not refreshing after sort 

### ISSUE THREAD

**Issue by jonathanrp** [bvaughn/react-window#357]
Hi, I am using FixedSizeList on a table that has sort functionality. To get the sort working I create a copy of the data and then save that to a state, so I can pass the sorted data state to the table. Right now if I click the header to sort the column nothing happens, but I if scroll on the list the data updates and I get the sorted list. Is there any way to update the data after I call the sort functionality?

**Comment by tmmgn** [comment]
Have the same issue, cant figure out whats wrong and how to force update

**Comment by bvaughn** [comment]
Yes. The easiest way would be to just pass an additional prop (e.g. `sortDirection`) that changes when you re-sort your data. This will let React know to re-render `FixedSizeList`.

The current problem you're observing is that when your state changes, none of the props passed to `FixedSizeList` actually change (so it does not re-render).
