### ISSUE TITLE
Readme: - Does this library support "sticky" items?

### ISSUE THREAD

**Issue by elishas** [bvaughn/react-window#360]
The answer is yes. But the example doesn't work once that you put other indices like 0, 10, 20, 30, 40 ,50

Here is what It did when I've put these indices. https://codesandbox.io/embed/happy-hofstadter-x8wbg

The sticky should work like the following link: https://css-tricks.com/position-sticky-2/

Thanks,
Elisha

**Comment by bvaughn** [comment]
This isn't supported directly, sorry.
