### ISSUE TITLE
Pass parameters to innerElementType

### ISSUE THREAD

**Issue by naorye** [bvaughn/react-window#361]
I am using react-window to represent a calendar. I'd like to draw "events" which are elements that absolutely positioned on top of cells.   
For that reason I am creating a grid an pass custom element in innerElementType:
```
<Grid
      ...
      ...
      innerElementType={InnerGridElement}
/>

function InnerGridElement(props) {
      return (
            <div>
                  {children}
                  <Events data={props.data} />
            </div>
      );
}
```

How can I pass the data to InnerGridElement?

**Comment by bvaughn** [comment]
> How can I pass the data to InnerGridElement?

Have you considered using the [Context API](https://reactjs.org/docs/context.html#contextprovider) for this?

**Comment by naorye** [comment]
I can, but I hoped that I there is a way to use the same data property that is passed to the cells.

> Contextual data to be passed to the item renderer as a data prop. This is a light-weight alternative to React's built-in context API.

**Comment by bvaughn** [comment]
No. This data isn't passed to the inner/outer element types, only the cells

**Comment by naorye** [comment]
I noticed that behaviour :)
If you don't think it worth to pass also the data (and even the Grid props like height, rows count and so on), I guess that Context is the only solution.

Anyway, thanks for a great library.

NaorYe
