### ISSUE TITLE
Differences from react-virtualized?

### ISSUE THREAD

**Issue by bhovhannes** [bvaughn/react-window#37]
Hi,

I am just curious how is this different from react-virtualized?
Are there any conceptual differences?

Thanks!

**Comment by nihgwu** [comment]
#36 
Please search before fire an issue, also I don't think Issues is the QA place

**Comment by luisbelloch** [comment]
Also, if possible, it would be great to know what's the future plan for both projects. Would react virtualize deprecate part of the functionality in favour of react window? Or spin-off some parts of it as separated project?

Both projects are awesome, thanks for putting hard work on them! 😊

**Comment by TrySound** [comment]
@luisbelloch virtualized has a lot of functionality which won't be implemented in react-window, so both projects will exist independently. Maybe somebody will move some optimisations to from this project to virtualized.

**Comment by bvaughn** [comment]
Duplicate of #36 and #29 😄

@TrySound's answer is correct about the future plans.

**Comment by luisbelloch** [comment]
thanks for the info! 😊

**Comment by kpennell** [comment]
@bvaughn thanks for commenting here
