### ISSUE TITLE
FixedSizeList Height docs unclear

### ISSUE THREAD

**Issue by NickHeiner** [bvaughn/react-window#372]
Hi @bvaughn! I used `react-virtualized` in 2017 and am now excited to give `react-window` a try.

I'm trying to make a vertical `FixedSizeList`. The [docs](https://react-window.now.sh/#/api/FixedSizeList) are a bit unclear to me:

> **height: number | string**
> Height of the list.
>
> For vertical lists, this must be a number. It affects the number of rows that will be rendered (and displayed) at any given time.

Questions this leaves me with:

1. When it's a number, what is the unit? What does the number represent?
2. The number "affects" the number of rows – what precisely is the relationship between the number I pass and how many rows are shown?

Running it locally, it appears that the `height` prop is used to set a pixel height for the component. What if I want a non-fixed height, such as if the `FixedSizeList` is in a flex layout and I want it to have a min height, but also grow? I'm fine setting those properties myself using the `style` or `className` props, but I'm not sure if that's an anti-pattern.

(While I'm here, there are a few other spots in the docs that could be tightened up. For instance, the `children` prop is a render function that takes `(index, style)`, but the docs don't say what the type of `style` is.)

Thanks!

**Comment by bvaughn** [comment]
> When it's a number, what is the unit? What does the number represent?

The height of the list in pixels, The example code should hopefully illustrate this but if not, PRs for docs are welcome.

> The number "affects" the number of rows – what precisely is the relationship between the number I pass and how many rows are shown?

Libraries like this fill the available space. The bigger the height, the more rows will be rendered.

> Running it locally, it appears that the height prop is used to set a pixel height for the component. What if I want a non-fixed height, such as if the FixedSizeList is in a flex layout and I want it to have a min height, but also grow? I'm fine setting those properties myself using the style or className props, but I'm not sure if that's an anti-pattern.

You will need to provide an actual pixel height. If you don't know that height, you can use `react-virtualized-auto-sizer` to inject it as a prop: https://github.com/bvaughn/react-window#can-a-list-or-a-grid-fill-100-the-width-or-height-of-a-page

`index` is a number and `style` is an object.
