### ISSUE TITLE
Style Cache Busting

### ISSUE THREAD

**Issue by ntbosscher** [bvaughn/react-window#374]
I've got a variable sized list that is updated quite frequently. I'd like to have my item sizes recalculated when the data item changes which doesn't seem to be possible right now. 

First there's the memoizer cache https://github.com/bvaughn/react-window/blob/c43a2eeaa98e67fb1fe2cb571d964ea5a7ecabd5/src/createListComponent.js#L452

Then there's the getItemSize which seems to pull from an itemMetaDataMap (appears to be another cache) https://github.com/bvaughn/react-window/blob/c43a2eeaa98e67fb1fe2cb571d964ea5a7ecabd5/src/VariableSizeList.js#L177

It would be nice if styles were cached based on ItemData, so that changes to ItemData would result in a height recalculation. Right now I've hacked this by setting 
```tsx
<List key={this.state.reRenderIndex} />
``` 
and incrementing `reRenderIndex` each time I want the heights recalculated

**Comment by bvaughn** [comment]
Have you checked other similar issues?
The question about VariableSizeList and resetting cached sizes has been asked a few times :)

**Comment by ntbosscher** [comment]
Ah shoot! Sorry. I forgot to look in the closed issues :/

**Comment by bvaughn** [comment]
No worries. Would have linked you to a specific issue but on mobile.

**Comment by ntbosscher** [comment]
If anyone else comes across this, see https://github.com/bvaughn/react-window/issues/344#issuecomment-540583132
