### ISSUE TITLE
Scroll to top at render + focusout of the inputs (with a repro-case)

### ISSUE THREAD

**Issue by mr21** [bvaughn/react-window#377]
Hi :)

On this example https://codesandbox.io/s/beautiful-moore-h8rtt what i have to do to be able to update the state with the inputs without losing focus and without the scroll moving?
Does your dependence is compatible with this kind of scenario?

Anyway thx a lot for your work.

On the example i've used react-dom v16.8.6 to avoid a cross-origin error

**Comment by bvaughn** [comment]
Here you go
https://codesandbox.io/s/quirky-tree-f79bi

**Comment by mr21** [comment]
Thx a lot, i didn't realise the binding was capable to retrigger something.. but it's totally logical.
Thx again :)

**Comment by lavish0000** [comment]
can you please tell me how to achieve the same thing using functional components and hooks ?
