### ISSUE TITLE
Accordion effect

### ISSUE THREAD

**Issue by dht** [bvaughn/react-window#380]
```
<List
    ref={listRef}
    height={height}
    itemCount={items.length}
    itemData={items}
    itemSize={props.rowHeight}
    width={width}
    >
{props.cmp}
</List>
```

We are trying to implement a behaviour in which clicking on a row expands it for more details, however it seems the itemSize function is cached. Is there away to re-render on itemSize change?

**Comment by bvaughn** [comment]
Have you checked other similar issues?
The question about VariableSizeList and resetting cached sizes has been asked a few times :)

https://github.com/bvaughn/react-window/issues/344#issuecomment-540583132
