### ISSUE TITLE
Responsive FixedSize Grid shows more rows than needed

### ISSUE THREAD

**Issue by el1f** [bvaughn/react-window#382]
I am using the FixedSizeGrid to display a grid of cells, I define the `columnCount`, rowCount and sizes through some runtime variables that I change depending on the `screenSize`. This shows the exact result I expect it to show on laptop screens but on smaller screens it shows a grid that appears to be twice as high as the expected result. Am I missing something?

Grid Code
```
const ItemCardGrid: React.FC<ItemCardGridProps> = ({ mode, items, onClick }: ItemCardGridProps) => {
    const S = useMediaQuery('(min-width:360px)');
    const M = useMediaQuery('(min-width:600px)');
    const L = useMediaQuery('(min-width:1280px)');
    const XL = useMediaQuery('(min-width:1600px)');
    const isMini = mode === 'MINISPRITE';

    const grid = {
        cols: 0,
    };

    if (XL) {
        grid.cols = isMini ? 12 : 10;
    } else if (L) {
        grid.cols = isMini ? 7 : 5;
    } else if (M) {
        grid.cols = isMini ? 5 : 4;
    } else if (S) {
        grid.cols = isMini ? 3 : 2;
    } else {
        grid.cols = 2;
    }

    return (
        <Autosizer>
            {({ height, width }) => (
                <Grid
                    columnCount={grid.cols}
                    columnWidth={width / grid.cols}
                    height={height}
                    rowCount={Math.ceil((items || []).length / grid.cols)}
                    overscanRowCount={20}
                    rowHeight={isMini ? 116 : 180}
                    width={width}
                    style={{ margin: -4 }}
                >
                    {({ columnIndex, rowIndex, style }) => {
                        const id = getIdByGridPosition(columnIndex, rowIndex);
                        if (!items || items.length === 0 || id >= items.length) return null;
                        return <Cell {...items[id]} style={style} mode={mode} onClick={onClick} />;
                    }}
                </Grid>
            )}
        </Autosizer>
    );
};
```

Results (note the position of the scrollbar): 

LG screen
![image](https://user-images.githubusercontent.com/10723208/69293013-d836dd00-0c07-11ea-835f-07a4987da33d.png)

MD screen
![image](https://user-images.githubusercontent.com/10723208/69292966-b76e8780-0c07-11ea-8fc8-2fcc24df2b14.png)

SM screen (The scrollbar isn't visible due to it being too tiny but I'm around 1/4th of the way)
![image](https://user-images.githubusercontent.com/10723208/69293086-2946d100-0c08-11ea-8943-1ecacde8e19b.png)

**Comment by bvaughn** [comment]
Need a full repro on Code Sandbox. I don't have enough context to help with this.

**Comment by el1f** [comment]
There you are
https://codesandbox.io/s/modest-shadow-nknn1

**Comment by el1f** [comment]
Actually, having to rewrite the code for the Sandbox I realized it was an issue of mine... I was generating the wrong ids for the items which resulted in fewer items, therefore leaving a lot of empty space...
Excuse the spam.

**Comment by bvaughn** [comment]
No problem. This is one of the reasons I asked for repros 🙂
