### ISSUE TITLE
columnWidth in TypeScript

### ISSUE THREAD

**Issue by futurfutur** [bvaughn/react-window#386]
TS compiler returns error if columnWidth is set with function:
Type '(ind: number) => number' is not assignable to type 'number'

<Grid
          columnWidth={ind => arr[ind]}
          //...
 >

What do I miss?

**Comment by futurfutur** [comment]
sorry, used FixedSizeGridProps instead of VariableSizeGridProps

**Comment by bvaughn** [comment]
I don't have anything to do with the TypeScript types, sorry. You'll have to post about this over on DefinitelyTyped or wherever they're maintained.
