### ISSUE TITLE
resizing a list element after it is first rendered

### ISSUE THREAD

**Issue by gilesbradshaw** [bvaughn/react-window#388]
If I resize a list element after it's first rendered - for example on a click is it possible to re render the list to take account of new size?

**Comment by bvaughn** [comment]
This looks like a variation of a question that's been asked several times:
https://github.com/bvaughn/react-window/issues?q=is%3Aissue+resize+is%3Aclosed

Here's an answer:
https://github.com/bvaughn/react-window/issues/344#issuecomment-540583132

**Comment by gilesbradshaw** [comment]
Thanks! (I should have looked more thoroughly)
