### ISSUE TITLE
Is there a best practice solution for loading a VariableSizeList – scrolled to the absolute bottom on initial load?

### ISSUE THREAD

**Issue by zackster** [bvaughn/react-window#389]
I appreciate that there is an `initialScrollOffset` param, which seems to accept a pixels number and cannot be 100%.  My current "solution", which is incredibly hacky and doesn't work well, is..

1. I have a useState() hook to track whether it's the first render, `setFirstRender(true)`
2. Inside the `onItemsRendered` method, if it's the first render, I call `listRef.current.scrollToItem(chatLog.length - 1, "end");` then call `setScrollToEnd(true)` and `setFirstRender(false)`
3. Then inside my setSize method, I have this logic..

```
if(scrollToEnd && chatLog && (index === chatLog.length - 1)) {
      setScrollToEnd(false);
      listRef.current.scrollToItem(chatLog.length - 1, "end");    
}
```

since while scrolling down, maybe it recalculates the heights and another scrollToItem is appropriate.

I feel like I'm going about things the wrong way.  Is there a recommended way?

**Comment by bvaughn** [comment]
If you want to scroll to the "absolute bottom" of the list, I suggest you just use `scrollToItem` instead, and pass it the last index in your list :smile: List will take care of the offset calculation for you.

**Comment by zackster** [comment]
Hi Brian,

I don't mean to bug you with this, but scrollToItem(last-index) doesn't always scroll exactly to the absolute bottom.  I have a solution in place that involves manually computing row heights and setting the scrollOffset, and it's more or less reliable...

**Comment by bvaughn** [comment]
Sounds like maybe something that should be filed as a bug then.

**Comment by osamakhalil98** [comment]
@zackster any update on this? i face the same issue where i need the scroll bar to be at the absolute bottom of my VariableSizedList on the initial load and scrollToItem doesn't always work well.

**Comment by Charles-XD** [comment]
@osamakhalil98 I added the estimatedItemSize and increase it to the number, higher than my average list items.

**Comment by yelnyafacee** [comment]
> @osamakhalil98 I added the estimatedItemSize and increase it to the number, higher than my average list items.

are you refering to the `itemSize` of `VariableSizeList`? seems like a hacky solution to the problem
