### ISSUE TITLE
List.componentDidUpdate Warning: Scheduled a cascading update

### ISSUE THREAD

**Issue by pfcstyle** [bvaughn/react-window#392]
I caught a strange problem by "Performance" in chrome:

![image](https://user-images.githubusercontent.com/8980215/71249305-d1f76600-2357-11ea-9e13-91fde1bf0d6b.png)

The problem waste so many time between two render. 

The result is below: 
![image](https://user-images.githubusercontent.com/8980215/71249519-46320980-2358-11ea-9395-abf68fb635a2.png)
There is a so big blank area when scrolling quickly.

Ps: I have set the overscanCount property for **VariableSizeList**.

"react-window": "^1.8.5",
"@types/react": "^16.9.2",

Anyone have some suggestions to resolve this? 
Thanks!

**Comment by bvaughn** [comment]
The `componentDidUpdate` method of react-window list does not call `setState` so the cascading update must be triggered by the `onScroll` or `onItemsRendered` callback in your application code?

**Comment by pfcstyle** [comment]
Thanks for your fast reply.
Yes, you are right. The cascading update triggered by the onScroll callback. However, after removing the callback, the blank area is still exist. I guess my list items are too heavy.
I'll try to find the real reason and then update here if I resolve it.

**Comment by bvaughn** [comment]
Sounds like it, yeah.


You might try the useIsScrolling prop:

https://react-window.now.sh/#/examples/list/scrolling-indicators
