### ISSUE TITLE
Expanding list

### ISSUE THREAD

**Issue by dht** [bvaughn/react-window#393]
I am trying to implement a behaviour where clicking on a row expands its height.

      <List
                        ref={listRef}
                        height={height}
                        itemCount={items.length}
                        itemData={items}
                        itemSize={props.rowHeight}
                        width={width}
                    >
                        {memoize(props.cmp, areEqual)}
      </List>

I have noticed itemSize is called only once.
How can I recalculate itemSize when a row is clicked?

I've tried re-rendering the component on selectedId change and implementing:
```

    function rowHeight(index) {
        const item = items[index] || {};
        const isSelected = currentId === item.id;

        return isSelected ? rowHeightOpen : rowHeightClosed;
    }
```
It didn't seem to work.

**Comment by bvaughn** [comment]
I'm not at a computer so please excuse the brief response: Search closed
issues though. This has been asked a few times :)

>

**Comment by dht** [comment]
Found it, thanks.
https://github.com/bvaughn/react-window/issues/92

**Comment by bvaughn** [comment]
No prob!
