### ISSUE TITLE
What does style="will-change:transform" mean ?

### ISSUE THREAD

**Issue by NexxLuo** [bvaughn/react-window#395]
I found in the outter element has this style `will-change:transform`.
It can make the scroll area scroll more smoothly , but also has lag when i use `scrollTo` method to make two react-window component scroll together.

What does style="will-change:transform" mean , can i remove it?

**Comment by bvaughn** [comment]
You can read about the `will-change` style here:
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

> It can make the scroll area scroll more smoothly , but also has lag when i use scrollTo method to make two react-window component scroll together.

I've described why this is happening (and why it's expected) in some other issues/comments so I'm going to just link to one of them :smile:

https://github.com/bvaughn/react-virtualized/issues/369#issuecomment-243466104

**Comment by Hainesy** [comment]
This property affects z-index of absolutely-positioned child components, and means I cannot display an item as an inline-modal. Can `will-change` be optionally removed?
