### ISSUE TITLE
Using within SVG

### ISSUE THREAD

**Issue by jakub-chatrny** [bvaughn/react-window#397]
Hey,

I need to virtualize vertically oriented SVG using `FixedSizeList`.

I've found the way to do it by setting `innerElementType="svg"` and using "rowRenderer" for rendering SVG elements. What I also need is render some content after those elements. I've tried to wrap whole list with `svg` and then set `innerElementType` and `outerElementType` to `g` but that didn't work.

I guess i might append some content using `innerRef` but it's really hacky way.

What I rather do is add prop `innerElementAfterContent`. Will be PR like that welcome?

**Comment by bvaughn** [comment]
No. I would not accept a PR that added a property like that.

You should be able to do what you're looking to do by setting innerElementType to be e.g. a function component that renders an SVG containing props.children and then whatever extra things you want afterward, though.

**Comment by jakub-chatrny** [comment]
Cool, didn't realized that `innerElementType` can be a component, thanks!

Final solution for others:
```
<FixedSizeList
 ...
 innerElementType={
  ({children, ...restProps}) => 
   <svg {...restProps}>
     {children}
     <text` x="0" y="15 fill="red">
      AppendedSvgNode
     </text>
   </svg>
 }
>
            {SvgLineRenderer}
</FixedSizeList>
```
