### ISSUE TITLE
[Feature request] Bottom to top stacking of list elements (stack usage: chat, RPN calculator, etc)

### ISSUE THREAD

**Issue by radulle** [bvaughn/react-window#398]
It would be good if it was possible for list to be stacked from bottom instead from the top for usages like chat or stack like HS's old RPN calculators.

I have a workaround for FixedSizeList but if there is a need for such usage it would still be nice to have it (especially for VariableSizeList):
```
    <FixedSizeList
      height={Math.min(containerHeight, itemCount * itemSize)}
      itemCount={itemCount}
      itemSize={itemSize}
      width={winWidth}>
      {renderRow}
    </FixedSizeList>
```

**Comment by bvaughn** [comment]
This looks to be asking the same thing as #247 essentially.

Totally valid use case, but no plans to add support for this at the current time. I don't have the bandwidth.

**Comment by chrisdevereux** [comment]
You can hack this in by setting `transform: scaleY(-1)` on the list element and then doing the same on the cells. Works surprisingly well.

This unfortunately leaves the scroll direction wrong on mac. You can fix this by attaching the following ref to your list's `outerRef` prop (after making the appropriate platform checks).

```typescript
const useInvertScrollDirection = (enabled: boolean) => {
  const ref = useRef<HTMLDivElement>();

  const invertedWheelEvent = useCallback((e: WheelEvent) => {
    if (ref.current) {
      ref.current.scrollTop += -e.deltaY;
      e.preventDefault();
    }
  }, []);

  useEffect(
    () => () => {
      if (ref.current) {
        ref.current.removeEventListener("wheel", invertedWheelEvent);
      }
    },
    []
  );

  return (incomingRef: HTMLDivElement | null) => {
    if (!enabled || !incomingRef) {
      return;
    }

    ref.current = incomingRef;

    if (ref.current) {
      ref.current.addEventListener("wheel", invertedWheelEvent);
    }
  };
};
```

**Comment by plandem** [comment]
@chrisdevere codesandbox example would be great
