### ISSUE TITLE
Hide vertical scrollbar only while maintaining scroll capability

### ISSUE THREAD

**Issue by adrienpwd** [bvaughn/react-window#400]
Hi there.

Thank you for this awesome library, I was already a fan of react-virtualized, and i like this one even more !

I hope it's allowed to post here for help, even though it's not directly related to react-window.

I have 2 Grids, side by side, that are "synchronized".
I would like to hide the vertical scrollbar of the Left Grid so they appear as one single element.
But I still need to let the user scroll the left grid, using its keyboard, trackpad or mouse-wheel.

Here is an example:
https://codesandbox.io/s/focused-fire-4j5ro

Help would be appreciated, thank you !

**Comment by bvaughn** [comment]
Hi @adrienpwd. Thanks for the kind words.

Unfortunately I don't really have the time to help with this. All I can suggest is that you take a look at how e.g. [`MultiGrid`](https://github.com/bvaughn/react-virtualized/blob/master/source/MultiGrid/MultiGrid.js) is implemented in react-virtualized for ideas.

This is not a use case that I set out to support with this library. You might be able to make it work with the existing API (not sure). 😅 

Good luck!
