### ISSUE TITLE
[VariableSizeList]itemSize not change when itemData change

### ISSUE THREAD

**Issue by xingBri** [bvaughn/react-window#403]
Hey guys, I just met this problem when I use <VariableSizeList>. 
When I change itemData, the List change, but the item size not change. Then the item size go wrong.

**Comment by bvaughn** [comment]
This has been asked a lot of times:
* #344
* #280
* #273
* #223
* #202
* #199

Check out this answer:
https://github.com/bvaughn/react-window/issues/344#issuecomment-540583132
