### ISSUE TITLE
Add ability to pass props to the inner element

### ISSUE THREAD

**Issue by migueloller** [bvaughn/react-window#404]
Would the maintainers be open to adding a new prop to the component APIs that allows one to pass props to the element created from the `innerElementType` props?

Currently one is able to pass props to the outer element type by just passing top-level props. It's not possible to do so for the inner element type, though.

**Comment by bvaughn** [comment]
React's Context API can be used to share values with the inner element.

**Comment by migueloller** [comment]
@bvaughn, that's a good point.

**Comment by bvaughn** [comment]
Thanks for being understanding! :)

**Comment by stoplion** [comment]
There is no way to pass props (i.e. an onClick handler) to the inner element?
