### ISSUE TITLE
Adding DnD options?

### ISSUE THREAD

**Issue by michaltaberski** [bvaughn/react-window#405]
Hi, 

I am thinking about using `react-window` for long lists together with drag and drop functionalities. I would like to ask if there are patterns already for such case or in general if `react-window` is a good choice if it has to be combined with DnD. Do you have any experience on that?

**Comment by carlosagsmendes** [comment]
Hi @michaltaberski have you checked [React Beautiful DND](https://github.com/atlassian/react-beautiful-dnd)? 

They have [examples on how to use it with react-window](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/virtual-lists.md)

**Comment by bvaughn** [comment]
Yup, use React Beautiful DND.

Thanks for sharing the link, Carlos!

**Comment by AdhamMoussa** [comment]
I have a problem using react-beautiful-dnd with react-window
my list is variable size list. I calculate height based on data
the initial render looks fine, but when I drag and drop a large card, the layout looks broken. the available space for the card is suitable only to the small card. anyone had the same issue before?
