### ISSUE TITLE
Non-stop re-rendering

### ISSUE THREAD

**Issue by maynir** [bvaughn/react-window#41]
I'm having a non-stop re-rendering.
In this simple example, I'm just rendering div containing "X".
I gave it the right height and width, tried to remove every possible CSS and I just can't get it.

Elements:
![ezgif com-crop](https://user-images.githubusercontent.com/35686764/44040741-b094d19a-9f24-11e8-876a-c7d6e51135cf.gif)

Screen:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35686764/44040891-0a03295c-9f25-11e8-84e2-76fd871809e9.gif)

my code:
```
<div>
        <List
                height={200}
                itemCount={this.state.filteredValues.length}
                itemSize={17}
                width={682}
                overscanCount={10}
            >
                {({ index, style }) => (
                    <div> X </div>
                )}
            </List>
    </div>

**Comment by bvaughn** [comment]
> I gave it the right height and width, tried to remove every possible CSS and I just can't get it.

Not sure what you mean by this, but your example doesn't seem to be using the `style` parameter passed to it which would cause a problem. The `style` parameter is what positions and sizes the elements in your list.

Also, what do you mean by "nonstop rendering" ? In the code example you provide above, you configure the list to be 200 pixels tall and tell it that items are 17 pixels tall, _and_ that you want it to pre-render ("overscan") 10 additional items. This means that it will render ~22 items. (As a side note, I would advise against an overscan value that high. Probably 1-3 is best.)

**Comment by bvaughn** [comment]
I'm going to close this issue since it isn't really actionable. We can chat more here if there are follow up questions though.

**Comment by maynir** [comment]
Hi Brian,
I added the style option and that solved the problem.
I would like to if there is an option for rendering when there is no
results?
(like you have in react virtualized)
Thank you.

**Comment by bvaughn** [comment]
No, nothing built into react-window. I think the easiest thing to do is to just return a different component, e.g.
```js
if (numItems === 0) {
  return <NoResultsView />;
} else {
  return <FixedSizeList />;
}
```
