### ISSUE TITLE
Text selection disappearing on scroll.

### ISSUE THREAD

**Issue by clems4ever** [bvaughn/react-window#410]
Hello, I'm trying to use react-window to display a large text file and only render a subset. The user can scroll up and down to read the file. I'd like to let the user copy and paste but I found out that when I select some text with my mouse and scroll, the selection automatically disappears. Is it expected? Are you aware of that behavior? Do you have any idea on how to workaround that? 

Please note I'd rather like to use the feature provided by the browser than a simulated text selection in my application in order to avoid incompatibilities between browsers.

Thank you in advance.

**Comment by bvaughn** [comment]
It's expected, given the way this library works:
https://twitter.com/brian_d_vaughn/status/957048801130299392

What's happening is that, as you scroll, as elements are scrolled off screen, they are either removed and thrown away, or moved and reused to show new content. Either way, the text you selected previously is no longer there to copy-paste.

There's no way to work around this while using this library for the time being. It's a performance trade off.
