### ISSUE TITLE
[question] Is horizontal orientation supported?

### ISSUE THREAD

**Issue by herchu** [bvaughn/react-window#414]
I came across this awesome library from https://www.youtube.com/watch?v=nySib7ipZdk -- awesome job, thanks!

Is there any way to use react-window on a large horizontal list? Our app contains lots (100s, 1000s) of  fixed-size elements, each of them a small _column_ with information (ie. there is no vertical scrolling, only horizontal). We want to make use of the "lazy" rendering when scrolling left-right. Is this supported in react-window?

**Comment by bvaughn** [comment]
Please check out the docs first!
https://react-window.now.sh/

Horizontal scrolling is shown on the home page :smile: (with example code)

**Comment by herchu** [comment]
Ohh I totally missed the link _to the home page_. I had only read the github home page, thinking "there should be more than this", and missed it.

Sorry for the spam. And thanks for the quick response!
