### ISSUE TITLE
Could you give some guidance on table headers?

### ISSUE THREAD

**Issue by boatcoder** [bvaughn/react-window#416]
The problem I'm running into is when the table is wider than the space available, the scroll bar eats into the table space:

![image](https://user-images.githubusercontent.com/18578897/73974037-a7ef0880-48f1-11ea-9a0e-0360b881456d.png)

When there is sufficient space for the for the scroll bar, it looks like this, which is not totally ideal, but better than above.

![image](https://user-images.githubusercontent.com/18578897/73973647-fbad2200-48f0-11ea-8331-d09331b92b07.png)

[This issue](https://github.com/bvaughn/react-window/issues/9) was killed off almost 2 years ago but I don't see anything other than [stickyrows](https://codesandbox.io/s/0mk3qwpl4l) which has my header as a "data" row which then complicates sorting and filtering.

The other things I've thought of (absolute positioning, floating a div) all seem unworkable or a have other problems.

**Comment by bvaughn** [comment]
Unfortunately the short answer is no, I don't really have the bandwidth to give guidance for this. Sorry about that! I'm always pretty swamped though lately.

This library does not offer a table component like react-virtualized does. You might be able to build one on top of it. You might find the source for `Table` to be a useful starting point:
https://github.com/bvaughn/react-virtualized/tree/master/source/Table
