### ISSUE TITLE
Input always losing focus when setNewState to data array

### ISSUE THREAD

**Issue by Taymindis** [bvaughn/react-window#420]
please try this codesand box, when you key something on textbox, it loses focus

[https://codesandbox.io/s/react-window-x9gwc](https://codesandbox.io/s/react-window-x9gwc)

**Comment by Taymindis** [comment]
react virtualized has no issue at all

[https://codesandbox.io/s/react-virtualized-list-with-width-100-7btt7](https://codesandbox.io/s/react-virtualized-list-with-width-100-7btt7)

**Comment by bvaughn** [comment]
Don't define your item renderer inline. It will get recreated each time the parent component re-renders which will mess with text selection apparently.

https://codesandbox.io/s/react-window-5yzbr

**Comment by ZeeCoder** [comment]
If this is the case the docs should probably reflect it:
https://react-window.vercel.app/#/api/FixedSizeList

This just tripped me and had no idea why my rows were unmounting.

**Comment by glitcher93** [comment]
Hi I seem to be having a similar issue where my inputs are losing focus after typing one character and the scrollbar jumps up immediately after losing focus

**Comment by bvaughn** [comment]
The same answer applies as above: Don't define your renderer inline.

Any time _any of the things_ in your dependencies array change (entireUnit, preConstruction, demolition, livingDining, kitchen, bedroom, bathroom, powder, misc, entireUnitQuantities, preConQuantities, demoQuantities, livingDiningQuantities, kitchenQuantities, bedroomQuantities, bathroomQuantities, powderQuantities, miscQuantities) your renderer will be recreated, and state for things like text inputs will be lost.

**Comment by glitcher93** [comment]
> The same answer applies as above: Don't define your renderer inline.
> 
> Any time _any of the things_ in your dependencies array change (entireUnit, preConstruction, demolition, livingDining, kitchen, bedroom, bathroom, powder, misc, entireUnitQuantities, preConQuantities, demoQuantities, livingDiningQuantities, kitchenQuantities, bedroomQuantities, bathroomQuantities, powderQuantities, miscQuantities) your renderer will be recreated, and state for things like text inputs will be lost.

can you maybe elaborate more on this? im not exactly sure how to tackle this.

**Comment by bvaughn** [comment]
Did you check out the comment above before the issue was closed?

https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335

They link to a suggested solution.

**Comment by glitcher93** [comment]
> Did you check out the comment above before the issue was closed?
> 
> [#420 (comment)](https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335)
> 
> They link to a suggested solution.

Yes, but the codesandbox isn't working in it, so its not really providing any clues

**Comment by glitcher93** [comment]
> Did you check out the comment above before the issue was closed?
> 
> [#420 (comment)](https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335)
> 
> They link to a suggested solution.

I think I see it now, the item renderer shouldn't be inside the component but outside the component, am I correct in that assumption?

**Comment by mayanksolan** [comment]
> > Did you check out the comment above before the issue was closed?
> > [#420 (comment)](https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335)
> > They link to a suggested solution.
> 
> I think I see it now, the item renderer shouldn't be inside the component but outside the component, am I correct in that assumption?

Yes, that is how the issue is resolved, the item renderer shouldn't be inside the component but outside the component

**Comment by sunpcm** [comment]
> I think I see it now, the item renderer shouldn't be inside the component but outside the component, am I correct in that assumption?

Upgrading React to version 16.6.0 or higher and ensuring you are using Ant Design version 3.x will resolve the issue. If you are using Ant Design 4.x or later, you should use the new form API instead of Form.create()
