### ISSUE TITLE
Feature: Add reverse support

### ISSUE THREAD

**Issue by martinboksa** [bvaughn/react-window#423]
Hello,
do you have the plan to add layout for **reversed array**?  
I was thinking about to use your `react-virtualized` with reverse support but I can't figure out how really slow is too use reversed array in the variable list with item key in `react-window` now. 

Maybe some description, please? 
Currently, I have to use `resetAfterIndex(0, true)` after each `unshift to array`.
Is currently a better solution to render reversed array? 

Thanks

**Comment by bvaughn** [comment]
Same question as #247, and still the same answer 🙂 no plans to add support for this.

**Comment by corupta** [comment]
Back in the day, I implemented it for myself for some specific case, [https://github.com/corupta/react-window/tree/npm](corupta/react-window)
It did work with `npm install --save react-window-reversed`
If new version features are not needed for you, you can use that, I don't have any plans to merge latest version.
