### ISSUE TITLE
Keep the background color when scrolling

### ISSUE THREAD

**Issue by difagume** [bvaughn/react-window#424]
Hello thank you very much for the component, I'm using with material-ui and I have a small problem when I scroll down the list, the background color of the Avatar component begins to change, I am placing the background color to each row by calling a function randomMaterialColor(), but I would like to prevent it from changing, I hope you can guide me to solve this, I leave the practical link so you can see the code, thank you very much

https://codesandbox.io/s/material-demo-0cf86?fontsize=14&hidenavigation=1&theme=dark

![list](https://user-images.githubusercontent.com/5271339/74750329-8f5be800-5239-11ea-868f-c4912b757b44.gif)

**Comment by bvaughn** [comment]
If the color is random, then it will change. React window does not store data anywhere. React Window doesn't s Color should be part of the underlying row data. :)

Store this somewhere higher up, and use `itemData` API.

https://react-window.now.sh/#/examples/list/memoized-list-items
