### ISSUE TITLE
How are people calculating the height of each row for VariableSizeList ?

### ISSUE THREAD

**Issue by noahehall** [bvaughn/react-window#430]
i'm using a very rudimentary solution

`const itemSize = index => (props.messages[index].text.length / 20 % 10 * 25) + 70`

whats your method?

- [a decent method here](https://codesandbox.io/s/dynamic-size-of-react-window-list-items-64o9p) sourced from [this comment](https://github.com/bvaughn/react-window/issues/6#issuecomment-538261156)

**Comment by wangzongming** [comment]
What I do is, when the line DOM is rendered, I get the height（VariableSizeList  height）. Then update the height, and finally call the listRef. Current. ResetAfterIndex (0). And then it's magically OK
