### ISSUE TITLE
[Feature Request] Specify width of <Grid> component with function or string

### ISSUE THREAD

**Issue by dukartbr** [bvaughn/react-window#431]
I'd like to create a grid with a more responsive width rather than a set integer. Ideally, you could set the width of the grid in the same way you could set the width:

<img width="558" alt="Screen Shot 2020-02-24 at 10 05 48 AM" src="https://user-images.githubusercontent.com/24302915/75168980-5f0ac280-56ed-11ea-8922-61dc7983a6d2.png">

**Comment by bvaughn** [comment]
You can already do this. Just store `width` in state and your parent component (wherever `gridWidth` is defined) will re-render when it changes.
