### ISSUE TITLE
Related to DOM nodes accumulation in memory while scrolling in DynamicSizeList. 

### ISSUE THREAD

**Issue by dheerajk30** [bvaughn/react-window#433]
@bvaughn  I was checking out the demo of DynamicSizeList here(https://react-window-next.now.sh/#/examples/list/dynamic-size) when I noticed that there is a memory leak in scrolling effect as the DOM nodes are increasing while scrolling but they don't get garbage collected somehow. I started from DOM nodes count ~2000 and after scrolling for some time, it increased to ~9000 and never went back to the initial count. This will become very problematic when the user is continously scrolling through the app. I checked if the same issue is there in FixedSizeList or DynamicSizeList but it is not there

**Comment by BrianHung** [comment]
I see a memory leak in DOM Nodes with the FixedSizeList on that example page as well. Oddly enough, on the code sandbox example, there isn't a memory leak.
