### ISSUE TITLE
Nested arrays

### ISSUE THREAD

**Issue by dougg0k** [bvaughn/react-window#435]
Hello,

Does `react-window` support nested array? I didn't see anything resembling it. 

Here is a example of what I would try to build:
```js
function Category({ title, items }) {
	return (
		<CategoryContainer>
			<CategoryTitle category={title}>{title}</CategoryTitle>
			<ProductItemContainer>
				{items[title].map((item: ProductProps) => (
					<ProductItem key={item.name} item={item} category={title} />
				))}
			</ProductItemContainer>
		</CategoryContainer>
	);
}

function ProductList({ items }) {
	return (
		<Container>
			{items &&
				Object.keys(items).map(key => (
					<Category key={key} title={key} items={items} />
				))}
		</Container>
	);
}
```
If possible, any suggestions in how?

**Comment by bvaughn** [comment]
No. `react-window` doesn't do anything with arrays or lists directly. It expects you to tell it the total item count. In your case, that probably means flattening the array or some other counting operation. There aren't any utilities in this library to help you with that though :smiles: Sorry!

**Comment by dougg0k** [comment]
No worries, thanks for the quick answer.
