### ISSUE TITLE
scrollTo breaks when passing ref to useRef in outerElementType

### ISSUE THREAD

**Issue by baldurpan** [bvaughn/react-window#437]
In my project, I'm using a custom component for outerElementType to create a header and sync horizontal scroll position.
So in my case, I need to pass the ref to useRef to be able to do anything with it. That seems to work fine in general, except that the scrollTo/scrollToItem methods start rendering blank content.

Sandbox:
https://codesandbox.io/s/bvaughnreact-window-fixed-size-list-vertical-7jjwz

**Comment by bvaughn** [comment]
If you inject your own ref, you need to make sure react-window's ref still gets passed along too. The way to do that is using a callback ref to compose the two:

https://codesandbox.io/s/bvaughnreact-window-fixed-size-list-vertical-wqmeo

**Comment by snirdahan01** [comment]
Is it possible with react-custom-scrollbars-2? @bvaughn current solution you provided (for react-custom-scrollbars) is not working for react-custom-scrollbars-2
