### ISSUE TITLE
re-render problem using redux

### ISSUE THREAD

**Issue by manueldelapenna** [bvaughn/react-window#438]
Hi!

I'm trying to virtualize a large list of a custom component.

My component renders information from my store (I'm using redux) and has a textfield to update information via redux, using dispatchers.

I have my component memoized and I added "areEqual" for second parameter, but when I dispatch the action for update the store, all components are re-rendered (this doesn't occours if I don't use the library)

This is a simplification of the code:
`var MyComponent = React.memo(function MyComponent(props:{
    style, index
}){
    return <TextField
            onchange={(value)=>
                dispatch(dispatchers.SET_VALUE({
                    index: props.index
                    value:value
                }))
            }
        />
}, areEqual)

function ParentComponent(props{}){
    const {myList} = useSelector((myInfo)=>myInfo.myList);
    const Row = ({ index, style }) => {
        return <MyComponent index={index} style={style}/>
    };
    return <div>
        <VariableSizeList
            height={900}
            itemCount={myList.length}
            itemSize={getItemSize}
            width={650}
        >
            {Row}
        </VariableSizeList>
    </div>
}`

I don't know if I'm doing something wrong or if library don't have support for this!

regards!

**Comment by bvaughn** [comment]
Simplification of code isn't going to be enough. Please provide something I can run on Code Sandbox. :)

**Comment by manueldelapenna** [comment]
I forgot to import memoize function from "memoize-one", now it works perfectly!

Thank you very much!

**Comment by bvaughn** [comment]
Yup, glad to hear!
