### ISSUE TITLE
Add follow that keeps the scroll at the bottom

### ISSUE THREAD

**Issue by angaz** [bvaughn/react-window#439]
Add a boolean field, `follow`, that keeps the scrollbar at the bottom for showing growing lists, such as logs. At the moment, I have a `useEffect` and `scrollTo` to get it to stay at the bottom, but it would be nice to have it scroll to the bottom via a prop.

I will have a look if I can implement this in a nice way over the weekend.

**Comment by bvaughn** [comment]
This does not sound like something I'm interested in adding to react-window List/Grid as built-in functionality.

**Comment by pimterry** [comment]
I wanted this feature, but I'm actually +1 for not including it as a built-in feature - it's very easy to implement from scratch, and the existing API makes it possible to even handle fiddly cases.

In case others are trying to implement this, here's an example where the window follows the bottom by default, unless you manually scroll away from it: https://github.com/httptoolkit/httptoolkit-ui/commit/515ad833cc6f78528ae9a36b7ff11ac128bc2a18
