### ISSUE TITLE
Using FixedSizeList + AutoSizer + InfiniteLoader

### ISSUE THREAD

**Issue by vkolova** [bvaughn/react-window#440]
Hello!

I'm trying to do a setup of FixedSizeList, AutoSizer and InfiniteLoader working together, but the loadMoreItems function doesn't seem to get called.

Here's a sample that shows the issue I'm having [click](https://codesandbox.io/s/modest-borg-8wlb5)

Is the `itemCount` prop supposed to not change? Cause my component is connected to a subscription and whenever something new happens I need to show it.

I'm probably missing something really important here but I'm not sure what.

**Comment by LittlePony** [comment]
isItemLoaded should return false, that never happens in you code

**Comment by vkolova** [comment]
Wow, I never noticed that. Thanks!

**Comment by erikdao** [comment]
@vkolova Hi, how did you solve this issue? It seems that I'm dealing with a similar problem but I haven't got any clue on why my `loadMoreItems` function isn't invoked.

**Comment by vkolova** [comment]
@erikdao I re-worked my code like:
```
isItemLoaded = itemsCount => index => {
        return (itemsCount - index) > 5;
    }
```
which I pass like
```
<InfiniteLoader
          isItemLoaded={this.isItemLoaded(itemsCount)}
          itemCount={itemsCount}>
```
That way I can set it to start loading new rows a few items before the end of the rendered list.
