### ISSUE TITLE
[DynamicSizeList] wrong size if item changes index

### ISSUE THREAD

**Issue by daviderenger** [bvaughn/react-window#445]
Hi!

I really like the concept of the dynaimList and trying to make it work for my use case (a filterable list of items). Almost everything is now working as expected after some tweaking but I have one issue left I dont really see a solution for.

So say you have a list that look like this that is rendered:

0. item A, small size
1. Item B, large size
2. Item C, large size
... and many more

And I enter some text in the filter input so it now looks like this:

0. Item B, large size
1. Item C, large size
... and many more

What is happening now is that Item B, that is now on index 0 inherits its size from item A that is no longer rendered. Even they have different keys. So Item C is overlapping Item B.

If a scroll down a bit and back up it is correcting itself.

A guess is that is because of this in the render function:
```
const { size } = getItemMetadata(
            instance.props,
            index,
            instanceProps
          );
```

Its getting its saved size based on index and not on key.
And since it was already mounted before the ItemMeasurer is not doing its initial check for size (but it should capture the resize?).

**Comment by nopol10** [comment]
As a temporary workaround, setting a _key_ prop (based on the search string for e.g.) on the DynamicSizeList to make React create a new instance of the list every time the filter condition changes seems to work

**Comment by korzo-fortegrp** [comment]
Also you can call `resetAfterIndex` method of list instance to reset cache.

**Comment by Qlipoth** [comment]
is it possible update top position after removing/adding new rows into DOM? https://codesandbox.io/s/priceless-villani-ph05n?file=/src/App.js:3081-3102
