### ISSUE TITLE
How to abstract out height, width, rowWidth?

### ISSUE THREAD

**Issue by MikeWarren2014** [bvaughn/react-window#446]
First, thank you for providing us with this essential project!!! After seeing some of the demos, including from the Dev Tools, this project looks exactly like what my team needs right now! 

Right now, we're just rendering the table rows, as-is, and not hard-coding in any table row heights, or any table cell widths. If we need to fix a table column width, we put that on the corresponding table header, as width percentage, not as hard-coded pixel-width. 

Also, our table rows are their own components.

Here is example of one of our tables (full of test data, of course, and on the largest screen I can access right now): 
![Sample table](https://user-images.githubusercontent.com/10160410/77565649-ebe69e80-6e9a-11ea-9357-0546af44a242.png)

I am itching to refactor our site, using your project, but right now I'm facing issue. I see that, in all of these examples, and examples I can find elsewhere, that the `itemSize` or `rowHeight` is either hardcoded or calculated. This is problematic, because we have the Bootstrap CSS files computing the size of the cells (thus the size of the rows), based on the content within. I am also not trying to do some hacks to somehow tightly couple that with this. 

Is there any way to omit having to have a hardcoded `itemSize` or `rowHeight`?

**Comment by mayeths** [comment]
I use ref and add listener to window to do it. A sample code from my project like this (didn't test):
```javascript
import { useState, useRef, useEffect } from 'react'
import { FixedSizeList as List } from 'react-window'

const Row = ({ index, style }) => <div style={style}>Row {index}</div>

const Example = () => {
  const containerRef = useRef(null)
  const [itemSize, setItemSize] = useState(35)
  useEffect(() => {
    window.addEventListener('resize', updateItemSize)
    return () => window.removeEventListener('resize', updateItemSize)
  }, [])

  return (
    <div ref={containerRef}>
      <List height={150} itemCount={1000} itemSize={itemSize} width={300}>
        {Row}
      </List>
    </div>
  )

  function updateItemSize() {
    const containerHeight = document.body.clientHeight
    // Or
    // if (!containerRef.current) return
    // const containerHeight = containerRef.current.clientHeight
    if (0 < containerHeight && containerHeight < 500) {
      setItemSize(50)
    } else if (500 < containerHeight && containerHeight < 1000) {
      setItemSize(65)
    } else {
      setItemSize(75)
    }
  }
}

```
