### ISSUE TITLE
IsScrolling is not set in scrollTo method

### ISSUE THREAD

**Issue by duvet86** [bvaughn/react-window#447]
Hi,
I've a component that's composed of a grid as body and a list as header. The header is fixed and I'm keeping them in sync with the scrollTo method.
Both header and body have very expensive cells to render and I was using the useIsScrolling prop to display a placeholder but when the grid scrolls the isScrolling variable is not set in the header. 
I was looking at the source code: https://github.com/bvaughn/react-window/blob/f2b2106cc828e9828cf2940411e5eab67f1d7aa6/src/createListComponent.js#L182-L196
and effectively the variable is missing.

Cheers

**Comment by tapayne88** [comment]
I was looking for an answer to this, found this which helped #195
