### ISSUE TITLE
Way to determine local item index.

### ISSUE THREAD

**Issue by cryszero** [bvaughn/react-window#451]
Hey guys, I'm trying to implement a tree component with dots on the opened tree branch items, but I can't find a way to get local indexes in the List item. You can get the main index number from the flatten array, which you are rendering, but is there any "legit" way to get some sort of localized one? For example, if react-window renders 24 items, how can I determine which one is last and which one is first?

**Comment by korzo-fortegrp** [comment]
@cryszero I think you can do it with `itemData` prop. And calculate it by yourself.

**Comment by cryszero** [comment]
> @cryszero I think you can do it with `itemData` prop. And calculate it by yourself.

itemData is just a prop to insert data, but there is no way to get it first.
I mean, we already have onItemsRendered callback, which has all this useful data, but it gets called AFTER render, which is not that useful for me, because it would call massive rerender loops after pretty much any cation.

**Comment by korzo-fortegrp** [comment]
> > @cryszero I think you can do it with `itemData` prop. And calculate it by yourself.
> 
> itemData is just a prop to insert data, but there is no way to get it first.
> I mean, we already have onItemsRendered callback, which has all this useful data, but it gets called AFTER render, which is not that useful for me, because it would call massive rerender loops after pretty much any cation.

I mean that you can calculate last and first item indexes, because you now height of the list, height of the item, and it becomes easy to calculate your indexes.
