### ISSUE TITLE
React Window Infinite Loader with Redux

### ISSUE THREAD

**Issue by janhesters** [bvaughn/react-window#453]
The [React Window Infinite Loader](https://github.com/bvaughn/react-window-infinite-loader) expects `loadMoreItems` to be a promise. I would like to fetch my data using Redux by dispatching an action. Is there any way to achieve this?

**Comment by atfera** [comment]
Did you find a solution @janhesters ?
I'm using Relay to fetch data, the problem is the function used in Relay [loadMore](https://relay.dev/docs/en/pagination-container#loadmore) return an object `Disposable` and not a promise.

**Comment by alessandrojcm** [comment]
The way I solved is to "fake" the asynchrony, in my project we are using RXJS: so I took the `loading` state from redux and created an observable from it, and then that observable I converted to a promise:

```javascript
const loadingObs = of(loading)
            .pipe(
                filter((l) => !l), // Only emit when loading is false
                switchMapTo(of()), // the resulting promise will resolve with no value, like Promise.resolve()
                takeUntil(destroy$) // will unsubscribe when destroy$ emits, destroy$ emits in useEffect cleanup
            )
            .toPromise();
```
Then I take the callback from `mapDispatchToProps` and create a "patch" function which I pass to the list:

```javascript
const patchedFunction = (startIndex: number, stopIndex: number) => {
    fetchMore(startIndex, stopIndex);
    return loadingObs;
}
```

I think this could be implemented with plain promises (maybe with the help of hooks); but hopefully, this will give you some ideas :wink:

**Comment by atfera** [comment]
> The way I solved is to "fake" the asynchrony, in my project we are using RXJS: so I took the `loading` state from redux and created an observable from it, and then that observable I converted to a promise:
> 
> ```js
> const loadingObs = of(loading)
>             .pipe(
>                 filter((l) => !l), // Only emit when loading is false
>                 switchMapTo(of()), // the resulting promise will resolve with no value, like Promise.resolve()
>                 takeUntil(destroy$) // will unsubscribe when destroy$ emits, destroy$ emits in useEffect cleanup
>             )
>             .toPromise();
> ```
> 
> Then I take the callback from `mapDispatchToProps` and create a "patch" function which I pass to the list:
> 
> ```js
> const patchedFunction = (startIndex: number, stopIndex: number) => {
>     fetchMore(startIndex, stopIndex);
>     return loadingObs;
> }
> ```
> 
> I think this could be implemented with plain promises (maybe with the help of hooks); but hopefully, this will give you some ideas 😉

Yeah, I just used `Promise.resolve()` to convert it, and it works. Still having issue, but it's another problem. Thanks for the tips.
