### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kserjey** [bvaughn/react-window#454]
I have implemented infinite scroll with your libraries (`react-window`, `react-window-infinite-loader`) according to guides and it works fine, but there is a problem with testing. When I tried to test my component I ran into problem that there is nothing inside `FixedSizeList`. I haven't found anything about testing in the docs. Is it a bug or I missed something?

Here is [codesandbox](https://codesandbox.io/s/react-window-testing-issue-gunx7)

**Comment by effectivetom** [comment]
I'm having the same issue. At first I thought it was because I wasn't mocking `AutoSizer` correctly, but I've verified that it's receiving correct `width` and `height` props in my tests, and `FixedSizeList` is still empty. My implementation is pretty barebones.

**Comment by haithemT** [comment]
did you try to mock autoSizer
`jest.mock('react-virtualized-auto-sizer', () => ({ children }: any) => children({ height: 600, width: 600 }));`

**Comment by OriAmir** [comment]
but why I need to mock that? I try to understand whats the different between the "original" AutoSizer to the one that exists in separate library ?

**Comment by haithemT** [comment]
there is a condition to prevent children from rendering if width or height are 0
https://github.com/bvaughn/react-virtualized-auto-sizer/blob/ffcba2dd39b89111ed4b42d64431f35ce7c1c23a/src/index.js#L123

since we are using jest-dom for testing the calculation will never happen and height and width will be always 0.

in the original AutoSizer this condition doesn't exist so the children will always render.

**Comment by OriAmir** [comment]
@haithemT get you,thanks for that!
the problem that my component render the Autosizer inside component with a lot of data.

I try to mock like you says but still nothing inside the container:
    j```
est.mock(
      "react-virtualized-auto-sizer",
      () => ({ children }) => children({ height: 1000, width: 1000 })
    );
    const wrapper = mount(
      <VariablesContainer
        variables={[...dieslVariables, ...cu_cloudVariables]}
      />
    );
    .... try to find some variable inside the container but nothing exists
```

**Comment by haithemT** [comment]
honestly i'm using this library from it first release and till now i didn't encounter any blocking issues, i tried some other new libraries but none of them was performant like this one.
