### ISSUE TITLE
Improved render performance while scrolling in Chrome under weird condition

### ISSUE THREAD

**Issue by beauroberts** [bvaughn/react-window#455]
First of all, thanks for all your contributions to the community and in particular this amazing library. Second, I want to apologise in advance if this has already been noted elsewhere and I have missed it. 

While creating some debug overlays to visualise the rendered item regions, I stumbled on a weird situation in Chrome (Version 80.0.3987.163) on macOS Catalina where I see improved performance if I cover the scroll region with an absolute-positioned element with `pointerEvents: "none"` styling:

![react-window-performance](https://user-images.githubusercontent.com/337712/79636326-bc137980-816e-11ea-8843-a8c7426c33a8.gif)

[Here is a codesandbox.io link that demonstrates the situation](https://codesandbox.io/s/inspiring-silence-n4ygq?file=/src/App.js) - because `react-window` is so performant already, I find it's best to break the preview off into its own window and scroll vigorously (really get those fingers flyin') to see the flashes of empty content. Then tick on the "show overlay" checkbox at the bottom of the page and observe the difference. It's odd, but no matter how hard I try I can't get the flash to occur while the overlay is visible.

I'm curious if someone can enlighten me as to what might be happening here? I've probably neglected to think of something obvious. Are there any drawbacks you can think of if I just...keep this overlay there all the time? Thanks for your thoughts!

**Comment by beauroberts** [comment]
UPDATE: After testing with some heavier-weight cell renderers, I can see that frames are being dropped, so it's not improved performance. Looks like maybe the rate at which the region is re-rendering while scrolling is reduced?

**Comment by olehhusiev** [comment]
Hi @beauroberts, it's a good solution and it works for me with 1000 items,  but I have a question about it. What do you mean with "_heavier-weight cell_" and what conditions doesn't work for you?

**Comment by beauroberts** [comment]
Hey @olehhusiev thanks for confirming that it works for you too! I have a test environment with 10,000 items and it seems to be performing nicely also.

By "heavier-weight cell" I mean a cell that takes more time to render than the simple text cell I used in my example. When this hack is in place, you can get poor scrolling performance if the individual items are very costly. But if you have optimised the rendering of your items, it seems like this hack can lead to better perceived performance.

My colleague @woollenhat did more thorough investigation into this than I did, and discovered a couple of interesting things:

First, that the performance is actually better _without_ the hack, as demonstrated by the two halves of the profiler output here. The left half is _without_ the overlay hack and the right half is _with_ the overlay hack:

<img width="1536" alt="Screenshot 2020-04-20 at 11 18 58" src="https://user-images.githubusercontent.com/337712/80028834-b1921080-84dd-11ea-960b-16993e94ff59.png">

Second, he noticed that when you place the overlay over only half of the scroll container, the performance changes based on where your mouse is. That effect can be seen in [this forked sandbox](https://codesandbox.io/s/quirky-leavitt-i035v?file=/src/App.js) - scroll with the trackpad rapidly on the overlay half and you have different behaviour than when you scroll on the non-overlay half. So it is related to the element the mouse is over at the time of scrolling, maybe?

<img width="1536" alt="Screenshot 2020-04-20 at 11 21 07" src="https://user-images.githubusercontent.com/337712/80029369-983d9400-84de-11ea-80fa-f728a028bc0e.png">

He realised that scrolling over the overlay seems to [enable a different scroll mode](https://chromium-review.googlesource.com/c/chromium/src/+/1512536), as can be seen in the call trees here:

<img width="505" alt="with_overlay" src="https://user-images.githubusercontent.com/337712/80029508-c7ec9c00-84de-11ea-9492-866192ce29fa.png">

<img width="503" alt="without_overlay" src="https://user-images.githubusercontent.com/337712/80029530-cde27d00-84de-11ea-89d8-81cb21d53fc1.png">

Note that one is `gesturescrollupdate` and the other is just `scroll`.

He also pointed me to [this article about changes to the scrolling implementation in Chrome](https://mspoweruser.com/scrolling-on-chromium-browsers-might-soon-be-as-good-as-the-classic-edge-thanks-to-microsoft/), moving it off of the main thread.

**Comment by olehhusiev** [comment]
Hi @beauroberts, it's awesome thank you for this information it's very helpful and thank you @woollenhat for metrics. If I have some information I will send it to you and If you get another way to solving this problem please let me know.

**Comment by JavanPoirier** [comment]
Thanks @beauroberts. This was occurring only on Chrome on Mac, where list items would not show when swiping/scrolling fast and I was definitely lost as to why. Having tested a few different list library examples, this only occurred with `react-virtualized` and `react-window` out of those I tested.

**Comment by zhaoyao91** [comment]
We now know scroll with mouse on overlay will disable threaded scrolling feature, but didn't know why and how to fix it. Any good idea?
