### ISSUE TITLE
Use with large block/article elements (unknown height, unlimited container height)

### ISSUE THREAD

**Issue by kyleconrad** [bvaughn/react-window#457]
This is definitely a question vs issue/bug, but after doing a ton of research I'm having a hard time sorting it out so wanted to post it here.

Essentially, I have a series of case studies on my site - much more complex than a normal list, they have content blocks and images and all of that, and they can be unknown (and differing) heights. The container around them should fit to the height they're in, so it's only the main page scrolling, not the container. After doing Lighthouse audits, it recommended looking into react-window for virtualization because the case studies have a ton of DOM elements within them.

Does react-window (or a similar library) make sense here?
- Unknown list item height (preferably set on load/render)
- Unknown container height (set based on list item sizes)
- Items and container would resize with window resize, but content inside isn't changing after load

Really appreciate any help!

**Comment by LittlePony** [comment]
https://codesandbox.io/s/dynamic-size-of-react-window-list-items-64o9p

This solution is far from ideal but I use based on it

**Comment by adaschevici** [comment]
Hi @LittlePony 
I looked at the code sanbox provided and looks really neat.
Was wondering though, it seems that the `getSize`/`setSize` is out of order?

Specifically this snippet:
```javascript
  const getSize = React.useCallback(
    (index) => {
      console.log('Retrieving component size', sizeMap.current[index])
      return sizeMap.current[index] || 90
    },
    [sizeMap]
  )
```

Is always evaluated as 90 because the getSize is executed before the setSize. Have you found a way to get them to execute in the right order?
My guess is that they need to execute `setSize`, then `getSize` to account for the variable height.

**Comment by adaschevici** [comment]
disregard my last comment, i had removed the handleScroll which caused the issue.
This is a semi working version, but it still seems to be broken in that once it goes past the overscanCount it jumbles up the nodes and auto scrolls back
https://codesandbox.io/s/dynamic-size-of-react-window-list-items-xhkl6

**Comment by eyea** [comment]
> disregard my last comment, i had removed the handleScroll which caused the issue.
> This is a semi working version, but it still seems to be broken in that once it goes past the overscanCount it jumbles up the nodes and auto scrolls back
> https://codesandbox.io/s/dynamic-size-of-react-window-list-items-xhkl6

Thanks for your answer :)
