### ISSUE TITLE
Please support disable keyboard scrolling

### ISSUE THREAD

**Issue by cr4zyc4t** [bvaughn/react-window#458]
I'm building an application which pretty much like Excel, which means I need to be able to control arrow keys event but it look like react-window does not support it.
Please add it as an option.

**Comment by cr4zyc4t** [comment]
I figure it out, close issue

**Comment by sandeepkumar-vedam-by** [comment]
> I figure it out, close issue

@cr4zyc4t Could you please let us know the solution how we achieved it. I have similar use case
