### ISSUE TITLE
Is it possible to prevent re-rendering columns which are visible in viewport?

### ISSUE THREAD

**Issue by TautvydasDerzinskas** [bvaughn/react-window#459]
Hello,

Is it possible to prevent re-rendering columns and it's contents, when they are visible in viewport?
I understand rendering the items which newly appear in list, but the ones which are already visible, just change position - could't be prevented from re-rendering.

**Comment by Shub1427** [comment]
Please refer [here](https://github.com/bvaughn/react-window/issues/462) for discussion.

Or read the docs - https://react-window.now.sh/#/examples/list/memoized-list-items

**Comment by l695343920** [comment]
resetAfterIndex(i, false);
