### ISSUE TITLE
react-window-infinite-loader: InfiniteLoaderProps for typescript

### ISSUE THREAD

**Issue by WillSquire** [bvaughn/react-window#460]
Would be fab if `InfiniteLoaderProps` was exported for typescript. Just to avoid `InfiniteLoader['props']` :)

**Comment by piecyk** [comment]
Hmm @WillSquire you can always

```ts
type InfiniteLoaderProps = React.ComponentProps<typeof InfiniteLoader>
```

also typescript types are stored in `DefinitelyTyped` there you can submit PR with fix 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-window-infinite-loader

**Comment by WillSquire** [comment]
Thanks @piecyk, but I like `InfiniteLoader['props']` better :) .

```
type InfiniteLoaderProps = InfiniteLoader['props']
```

It would just be a bit nicer on the eyes doing 
```
import InfiniteLoader, { InfiniteLoaderProps } from 'react-window-infinite-loader'
```

In my opinion anyway.

**Comment by piecyk** [comment]
Ok 😄 just one problem with accessing `['props']` like this, it will not work with function components ( i know not valid in this case )

But yeah, types are not maintained by this library, you can create it at DefinitelyTyped 👍
