### ISSUE TITLE
Insane amount of re-renders when scrolling 1 items into viewport

### ISSUE THREAD

**Issue by jennyjkim95** [bvaughn/react-window#462]
I went into the codesandbox example here: https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/fixed-size-list-vertical

And updated the code to `console.log` the index whenever a row was rendered & noticed an alarming amount of re-renders in the browser console:

![rerenders](https://user-images.githubusercontent.com/20261332/80550457-04a01380-8975-11ea-876d-058cb89d736f.gif)

I noticed this while using `FixedSizeList` in my project as well. Am I missing something here or is there a bug w/ the list virtualization?

**Comment by Shub1427** [comment]
@jennyjkim95 Have you tried this?

https://react-window.now.sh/#/examples/list/memoized-list-items

**Comment by jennyjkim95** [comment]
@Shub1427 that seems to fix the mass re-rendering problem! I thought that would be baked into `FixedSizeList`. 

Thank you 💯

**Comment by Shub1427** [comment]
One more thing to note, u might have to use a custom `areEqual` implementation for `React.memo`, if the passed list items reference changes, but inner structure is still the same, so as to keep less re-renders

**Comment by jennyjkim95** [comment]
Thanks for the heads up! Will do
