### ISSUE TITLE
Which is better choice between react-window and react-virtualized on table component?

### ISSUE THREAD

**Issue by sungwoo91** [bvaughn/react-window#464]
Hello?

I'll convert my table component to **react-window** or **react-virtualized** component.
It has table header and table rows which have checkbox and text.

I think **react-window** prefer to simple list or grid data.
So is **react-virtualized** better for complex table components?

**Comment by colemars** [comment]
react-window provides the tools to create your own virtualized table component.

react-virtualized provides a table component.

**Comment by sungwoo91** [comment]
@colemars 
I undertstand. Thank you!!

**Comment by mgummelt** [comment]
To clarify, react-virtualized's table component is not an HTML table made up of tr's.  It's comprised of div's.
