### ISSUE TITLE
How to trigger an event on at end of the list element while scrolling down?

### ISSUE THREAD

**Issue by reynaldtaptalkio** [bvaughn/react-window#469]
How to detect the end of the list element on scroll event? Lets say i have array `[1,2,3,4,5,6,7,8,9,10]`, i need to detect if the scroll was reached the end of the list and return then value(in this case the value is 10)? Here is my snippet code: [https://codesandbox.io/s/react-window-detect-last-element-on-scrolling-down-oo99p](url)

**Comment by fpdutra** [comment]
I think you can achieve that by putting an event handler on the "onScroll" event.

https://codesandbox.io/s/react-window-detect-last-element-on-scrolling-down-jnz3t?file=/src/index.js

**Comment by jhonber** [comment]
Hello @reynaldtaptalkio,
you can achieve this using **onScroll** method and a little calculation taking in account the height, itemSize and the total number of elements:

```javascript
const onScroll = (props) => {
  const { scrollOffset } = props;
  const lastScroll = itemSize * itemCount - heigt;
  if (scrollOffset >= lastScroll) {
    console.log("End of list reached!");
  }
};
```
Full example: https://codesandbox.io/s/jovial-nightingale-jwv05
