### ISSUE TITLE
help: render list into multiple columns with flex or css grid

### ISSUE THREAD

**Issue by boxdox** [bvaughn/react-window#476]
Can anyone give me an example on how to do that? I tried passing in `display: grid` and `grid-template-column: repeat (2, 50%)` to innerElementType of a FixSizeList. But it doesn't seem to work. Thanks.

**Comment by albingroen** [comment]
In this issue you can see how I did to get grid working.
https://github.com/bvaughn/react-window/issues/486

**Comment by albingroen** [comment]
@boxdox Did you manage to create your grid, in that case can we maybe close this issue?

**Comment by boxdox** [comment]
@albingroen Hey, actually I couldn't get time to test this out. I will do it in coming weeks. Can we keep this open till then?

**Comment by albingroen** [comment]
@boxdox Sounds good, just ping me if you need any help :)
