### ISSUE TITLE
How to combine react-window with react-flip-move

### ISSUE THREAD

**Issue by shunmian** [bvaughn/react-window#477]
I'm trying to use  [react-flip-move](https://github.com/joshwcomeau/react-flip-move) to add animations for list items with `react-window` but cannot make it.

Please see [codeSandbox](https://8d7nq.csb.app/) for the sample code:
-  `this.renderFlipMove` is the function that only use `react-flip-move`, which works great.
- `this.renderReactWindow` is the function that only use `react-window`, which works great.
- `this.rednerFlipMoveWithReactWindow` is the function that use both `react-flip-move` and `react-window`, whose animation is not working after `remove` button is clicked.

**Comment by josecggarrido** [comment]
I have the same issue but I'm using `CSSTransition` and `TransitionGroup`, but also I have tried with other animated component and never works.

**Comment by shunmian** [comment]
I have made it work with [react-flip-toolkit](https://github.com/aholachek/react-flip-toolkit) instead of [react-flip-move](https://github.com/joshwcomeau/react-flip-move).
