### ISSUE TITLE
Does Infiniteloader work with react window FixedSizeGrid?

### ISSUE THREAD

**Issue by Julix91** [bvaughn/react-window#478]
I can't seem to get Infiniteloader to work with FixedSizeGrid - see [demo](https://codesandbox.io/s/infiniteloader-fork-with-grid-1sb8i?file=/src/App.js) (forked from the list version of it)

I'd leave this over at [Infiniteloader](https://github.com/bvaughn/react-window-infinite-loader) but it doesn't have an issue page...

```
Invalid onItemsRendered signature; please refer to InfiniteLoader documentation. 
    in Grid (at App.js:60)
    in InfiniteLoader (at App.js:54)
    in App 
```

**Comment by av1ctor** [comment]
I'm getting the same error as op.

**Comment by shahruz** [comment]
Had the same warning when using FixedSizeList + InfiniteLoader, and setting the dimensions dynamically. 
The props inside `onItemsRendered` are expected to be integers but started off as `NaN` in my implementation. I managed to silence the warning temporarily by doing this: 
```
onItemsRendered={props =>
    onItemsRendered({
      visibleStartIndex: props.visibleStartIndex || 0,
      visibleStopIndex: props.visibleStopIndex || 0,
      overscanStartIndex: props.overscanStartIndex || 0,
      overscanStopIndex: props.overscanStopIndex || 0,
    })
}
```
