### ISSUE TITLE
Flow error: Cannot use conditional as a computed property

### ISSUE THREAD

**Issue by jedwards1211** [bvaughn/react-window#482]
I'm seeing these errors, using Flow 0.123.0.  Also seeing them on the version of flow used by this repo if I paste the code into try flow.

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-window/src/createGridComponent.js:615:12

Cannot use conditional [1] as a computed property. Computed properties may only be primitive literal values, but
conditional [1] is a union. Can you add a literal type annotation to conditional [1]? See
https://flow.org/en/docs/types/literals/ for more information on literal types.

     612│       } else {
     613│         itemStyleCache[key] = style = {
     614│           position: 'absolute',
 [1] 615│           [direction === 'rtl' ? 'right' : 'left']: getColumnOffset(
     616│             this.props,
     617│             columnIndex,
     618│             this._instanceProps


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-window/src/createListComponent.js:471:12

Cannot use conditional [1] as a computed property. Computed properties may only be primitive literal values, but
conditional [1] is a union. Can you add a literal type annotation to conditional [1]? See
https://flow.org/en/docs/types/literals/ for more information on literal types.

     468│
     469│         itemStyleCache[index] = style = {
     470│           position: 'absolute',
 [1] 471│           [direction === 'rtl' ? 'right' : 'left']: isHorizontal ? offset : 0,
     472│           top: !isHorizontal ? offset : 0,
     473│           height: !isHorizontal ? size : '100%',
     474│           width: isHorizontal ? size : '100%',
```

**Comment by cstoddart** [comment]
@jedwards1211 I had this same error. Finally fixed it this morning by upgrading `flow-bin` to 0.129.0

**Comment by cstoddart** [comment]
> @jedwards1211 I had this same error. Finally fixed it this morning by upgrading `flow-bin` to 0.129.0

So it turns out this was only a temporary solution. I intended to put up a PR with a fix, but when I pulled down the repo I noticed the necessary changes were already there.

@bvaughn Can you make a release with the latest changes?

In the mean time, I can confirm that `"react-window": "bvaughn/react-window#master"` in my package.json is working well for me. 👍

**Comment by jedwards1211** [comment]
I also made a similar PR for other type challenges: https://github.com/bvaughn/react-window/pull/487

**Comment by jedwards1211** [comment]
> Can you make a release with the latest changes?

I advocate using [https://semantic-release.gitbook.io/semantic-release](semantic release) to automate publishing.

**Comment by cyspath** [comment]
I am using "react-window": "1.8.5" and it is still throwing me this Flow error. Could anyone please advise on how to fix?

```
Cannot use conditional [1] as a computed property. Computed properties may only be primitive literal values, but
conditional [1] is a union. Can you add a literal type annotation to conditional [1]? See
https://flow.org/en/docs/types/literals/ for more information on literal types. [invalid-computed-prop]

     612│       } else {
     613│         itemStyleCache[key] = style = {
     614│           position: 'absolute',
 [1] 615│           [direction === 'rtl' ? 'right' : 'left']: getColumnOffset(
     616│             this.props,
     617│             columnIndex,
     618│             this._instanceProps
```

**Comment by cstoddart** [comment]
This is a bug in the current release of react-window. However, the master branch has the bug fix in it. You can change  package.json to install from github instead of npm if you'd like to use what's in master.
`"react-window": "bvaughn/react-window#master"`

**Comment by jedwards1211** [comment]
@cstoddart as is the case for a lot of packages, `"react-window": "bvaughn/react-window#master"` won't work because it wouldn't contain the built code in `dist`, only the code in `src`.

**Comment by cstoddart** [comment]
Definitely not a solution I'm happy to suggest either way. I actually ended up pulling the code I needed from this repo and put it directly into my codebase. Kind of a pain but it's not a ton a code 🤷‍♂️
