### ISSUE TITLE
Website is out of date

### ISSUE THREAD

**Issue by jedwards1211** [bvaughn/react-window#488]
I noticed [this paragraph](https://github.com/bvaughn/react-window/blame/master/website/src/routes/api/FixedSizeList.js#L245) in the source doesn't appear on the published website.  The paragraph was committed a year ago so maybe something's wrong with deployment

**Comment by arminyahya** [comment]
I think doc is ok. you can see those two parameters (visibleStartIndex and visibleStopIndex) in path below:

https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js

@jedwards1211
