### ISSUE TITLE
Module '"./node_modules/@types/react"' has no exported member 'FunctionComponent'.

### ISSUE THREAD

**Issue by yaman-iotasol** [bvaughn/react-window#489]
Hi Team, 

I have recently added the library to my application. 
However there is an error @ line 15 ====> node_modules/@types/react-window/index.d.ts:
import {    FunctionComponent   } from "react";

FunctionComponent is not found in my already installed react-package.
I have already tried updating the react-package and @types/react-package.

Current used versions:
"react": "^16.4.0"
"@types/react": "^16.3.5"

"react-window": "^1.8.5"
"@types/react-window": "^1.8.2"

I can manually remove the import to get plugin run flawlessly, as I won't be using: 

innerElementType?: ReactElementType;
outerElementType?: ReactElementType;

Can you please suggest a way out.
Thanks in advance

**Comment by arminyahya** [comment]
I think you need to update @types/react.
package-lock.json says @types/react-window needs @types/react version: 16.9.52

![image](https://user-images.githubusercontent.com/35793921/96065265-2ea6ad00-0ea5-11eb-8bfb-13f18563e9f4.png)
@
