### ISSUE TITLE
Negative offset in VariableSizeList

### ISSUE THREAD

**Issue by danielbuechele** [bvaughn/react-window#49]
I am rendering a `VariableSizeList` component which has fewer items than its height and therefore is not scrollable at first, but more rows are added later which then requires scrolling. However, the rows added are not shown.

Here is what I think what happens:
- `VariableSizeList ` is rendered with a few items, which don't require scrolling
- I call `scrollToItem()` (this is called after adding rows because I want the list to be always scrolled to the bottom.
- the internal `scrollOffest` in state set to a negative value (I see this from react-devtools)
- new rows are added, but because of the negative value in `scrollOffset` they are assumed to be out of view and therefore not rendered.

I did some logging from the library and see `maxOffset` is negative here https://github.com/bvaughn/react-window/blob/master/src/VariableSizeList.js#L191
When manually setting the `scrollOffest` to 0 using react-devtools the missing rows are rendered.
Is there a case why the `scrollOffset` should ever be negative? Otherwise, I would suggest adding `Math.max(0, maxOffset)` there.

This might also affect `FixedSizeList` or the Grid components, I haven't tested with them.

**Comment by bvaughn** [comment]
I believe this was already reported and fixed via issue #45

Can you confirm if you're still seeing the problem?

**Comment by danielbuechele** [comment]
Confirming this is fixed as of version 1.1.2. I still was using 1.1.1.
