### ISSUE TITLE
Scrolling via arrow, page up, page down keys broken

### ISSUE THREAD

**Issue by Teddarific** [bvaughn/react-window#490]
I'm running into strange scrolling issue with `react-window`, and created this [sandbox to demonstrate](https://codesandbox.io/s/react-window-button-scroll-kop7d?file=/src/App.js).

When using the virtualized list from `react-window`, you'll see that if you click into the list to focus it, and then use the arrow keys to scroll, it'll halt after a little bit of scrolling. From there, the arrow keys are effectively rendered useless and you have to use the mouse / trackpad to be able to scroll again. It's consistently reproducible, and consistent in stopping after a little bit of scrolling.

It seems this isn't an issue in `react-virtualized` (see sandbox and swap the two implementations); you'll see that you can scroll fine with the arrow keys.

The same issue seems to happen with the page up / page down keys also.

 Also worth noting is that this doesn't actually seem to be an issue on Firefox. It at least happens on Chrome and Safari.

**Comment by Julio-Assis** [comment]
is there any workaround for this? For me the arrow scrolling doesn't work completely.

**Comment by viravir** [comment]
I think the solution to your problem was mentioned in a comment https://github.com/bvaughn/react-window/issues/46#issuecomment-416073707.
