### ISSUE TITLE
Is there a callback which returns the topmost (list item) index that is displayed in the view?

### ISSUE THREAD

**Issue by mtin79** [bvaughn/react-window#491]
I need to retrieve the element which is the topmost rendered element in the list in order to inform other components in the rendering tree about which element it is.
Not sure how this can be done with react-window.

Besides: Please don't drop horizontal scrollable lists!

**Comment by bjornuppeke** [comment]
I came here looking for an answer to the same question..

After further investigation I found out about the `onItemsRendered` prop.

From the docs:

> Called when the range of items rendered by the list changes.
> 
> This callback will only be called when item indices change. It will not be called if items are re-rendered for other reasons (e.g. a change in isScrolling or data params).

```
function onItemsRendered({
  overscanStartIndex,
  overscanStopIndex,
  visibleStartIndex,
  visibleStopIndex
}) {
  // All index params are numbers.
}
```
