### ISSUE TITLE
node_modules/@types/react-window has no exported member DynamicSizeList TypeScript Error.

### ISSUE THREAD

**Issue by StiliyanKushev** [bvaughn/react-window#493]
I cannot use the library functionality because typescript won't let me import the class I need. Can this be added please?

**Comment by mikeldking** [comment]
I think it's mentioned in #6 but `DynamicSizeList` is not quite ready for prime time. Should be available in v2? I couldn't get the component to work but if you just want the the typescript errors to go away, you can add this to your type declarations (e.x. `types.d.ts`)

```typescript
declare module "react-window" {
  export type DynamicSizeListProps = Omit<
    FixedSizeListProps,
    "itemSize" | "scrollToItem"
  >;
  export class DynamicSizeList extends Component<DynamicSizeListProps> {}
}

```
