### ISSUE TITLE
DynamicSizeList not calculating responsive height

### ISSUE THREAD

**Issue by WillSquire** [bvaughn/react-window#495]
When `DynamicSizeList` contains responsive components (using JS) inside of the row and these components affect the height of the list (i.e. `height: 1px;` or `margin-top: 8px;`), then scrolling to the top and bottom of the list causes it to 'flicker' to different scroll positions according to the height of the component (for each item, stacked). It looks like it snaps slightly higher and lower (looking a bit 'glitchy'). A guess might be the method used to measure the total scroll height isn't taking into consideration row height updates even though the row changes the height just fine (not overlapping with the next/previous row).

This drove me quite loopy for quite a while.. so I hope this helps someone else going through the pain.

**Comment by ArinCantCode** [comment]
@WillSquire I know its super old, but do you remember what you ended up doing?

**Comment by WillSquire** [comment]
@ArinCantCode I migrated to `react-virtuoso`.
