### ISSUE TITLE
How to render empty row? (noRowsRenderer in react-virtualized)

### ISSUE THREAD

**Issue by dizel852** [bvaughn/react-window#497]
Hi! I started using react-window recently. 
I wasn't able to find the appropriate prop in order to display an empty row if the itemCount is 0. 
I know react-virtualized has that one - noRowsRenderer prop. 
Any ideas?

**Comment by cmedinasoriano** [comment]
I know this is old but for anyone having the exact same question, I usually use the `innerElementType` for this similar to:
```
innerElementType={!rows.length && (
  () => <NoData />
)}
```
