### ISSUE TITLE
Footer prop?

### ISSUE THREAD

**Issue by superandrew213** [bvaughn/react-window#50]
I am trying to show a spinner at the end of the list when more data is getting fetched.

I can't seem to find a better way other than adding a footer component after inner container:

```jsx
<outer>
  <inner><item/>...</inner>
  <footer/>
</outer>
```

@bvaughn is this something that you would want to add?

**Comment by bvaughn** [comment]
That sounds like what I was trying to describe 😊

I didn't mean increase it just when loading. Glad you got it working!

**Comment by superandrew213** [comment]
Ah I see, you mean keep that extra row showing all the time. My row height is a bit big and there is just too much empty space when end is reached and there is no more data. 

Sounds like I'm too picky 😄

Thank you for the help! It's working great!

**Comment by superandrew213** [comment]
In my case I can't tell if there is more data or not. I can track if no new data is coming in then remove the row, however this still causes the grid to shift down when the row gets removed.

Is that what you mean? Maybe I'm missing something.

**Comment by bvaughn** [comment]
Can you show me what you're doing with a code sandbox or something

**Comment by superandrew213** [comment]
My current version is something close to this https://codesandbox.io/s/x3m8o9137w

Add back lines 35-37 to see behaviour with extra row. Scroll all the way to the end to see what I mean.

**Comment by bvaughn** [comment]
> In my case I can't tell if there is more data or not.

I think this might be key. Knowing if there's more data to be loaded seems important. Every API I've interacted with can at least tell you yes/no for this question– even if it can't tell you e.g. the total number of remote items.

> Add back lines 35-37 to see behaviour with extra row.

The extra row is shown regardless because of your `isLastRow` conditional.

Anyway, I was imagining something very similar: https://codesandbox.io/s/m72lm0yply
