### ISSUE TITLE
List glitches with Material UI's accordion component

### ISSUE THREAD

**Issue by vichuynh1** [bvaughn/react-window#501]
Each row in the virtualized list has an accordion in it. Scrolling to the bottom of the list causes the list to glitch and the last items in the list are flashing and repeatedly rendered. This is the link to my code. https://codesandbox.io/s/epic-snowflake-l0jce?file=/src/App.js

Thanks for the help!

**Comment by mastrix** [comment]
Hey @vichuynh1, It would be enough just to wrap **AccordionListItem** into **div** and apply a react-window **row** style to that **div** instead of **AccordionListItem**

```jsx
<div style={style}>
    <AccordionListItem
        key={item.id}
        data={item}
        itemsArray={itemsArray}
        setItemsArray={setItemsArray}
    />
</div>    
```

The other ways are much more time-consuming, search for customizing style object for MUI's accordion :)
https://material-ui.com/customization/globals/#css

**Comment by vichuynh1** [comment]
> Hey @vichuynh1, It would be enough just to wrap **AccordionListItem** into **div** and apply a react-window **row** style to that **div** instead of **AccordionListItem**
> 
> ```js-jsx
> <div style={style}>
>     <AccordionListItem
>         key={item.id}
>         data={item}
>         itemsArray={itemsArray}
>         setItemsArray={setItemsArray}
>     />
> </div>    
> ```
> 
> The other ways are much more time-consuming, search for customizing style object for MUI's accordion :)
> https://material-ui.com/customization/globals/#css

Doing this fixes the glitching issue but when you try to expand the list items they overlap with each other.

**Comment by mastrix** [comment]
@vichuynh1 , Oh sorry for such a long time to reply, I think you should wait for dynamic height for rows, there are some unofficial workarounds, some of them mentioned in issues in this repo, so you can type 'dynamic' and look :)
