### ISSUE TITLE
Question: Large lists with unknown sizes of items

### ISSUE THREAD

**Issue by AkalUstat** [bvaughn/react-window#503]
I know there is the VariableList component, but i have a list of 1000 items and their sizes arent known until the rows are mounted onto the dom  (unable to predict the size of each item). Since the variablelist still expects the itemSize prop, is there any way to get around this?

**Comment by hmtri1011** [comment]
![image](https://user-images.githubusercontent.com/16288424/90389172-4800c800-e0b3-11ea-9186-0d2ae662ae49.png)

I have created the VariableSizeList that supports items with dynamic and unpredictable size. With this component, you can easily set row item size when it mounted via `setItemSize` props.

However, when I pass the `style` props to the row item component, the height of it always fixed.
When I don't pass the `style` props to the row item component, it was rendered perfectly but the flash appears when scrolling

I have no idea to fix the flash without passing the `style` props, any help would be appreciated!

**Comment by dxsun97** [comment]
> ![image](https://user-images.githubusercontent.com/16288424/90389172-4800c800-e0b3-11ea-9186-0d2ae662ae49.png)
> 
> I have created the VariableSizeList that supports items with dynamic and unpredictable size. With this component, you can easily set row item size when it mounted via `setItemSize` props.
> 
> However, when I pass the `style` props to the row item component, the height of it always fixed.
> When I don't pass the `style` props to the row item component, it was rendered perfectly but the flash appears when scrolling
> 
> I have no idea to fix the flash without passing the `style` props, any help would be appreciated!

There is a height attribute inside the style object. You only need to overwrite or delete it. It should be noted that style is an unmodifiable object:
```
virtualizeStyle={{ ...style, height: 'auto' }}
```
