### ISSUE TITLE
Animated CSS transitions with VariableSizeList works in class components but not hooks?

### ISSUE THREAD

**Issue by Chunky-Chunk** [bvaughn/react-window#505]
I'm attempting to animate resizing of a `VariableSizeList` item renderer using CSS transitions in a functional components using hooks but the transition is ignored.

My code is based on a working example [Tweeted][2] by @bvaughn that uses class based components.

1. Brian's Code: **[CodeSandbox (Class Components)][3]**
2. My Code: **[CodeSandbox (Functional Components with Hooks)][4]**

Why does the animated transition not work using React Hooks?

  [1]: https://github.com/bvaughn/react-window
  [2]: https://twitter.com/brian_d_vaughn/status/1020376492130222081?lang=en
  [3]: https://codesandbox.io/s/n753oo58vj
  [4]: https://codesandbox.io/s/elated-moon-dw9o8

**Comment by ishumilova** [comment]
just move your `listItemRenderer` out of `App`

**Comment by bvaughn** [comment]
@ishumilova is correct. Move your item renderer outside of your `App` component. Otherwise, React will remove and re-add every item (and their children) each time `App` renders.

**Comment by skrat** [comment]
That would make a nice example if it would actually include the transitions. I tried and failed, I'm not sure it's even possible given that the core idea here is abolsutely positioning everything. Even if it would be possible, I think the user code for it would be ugly as hell. I think Flutter has it done right and even there it's kind of clunky.
