### ISSUE TITLE
Performance: Official example renders blank list when scrolling fast (Chromium)

### ISSUE THREAD

**Issue by ecklf** [bvaughn/react-window#515]
![ezgif-4-dbbcc89ee16e](https://user-images.githubusercontent.com/8146736/92738552-55d8fe80-f37c-11ea-85ca-a28d86483b64.gif)

**Comment by motykadaw** [comment]
Any progress on that?

**Comment by Vrq** [comment]
@bvaughn do you have any comments or directions how it could be approached?
