### ISSUE TITLE
Question: What happened to DynamicSizeList

### ISSUE THREAD

**Issue by Fazzacoot** [bvaughn/react-window#516]
I can see open issues and discussions that talk about this feature and can find reference to it at https://react-window-next.now.sh/#/examples/list/dynamic-size but the code sandbox link does not work.

Was this feature removed? If so is there a plan to implement a Dynamic sized list any time soon?

**Comment by anton6** [comment]
It looks like only alpha releases contain DynamicSizeList?

For example try 1.6.0-alpha.1, 1.4.0-alpha.1, 1.4.0-alpha.0 they seem to have it.

I think it might be something to do with the fact that DynamicSizeList lives on a separate branch called "issues/6".

More info here: https://github.com/bvaughn/react-window/issues/6

**Comment by Ceofy** [comment]
For whatever it's worth, 1.6.0-alpha.1 isn't working for me right now, but 1.4.0-alpha.1 is.

**Comment by impulse** [comment]
By the looks of it, this feature hasn't been touched in a while. Ended up implementing my own thing as an alternative. 

It is using `width` render prop from `AutoSizer` and expose a `setRowHeight` function via the Context API that will modify the array of row heights consumed by [VariableSizeList](https://react-window.now.sh/#/examples/list/variable-size).

**Comment by Fazzacoot** [comment]
> By the looks of it, this feature hasn't been touched in a while. Ended up implementing my own thing as an alternative.
> 
> I am using the `width` render prop from `AutoSizer` and expose a `setRowHeight` function via the Context API that will modify the array of row heights consumed by [VariableSizeList](https://react-window.now.sh/#/examples/list/variable-size).

Would you by any chance be able to share some code of how you achieved this? If the feature has not been touched in a while I would rather use something else for the moment.

**Comment by impulse** [comment]
> Would you by any chance be able to share some code of how you achieved this? If the feature has not been touched in a while I would rather use something else for the moment.

Just made a simple example during lunch break: [codesandbox](https://codesandbox.io/s/react-window-dynamic-list-xlfkq?file=/src/components/List.tsx). 

I just started using this library, so I am not sure if there are additional tweaks beside `overscanCount` and `estimatedItemSize` to improve render performance. Resizing can also be a bit laggy based on how many items you render. I think you may be able to get around this by debouncing the `setSize` calls. Maybe someone else knows how to improve this further.

**Comment by RuslanAsadov** [comment]
When will the functionality appear in react-window?

**Comment by qianjiachun** [comment]
> 该功能何时会出现在 react 窗口中？

hey, have you solved this problem? or any solution ? tks🙏

**Comment by timbrown5** [comment]
https://codesandbox.io/s/react-window-dynamic-list-forked-9eegb7?file=/src/App.tsx

> > Would you by any chance be able to share some code of how you achieved this? If the feature has not been touched in a while I would rather use something else for the moment.
> 
> Just made a simple example during lunch break: [codesandbox](https://codesandbox.io/s/react-window-dynamic-list-xlfkq?file=/src/components/List.tsx).
> 
> I just started using this library, so I am not sure if there are additional tweaks beside `overscanCount` and `estimatedItemSize` to improve render performance. Resizing can also be a bit laggy based on how many items you render. I think you may be able to get around this by debouncing the `setSize` calls. Maybe someone else knows how to improve this further.

If it helps anyone I've been playing with a fork to this to make List (slightly) more portable - `ListRow` and `itemData` get passed into the `List`:
https://codesandbox.io/s/react-window-dynamic-list-forked-9eegb7?file=/src/App.tsx
