### ISSUE TITLE
Header flickering issue in reacrt-window + infinite loader implementation with Material table.

### ISSUE THREAD

**Issue by DevAKS-Yara** [bvaughn/react-window#520]
I implemented a react-window (based on [#60](https://github.com/bvaughn/react-window/issues/60#issuecomment-588397239)) along with an infinite loader and Auto sizer with material UI. The table seems to be fulfilling the main objective but there are few issues with it - 

1. header is not sticking on the top in spite of having styles in place.
2. header is flashing/flickering while scrolling heavily towards up direction. [Steps to reproduce - scroll 50% down then do fast scroll up and observe the header movement ].

Here's the codesandbox example - [https://codesandbox.io/s/react-window-with-table-elements-forked-huti6?file=/src/index.tsx:514-542](https://codesandbox.io/s/react-window-with-table-elements-forked-huti6?file=/src/index.tsx:514-542)

Any help will be highly appreciated.

Thanks :)

**Comment by kaeland** [comment]
@DevAKS-Yara Hey, were you able to resolve the flickering issue? I'm seeing a similar problem in my end.

**Comment by pradeep-malviya-nrg** [comment]
Hi @DevAKS-Yara and @kaeland, were you guys able to resolve the issue?
