### ISSUE TITLE
Sticky headers don't stick in the sticky header demo

### ISSUE THREAD

**Issue by s4l4x** [bvaughn/react-window#522]
Here's a forked version which makes index 0, and 10 sticky, and adds a bit of color:
https://codesandbox.io/s/reverent-mayer-hpdzs

Here's the behavior I expect: 
https://codesandbox.io/s/sticky-headers-fmwki

Since the elements are positioned via top, I'm not sure how this is supposed to work.

**Comment by rohanbhangui** [comment]
is there any update on this?

**Comment by s4l4x** [comment]
Happy to take a deeper look, but I was looking at this example to try to understand. I'm sure there's some irony in here, but my confidence is low I'll be successful

**Comment by rohanbhangui** [comment]
@s4l4x i have been looking around too and to no avail. I am wondering is there a way to determine the scroll offset of certain rows and set the element to be sticky if it falls within certain ranges?

**Comment by rohanbhangui** [comment]
@s4l4x i was able to find a work around. It requires a bit of DOM manipulation to achieve. You can fake row element on top of the list, absolutely positioned and set it's clientWidth to match the client width of the list. Let me know if you want to see any example. I am sure there is a way to use refs to achieve this

**Comment by blissdev** [comment]
@rohanbhangui Do you happen to have any links or detail on your solution? Wanting to implement something similar.
