### ISSUE TITLE
Question: Can react-window / react-virtualized render without its own scrollable container?

### ISSUE THREAD

**Issue by denchen** [bvaughn/react-window#523]
Every example I've seen (and I'll admit, I did not go through _every_ example) has `react-window` being used in its own fixed-height container or full page. But can `react-window` help with a table that's inline with the rest of the page? In other words, the table takes whatever the full height would be within the page, but renders only the viewport portion. Basically, I really don't want a table to be contained within its own scrollable section.

**Comment by NoobTW** [comment]
Are you looking for something like [this](https://federicodirosa.github.io/react-window-scroller/)?

https://github.com/FedericoDiRosa/react-window-scroller

**Comment by batamire** [comment]
You can set `height={itemsCount * ITEM_HEIGHT}` and it will not need an inner scroll - just page scroll.

But this is what brought me here, as that fires `loadMoreItems(0, itemsCount)` which is wrong? Shouldn't it just pass "visibleRowCount" instead of `itemsCount` which can be rather large?

**Comment by patricklewis** [comment]
@batamire Were you ever able to find a workaround that would allow for `loadMoreItems` to be called properly when setting the height of the list to [item count * item height] in order to eliminate the scrollable container?
