### ISSUE TITLE
List blinking or going to blank when using with material UI

### ISSUE THREAD

**Issue by soma83** [bvaughn/react-window#525]
I will let this sandbox to talk by itself... how can I fix it?

https://codesandbox.io/s/laughing-bartik-ti05b?file=/index.js:0-817

The same goes if instead of <ListItem.../> I use a <div .../>

**Comment by Abdallatif** [comment]
You have to pass `style` to `ListItem`
https://codesandbox.io/s/wizardly-turing-wuhg4

**Comment by Andyliwr** [comment]
@Abdallatif I tried the demo you gave，problem still exists.

https://github.com/bvaughn/react-window/assets/12456160/cb72c9dc-d6dc-4806-af60-a1934d9144d1
