### ISSUE TITLE
useIsScrolling not working with react-window-scroller's style

### ISSUE THREAD

**Issue by xtrinch** [bvaughn/react-window#526]
I have prepared a code sandbox demonstrating the issue. The gist of it is, isScrolling does not work for me.

https://codesandbox.io/s/modest-darwin-x69wp

Notice that the isScrolling property is not working. If you remove the style property from the List, it starts to work.

What could I do to prevent the style property from disabling the isScrolling?

**Comment by tapayne88** [comment]
I _think_ the problem is react-window-scroller uses the `scrollTo` method which doesn't set the `isScrolling` state. There is an issue open for it (#447) but #195 explains why it's somewhat intentional
