### ISSUE TITLE
Image reload after each scroll in Grid

### ISSUE THREAD

**Issue by DoneDeal0** [bvaughn/react-window#535]
I have a virtualized-grid filled with images. It works well, but all images reload when I scroll back up or down. Is there a way to keep them displayed once for all? Such a behaviour is strange from a ux perspective. 

Here is a sandbox: https://codesandbox.io/s/grid-gutters-forked-j5roy?file=/index.js

And the code:
```javascript
import React from "react";
import ReactDOM from "react-dom";
import { FixedSizeGrid as Grid } from "react-window";
import AutoSizer from "react-virtualized-auto-sizer";
import "./styles.css";
import ax from "axios";
import Image from "./Image";

const COLUMN_WIDTH = 200;
const ROW_HEIGHT = 200;
const Card = ({ data, columnIndex, rowIndex, style }) => {
  const index = rowIndex * data.columnCount + columnIndex;
  const width = parseInt(style.width, 10);
  const leftOffset = (data.width - data.columnCount * width) / 2;
  return index < data.data.length ? (
    <div
      className={"GridItem"}
      style={{
        ...style,
        left: leftOffset + style.left,
        top: style.top
      }}
    >
      <Image
        src={data.data[index].download_url}
        width={width}
        height={width}
        alt="img"
      />
    </div>
  ) : null;
};

function Example() {
  const [data, setData] = React.useState([]);

  React.useEffect(() => {
    ax.get("https://picsum.photos/v2/list?page=2&limit=60")
      .then((res) => setData(res.data))
      .catch((_) => null);
  }, []);

  return (
    <div style={{ height: "100%", width: "100%" }}>
      <AutoSizer>
        {({ height, width }) => {
          const columnCount = Math.floor(width / COLUMN_WIDTH);
          const rowCount = Math.ceil(data.length / columnCount);
          return (
            <Grid
              className="Grid"
              rowCount={rowCount}
              columnCount={columnCount}
              height={height}
              rowHeight={ROW_HEIGHT}
              width={width}
              columnWidth={COLUMN_WIDTH}
              itemData={{ data, columnCount, width }}
            >
              {Card}
            </Grid>
          );
        }}
      </AutoSizer>
    </div>
  );
}

ReactDOM.render(<Example />, document.getElementById("root"));

```

**Comment by paulm17** [comment]
I've tried this lib, Masonary, React-Virtual and have found this behaviour across all of them.  Did you find a solution?

Thanks

**Comment by DoneDeal0** [comment]
@paulm17 no. I've just made a css grid with 25 images max, a native `loading="lazy"` attribute on `<img/>` and a pagination.

**Comment by fregante** [comment]
> all images reload when I scroll back up or down

That's at the basis of any "virtual scroll" component like `react-window`: elements are eliminated when not in view. The browser won't actually reload the images from the server though.

To make this issue less visible, you should restore/create the elements early so that once they reach the visible viewport they're fully ready. I don't know if react window offers control over this.

**Comment by dongnguyenvie** [comment]
I just readed some posts and get a way to optimize re-render and fetch image also:
here is a sanbox: https://codesandbox.io/s/admiring-wave-bk8iht?file=/index.js
