### ISSUE TITLE
Scroll Area

### ISSUE THREAD

**Issue by yoavShaked** [bvaughn/react-window#538]
I am rendering FixedSizeList component within a parent element that is already providing an overflow scrollbar.  

I want to prevent a double scrollbar in my page - now I have 2 scrollbars, one from FixedSizeList  and the other from the parent element of FixedSizeList .

Question: there is a way that FixedSizeList will use the parent element scrollbar and the only scrollbar that will be display is the parent element scrollbar?

**Comment by jimkaushal** [comment]
did you find the solution for the above questions

**Comment by Narcha** [comment]
I just ran into the same issue, and found a solution. I made a CodeSandbox demonstrating my approach, using a custom ScrollArea component from Mantine:
https://codesandbox.io/s/react-window-with-scrollarea-g9dg6d

**Comment by zqjimlove** [comment]
```

const GridOuter = React.forwardRef<
  HTMLDivElement,
  React.HTMLProps<HTMLDivElement>
>(function GridOuter(props, ref) {
  const { width, height } = props?.style ?? {};

  const viewportRef = useRef(null);

  useImperativeHandle(ref, () => viewportRef.current as any);

  return (
    <ScrollArea
      scrollbarSize={6}
      style={{ width, height }}
      viewportRef={viewportRef}
      onScrollPositionChange={(e) => {
        props.onScroll?.({
          currentTarget: viewportRef.current,
        } as any);
      }}
      viewportProps={{
        style: props.style,
      }}
    >
      {props.children}
    </ScrollArea>
  );
});
```
