### ISSUE TITLE
Adding padding to the list breaks the scrollToItem function

### ISSUE THREAD

**Issue by ValentinJS** [bvaughn/react-window#540]
According to the [FAQ in the README](https://github.com/bvaughn/react-window#can-i-add-padding-to-the-top-and-bottom-of-a-list ), you can add padding to the top and the bottom of the list like this : [codesandbox](https://codesandbox.io/s/react-window-list-padding-dg0pq)

However, doing so will break the scrollToItem function, offsetting its scroll position by the padding's value.

Iv'e updated the codesandbox to add the scrollToItem function :  [codesandbox fork](https://codesandbox.io/s/react-window-list-padding-forked-uwx09?file=/index.js)

**Comment by taghof** [comment]
Hey @ValentinJS I am currently facing the same issue, did you come up with a workaround?

**Comment by ValentinJS** [comment]
Hi @taghof, yes actually I rewrote react-window's getOffsetForIndexAndAlignment method to take the padding into account : 

Here's what I did : https://gist.github.com/ValentinJS/4f3738ed426cac183e8446c869b162dd

It's not perfect and you might need to adapt to fit your needs, but it'll give you an idea. Hope it can fix it for you :)

**Comment by taghof** [comment]
Hey @ValentinJS I managed to adapt your example to fit my needs, thanks a lot for helping me out :)
