### ISSUE TITLE
Due to absolutely position of rows, visible rows cannot extend to max row length

### ISSUE THREAD

**Issue by cyspath** [bvaughn/react-window#541]
For example, if the parent container width is set to 100px, and each absolutely positioned row item have variable length (eg 500px, 200px), is there any way to force all the children rows to have the length of background? 

This seems hard to achieve since all react-window rows are absolutely positioned. Since the parent container could not wrap the rows, it cannot force all children to extend to its width. See conceptual representation below:

Current:
[container]
[row1]
[row2 with longest text than others]
[row3 longer text than child1]

Target:
[container]
[row1 -----------------------------]
[row2 with longest text than others]
[row3 longer text than child1 ------]

* use case - vertical list, horizontal scrolling on longer items with alternating row background color

**Comment by sc-dtdl** [comment]
@cyspath - Were you able to get this resolved since i am facing a similar issue.
It seems that it expects column counts and their widths to be consistent.

Will really appreciate if you could update in case you were able to get a workaround.
