### ISSUE TITLE
`VariableSizeGrid` does not respond to `columnWidth` prop changes

### ISSUE THREAD

**Issue by kyleshevlin** [bvaughn/react-window#543]
I have a need for `VariableSizeGrid` to update cell styles when I change the `columnWidth` function (there's a chance this also affects `rowHeight`, but I have not explored that yet). Right now, the width remains the same despite props changing because of https://github.com/bvaughn/react-window/blob/d80bef25fe706d0c73fc801674c086f681811190/src/VariableSizeGrid.js#L484

I have a codesandbox demonstrating the issue here: https://codesandbox.io/s/sweet-ellis-0ot7p

So far, my workaround is to add a `key` to `VariableSizeGrid` and make the `key` change with the props that affect `columnWidth` to force an update.

**Comment by kyleshevlin** [comment]
Having looked through the codebase, it's clear that this same problem would occur with `VariableSizeGrid` if `rowHeight` or `direction` were changed. The style cache would not be busted. So this certainly isn't a bug, it's a deliberate choice.

One avenue I have explored in a fork is instead of using a memoized lazy cache, setting an instance property as the cache and setting all styles on mount and component updates. By doing it this way, we can create a method can be optionally passed the previous props and can determine if `columnWidth`, `direction`, or `rowHeight` changed in order to bust the cache.

The issues there are: 1) cache is eager, not lazy and 2) it breaks a number of tests. But doing it this way eliminates the need for the `shouldResetStyleCacheOnItemSizeChange` property entirely.

The other avenue would be to expose `shouldResetStyleCacheOnItemSizeChange` as a prop with different defaults per `Fixed*` and `Variable*` components. This at least gives the consumer the option of forcing the cache bust when they change item size.

I'm almost certain that the reason it wasn't designed this way is because the ethos of `react-window` is to not give the user that much control, but I'm struggling to reason why we wouldn't want to bust the style cache when props that would change the styles change. I can't figure that out.

As I made mention in my original post, I found a work around, _but_ that workaround is not sufficient for our needs. Forcing a remount of the grid by updating the key is too jarring. It leads to a flash of content as the grid is remounted.

I am more than willing to write and submit the code needed to fix this problem if a direction could be chosen. Please let me know if this work would be valuable to the project.

**Comment by guimello** [comment]
@kyleshevlin I had the same issue today using `VariableSizeList`. I have different row heights for different viewports so I needed to recompute the styles if the viewport breakpoint changes. I was using the `FixedSizeList`, but a change on our business logic required me to use the `VariableSizeList` (some items will have a different size now). Long story short I had the issue you described above because styles are not recomputed and it seems you are right about the cache thing.

As a workaround, I'm currently keeping a key on my list just like you described.

**Comment by kyleshevlin** [comment]
Yes, `VariableSizeList` also uses the same `shouldResetStyleCacheOnItemSizeChange` value, so the same problems would occur. Glad the workaround is sufficient for you.

**Comment by dave-trudes** [comment]
Having the same issue with `VariableSizeList`. Remounting the list with with a key is not sufficient for my use case. Maybe we can configure `shouldResetStyleCacheOnItemSizeChange` via a prop?

**Comment by kyleshevlin** [comment]
A colleague and I have found another workaround that makes use of the `resetAfter*` methods. Here's a sandbox with a solution for Grids: https://codesandbox.io/s/laughing-noyce-sigw9?file=/src/App.js

The gist is you track the props that will change the item's size, and for a reset of the cache based on those props. You can put that into a hook that returns a ref, such as I have in the sandbox above.

I still think that it's odd that I have to be responsible for forcing a cache update on something that seems like it should bust the cache by default. I'm not sure whether this issue should remain open based on the facts that:

- This is a deliberate design choice, and
- Clearly these `resetAfter*` methods are the intended work around

**Comment by kyleshevlin** [comment]
I'm closing this issue for lack of feedback (and I can't stand having lingering issues open 😅). Hopefully the sandbox here can help people who run into a similar issue in the future.

**Comment by jameskerr** [comment]
I'd think the cache should bust when the itemData prop changes.
