### ISSUE TITLE
Not all items are displayed for very long lists (starting with around 1 million items)

### ISSUE THREAD

**Issue by denzakharov** [bvaughn/react-window#551]
Not sure if the library was intended to be used with such long lists, but still seems worth mentioning. To reproduce, change item count for official example of `FixedSizeList` to 1 000 000: https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/fixed-size-list-vertical?file=/index.js

The last row that is displayed is `Row 958697`. Locally with different list item I hit a limit of `838860` records. Checked in Chrome and Safari, the result is the same.

**Comment by twall** [comment]
I don't think it even takes a million elements.  I'm using a variable size list, updating item heights as they render, and it only takes a few thousand to make them run off the end.

**Comment by vwjh37** [comment]
I guess it is caused by the height limitation of elements, I changed the itemSize to some small value, for example 25, then I can scroll whole 1,000,000 rows.
https://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties

**Comment by KeitelDOG** [comment]
I'm trying to imagine how much time a person would take to scroll 1M of items in a list without reading them. And if he read even a few of them. Is there use cases for this? Because usually I see search replace the need to scroll more than 1K - 10K.

**Comment by AXeL-dev** [comment]
Hello, any news for this issue?

**Comment by martijnthe** [comment]
I'm running into this problem as well.

**Comment by bvaughn** [comment]
This is not something the library will support. I supported it with react-virtualized (https://github.com/bvaughn/react-virtualized/pull/261) and I later regretted it.

Having thought about this use case a lot over the years, I don't think it makes for a good user experience.

Thanks for understanding.

**Comment by SmartArray** [comment]
@bvaughn I am interested in why did you regretted it? I guess it was a use case that just happened to rarely, right?

I am having a use case where I need this, so I am trying to switch back to react-virtualized. 
Also, about search functionality, I am considering to use server side search and jump to index X. 

Anyway, thanks for all your contributions!
