### ISSUE TITLE
How to reproduce React Virtualized scrolling behaviour in React Window?

### ISSUE THREAD

**Issue by DoneDeal0** [bvaughn/react-window#557]
I made a smooth scrolling list with React-spring and React-virtualized. In order to reduce my bundle size, I would like to switch to React-window. However, the animation doesn't work. 

Here is a sandbox with the two versions: how to fix the scroll?

https://codesandbox.io/s/muddy-star-kvhoq?file=/src/App.tsx

Thanks!

**Comment by BrianHung** [comment]
Have you tried accessing the internal `scrollToItem` api via `ref`?

**Comment by DoneDeal0** [comment]
Yes, it doesn't work. The key would be to force the scroll via react-spring, like in my example with react-virtualized.
