### ISSUE TITLE
Text contents color of FixedList is dimmed

### ISSUE THREAD

**Issue by mmussmann** [bvaughn/react-window#560]
Text content inside the FixedSizeList is dimmed. It's coming from will-change: 'transform'. 

https://github.com/bvaughn/react-window/blob/1f343d5d3c654912f43e656891e02181acf3eafb/src/createListComponent.js
https://github.com/bvaughn/react-window/blob/1f343d5d3c654912f43e656891e02181acf3eafb/src/createGridComponent.js

_Bottom line is the one dimmed by will-change css prop_
![image](https://user-images.githubusercontent.com/4272840/109140613-10a75e00-775d-11eb-8ce1-dc40e736e6d8.png)

As far as MDN states this is also not supposed to be a mainstay optimization but something added on the fly to handle an eminent change.
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

**NOTE:**
I tested this for the setup we use and could find no measurable performance change when scrolling a long list. (We dont have grids)

**Suggestion:**
Remove both or set to auto. 

I can make a PR for the change, but wont bother if there's reason I'm missing for it to be there in the general case.

**Comment by jnterry** [comment]
In chrome 90.x the `will-change: 'transform'` on `<FixedSizeList>` is causing the content to become blured in some situations

With `style` attribute set (the default):
![image](https://user-images.githubusercontent.com/2301058/121748677-494b2780-cb01-11eb-8ecf-afc84508642b.png)

Manually removed through devtools:
![image](https://user-images.githubusercontent.com/2301058/121748785-78619900-cb01-11eb-8c08-63ff0594706b.png)

As a work around, you can add `style={{ willChange: 'auto' }}` to your `<FixedSizeList>`

---------

Appears it was added 5 years ago to `react-virtualized` work around a chrome bug: https://github.com/bvaughn/react-virtualized/commit/2e308ed5ce81845974907f8c0aee405563914311#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR5

I've not noticed any issues with setting `willChange: 'auto'` on modern chrome versions, so it should prehaps be removed by default.

**Comment by metapzl** [comment]
Bumping this. This is causing lots of downstream issues when components integrate react-window.
I suggest using `will-change:scroll-position` instead as it is likely to follow the spirit of the initial change while not hurting subpixel rendering.
