### ISSUE TITLE
Infinite-loader issue: The scroll always comes at the top at the time of fetching new page.

### ISSUE THREAD

**Issue by hawaijar** [bvaughn/react-window#562]
Hello,

I am trying to integrate material-ui/Autocomplete component with React/Window/Infinite/Loader component. The goal is very simple - display a list of 1000 elements in the Autocomplete drop/down using Infinite/Loader component with a batch size of 30. The problem is that whenever a new batch (or page) is fetched and when the scrollbar hits the button, **the scroll always goes to the top**.

Here is the  [Code Sandbox link](https://codesandbox.io/s/material-demo-infinte-scroll-part51copy-6f71c)

Here is the problem statement captured in GIF 

![autocomplete-infinte-scroll](https://user-images.githubusercontent.com/26666919/110215485-16751000-7ed0-11eb-9a97-a4169f35673c.gif)

Not sure where the problem lies. I know this is not the case involving only infinite-loader component but also Material/UI's Autocomplete but I couldn't understand what am I missing here. 

Appreciate if you can see any idea/clue and share with me.

Note: My apology to post my concern here as I couldn't find Github/issues link for the React/Window/Infinite/Loader component. 

Thanks!

**Comment by hawaijar** [comment]
I'm closing it myself. Found similar issue and solution here https://codesandbox.io/s/material-demo-0fbyb

**Comment by hawaijar** [comment]
As there's no response, I'll have to close it myself. Good luck community!

**Comment by CaptainHoangLe** [comment]
I am also having the same problem as you. Can you explain specifically how to solve your problem. Thank you so much
