### ISSUE TITLE
TypeError: Cannot read property 'offset' of undefined when using scrollToItem

### ISSUE THREAD

**Issue by danielo515** [bvaughn/react-window#563]
When I use the method, scroll to Item I get the mentioned type error on the title. offset is tried to be read from itemMetadata, which happens to be undefined. My code is like this:

```js
  const list = useRef();
  list.current?.resetAfterIndex(refreshIdx);
  list.current?.scrollToItem({ rowIndex: refreshIdx, align: 'start' });
  return data.length ? (
    <Autosizer>
      {({ height, width }) => (
        <List>
          <VariableSizeList
            className={'home-sessions-list'}
            height={height}
            width={width}
            itemSize={itemSize}
            itemCount={data.length}
            itemData={data}
            ref={list}
          >
            {row}
          </VariableSizeList>
        </List>
      )}
    </Autosizer>
  ) : (
    <Loading  />
  );
```

**Comment by danielo515** [comment]
Ok, I found what the problem was.
I was looking at the docs of FixedSizeGrid, which takes an object rather than positional arguments, and I was just passing an object instead of positional arguments.
I think it will be a lot less confusing if you just use object arguments for all methods.

Cheers.

**Comment by darklightblue** [comment]
I had the same issue - in my case it wasn't because of the scroll but it happens if the item count changes, turns out that I was passing a decimal number on `itemCount`. Doing `Math.round` on the value fixed my issue.
