### ISSUE TITLE
Hardware/GPU acceleration

### ISSUE THREAD

**Issue by k4my4b** [bvaughn/react-window#564]
I was wondering if react-window uses transform/translate(2d/3d) to offset the elements which would be composited on the gpu layer

**Comment by joshwilsonvu** [comment]
Check https://github.com/bvaughn/react-window/blob/b0a470cc264e9100afcaa1b78ed59d88f7914ad4/src/createListComponent.js#L471, you'll see that it uses absolute positioning.

**Comment by shijiatongxue** [comment]
> I was wondering if react-window uses transform/translate(2d/3d) to offset the elements which would be composited on the gpu layer

+1

Maybe scroll items should have a wrapper, and then transform the wrapper. This won't cause layout and can use hardware acceleration。
