### ISSUE TITLE
Ability to add gap for FixedSizeGrid

### ISSUE THREAD

**Issue by thesobercoder** [bvaughn/react-window#565]
Provide an argument to have equal spacing around each cell items just like `gridGap`.

**Comment by Spring3** [comment]
I ended up calculating it myself.

```tsx
const renderCard = ({ columnIndex, rowIndex, style }: GridChildComponentProps) => {
    const styles = {
      ...style,
      left: columnIndex === 0 ? style.left : Number(style.left) + columnIndex * CELL_GAP,
      right: columnIndex === columnCount ? style.right : Number(style.right) + columnIndex * CELL_GAP,
      top: rowIndex === 0 ? style.top : Number(style.top) + rowIndex * CELL_GAP,
    }

    return <YourComponent ... style={styles} />
}


<FixedSizeGrid>{renderCard}</FixedSizeGrid>
```

**Comment by alolis** [comment]
> I ended up calculating it myself.
> 
> ```tsx
> const renderCard = ({ columnIndex, rowIndex, style }: GridChildComponentProps) => {
>     const styles = {
>       ...style,
>       left: columnIndex === 0 ? style.left : Number(style.left) + columnIndex * CELL_GAP,
>       right: columnIndex === columnCount ? style.right : Number(style.right) + columnIndex * CELL_GAP,
>       top: rowIndex === 0 ? style.top : Number(style.top) + rowIndex * CELL_GAP,
>     }
> 
>     return <YourComponent ... style={styles} />
> }
> 
> 
> return (
>    <FixedSizeGrid>{renderCard}</FixedSizeGrid>
> );
> ```

The `style.right` does not seem correct to me. `columnIndex` will never be equal with `columnCount` since the first one is zero based or perhaps I am missing something. In my case I do not need it at all anyway :)

**Comment by Jamzy01** [comment]
> I ended up calculating it myself.
> 
> ```tsx
> const renderCard = ({ columnIndex, rowIndex, style }: GridChildComponentProps) => {
>     const styles = {
>       ...style,
>       left: columnIndex === 0 ? style.left : Number(style.left) + columnIndex * CELL_GAP,
>       right: columnIndex === columnCount ? style.right : Number(style.right) + columnIndex * CELL_GAP,
>       top: rowIndex === 0 ? style.top : Number(style.top) + rowIndex * CELL_GAP,
>     }
> 
>     return <YourComponent ... style={styles} />
> }
> 
> 
> return (
>    <FixedSizeGrid>{renderCard}</FixedSizeGrid>
> );
> ```

I have tried the same effect and it works, although I have found that changing the styles manually causes issues with react window and makes the element culling no longer function properly. It would be nice if there was an inbuilt feature for this.

**Comment by gursidak** [comment]
I adopted a technique, I have wrapped the cellContent in  a div and provided the width and height to div such that
