### ISSUE TITLE
Add a prop for initialScrollItemIndex

### ISSUE THREAD

**Issue by ZengLawrence** [bvaughn/react-window#569]
Instead of using 'initialScrollOffset', which caller has to calculate the offset, pass in a new prop 'initialScrollItemIndex' to scroll to a specific item.  Can this be implemented in react-window?

**Comment by itdhsc** [comment]
If you know the defaultHeight of each row it should not be a problem. 
But if you use a VariableSize* its is not as easy as with FixedSize* components.

We have the latter problem :)
