### ISSUE TITLE
It doesn't work with hooks and async await

### ISSUE THREAD

**Issue by tar-aldev** [bvaughn/react-window#571]
In your example for infinite scroll you have setState wrapped in setTimeout. (I am referencing this codesandbox https://codesandbox.io/s/x70ly749rq)
 If rewrite this into more "real" mock, list will not load more than once.
In your example it is loaded twice at the beginning. I cannot seem to find anything about this in the docs.
Here is a codesandbox example that can clearly show the issue:
https://codesandbox.io/s/sleepy-http-80b97?file=/src/App.js

Am I missing something?

**Comment by Cobertos** [comment]
I also wasn't able to implement a list where every item is async from this library. I got stuck at the part where I needed to specify `itemKey` but I can't return a key until the promise resolves (at which point I add the returned item to a plain list to try to get `FixedSizeList` to ingest it).

My use case is admittedly niche, but it would've been nice to know going in that this really didnt work.
