### ISSUE TITLE
There seems to be a memory leak

### ISSUE THREAD

**Issue by adolfheir** [bvaughn/react-window#579]
I found a memory leak when I was using the virtual list. After debugging, I found that the item function does not have GC. I cannot find the reason. I suspect there is a reference inside the component that has not been removed. Can you help me?

![image](https://user-images.githubusercontent.com/26828649/123372350-fb7cf780-d5b5-11eb-9229-9cad2752da64.png)

You can see that after the component is uninstalled, there is still a reference to the item in the WeakMap, and there is no reference to the component that does not use virtual list

codesandbox：https://codesandbox.io/s/amazing-margulis-pvlny?file=/src/App.js

**Comment by M-ZubairAhmed** [comment]
Hey @bvaughn is there is a reason this is closed, i dont see a PR related to its closure. :)

**Comment by MFatihY** [comment]
@bvaughn You closed it as completed but I'm encountering the same issue in our project, even on v1.8.11.
