### ISSUE TITLE
Compiled code seems broken

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-window#58]
Calling e.g. `ref.current.resetAfterColumnIndex()` on `VariableSizeGrid` seems to trigger a runtime error.

Resize the window of this Code Sandbox to repro: https://codesandbox.io/s/5ywr9ro7nn

It looks like the `this` context is getting messed up somehow. (`this` is valid but `_this` is undefined.)

**Comment by TrySound** [comment]
This doesn't look like a bug in compiled code. I see you use `this` inside of `initInstanceProps` which is not called with any instance. Arrow functions of course doesn't have own context.

**Comment by TrySound** [comment]
Use `instance` instead of `this`.

**Comment by bvaughn** [comment]
Didn't have time to dig into the underlying cause, just noted that the compiled code was referencing the wrong thing and wanted to leave a note for myself to fix later (or you if you beat me to it 😉)

**Comment by TrySound** [comment]
Seems like you didn't covered this case with tests. This code doesn't look correct.
https://github.com/bvaughn/react-window/blob/master/src/VariableSizeGrid.js#L406

**Comment by TrySound** [comment]
I just passed by. Didn't have this issue yet.

**Comment by bvaughn** [comment]
Fixed via 35f99db
