### ISSUE TITLE
White space when scrolling

### ISSUE THREAD

**Issue by fyodore82** [bvaughn/react-window#581]
React-window is amazing library.

But as pointed in many issues, when scrolling fast, user will wee whitespace.

https://user-images.githubusercontent.com/29746153/123578352-ff5c8400-d818-11eb-9638-73931f498eb9.mp4

Cause of this is clear. React Window is rendering items while user is scrolling. And it takes time to render. So if user scrolls fast, items will not have time to render and user will see white space.
Items should contain as little html elements as possible to be rendered fast.
But all these will not eliminate whitespace completely.

Alternative approach can be to scroll only when items have been rendered (user moves scroll thumb -> items rendered -> scroll position changed). Drawback of this approach is that scroll will not be smooth, but will jump in small steps. But user will not see white space at all

https://user-images.githubusercontent.com/29746153/123578836-046e0300-d81a-11eb-8b2b-89b394a27326.mp4

I have implemented possible solution https://codesandbox.io/s/virtualscroll-kn9ic

The idea behind this implementation:

- Custom inner element is provided (`VirtualScrollInner`). It renders two `div`'s: first `div` have `sticky` position and hold children. Second `div` is React Window default inner element which has height large enough to show scroll bar
- Custom outer element is provided (`VirtualScrollOuter`). It does not bind to React Window's `onScroll` handler but use custom `onScroll`
- And all magic is happening in custom `VitualScrollList` component which is wrapper around `FixedSizedList`. It provide custom `onScroll` event handler to outer element. When scroll event is fired, it saves new scroll top position and calls `FixedSizedList`'s `scrollTo` method. Until list items are rendered (which is detected by `onScroll` callback of `FixedSizedList`) for all new scroll events, `scrollTop` is saved and not real scroll happens. 
- Custom `ListItemWrapper` which adjust items positions on sticky inner `div`

I can further elaborate on this approach.

My idea is to include such rendering style as an option for React Windows scrolling behavior

I will appreciate any comments/suggestions

-

**Comment by nick-keller** [comment]
Have you looked into the `useIsScrolling` option? https://react-window.vercel.app/#/examples/list/scrolling-indicators

It allows you to render a lightweight version of your elements while scrolling, I find it a much better alternative than low FPS scrolling in term of user experience :)

**Comment by fyodore82** [comment]
`useIsScrolling` is not solving the problem completely. If scrolling fast, whitespace is still present.

Synchronizing scroll with rendering should be considered as an options among `useIsScrolling`, memorizing row, etc. So users can choose which option is better for them.

There is also interesting example from material-ui - [XGrid](https://material-ui.com/components/data-grid/#commercial-version). They presented commercial version, which uses virtual scrolling (not sure, if it react-window with enhancements or not). But they synchronize scroll with rendering so you'll not see white space when scrolling fast. But scroll is 'jumping'.

**Comment by tianzhich** [comment]
> There is also interesting example from material-ui - XGrid. They presented commercial version, which uses virtual scrolling (not sure, if it react-window with enhancements or not). But they synchronize scroll with rendering so you'll not see white space when scrolling fast. But scroll is 'jumping'.

I still see the white space in this example. Is it changed?

**Comment by fonty422** [comment]
I agree that the 'useIsScrolling' isn't really an ideal solution to this. `react-virtuoso` appears to not have either the issue of white space while scrolling (and it does it without jitter) and also manages to keep the scrollbar nicely attached to the list. But I can't figure out how to attach it to the MUI Autocomplete instead of `react-window`

**Comment by Arslan26** [comment]
> React-window is amazing library.
> 
> But as pointed in many issues, when scrolling fast, user will wee whitespace.
> 
> Cause of this is clear. React Window is rendering items while user is scrolling. And it takes time to render. So if user scrolls fast, items will not have time to render and user will see white space. Items should contain as little html elements as possible to be rendered fast. But all these will not eliminate whitespace completely.
> 
> Alternative approach can be to scroll only when items have been rendered (user moves scroll thumb -> items rendered -> scroll position changed). Drawback of this approach is that scroll will not be smooth, but will jump in small steps. But user will not see white space at all
> 
> I have implemented possible solution https://codesandbox.io/s/virtualscroll-kn9ic
> 
> The idea behind this implementation:
> 
> * Custom inner element is provided (`VirtualScrollInner`). It renders two `div`'s: first `div` have `sticky` position and hold children. Second `div` is React Window default inner element which has height large enough to show scroll bar
> * Custom outer element is provided (`VirtualScrollOuter`). It does not bind to React Window's `onScroll` handler but use custom `onScroll`
> * And all magic is happening in custom `VitualScrollList` component which is wrapper around `FixedSizedList`. It provide custom `onScroll` event handler to outer element. When scroll event is fired, it saves new scroll top position and calls `FixedSizedList`'s `scrollTo` method. Until list items are rendered (which is detected by `onScroll` callback of `FixedSizedList`) for all new scroll events, `scrollTop` is saved and not real scroll happens.
> * Custom `ListItemWrapper` which adjust items positions on sticky inner `div`
> 
> I can further elaborate on this approach.
> 
> My idea is to include such rendering style as an option for React Windows scrolling behavior
> 
> I will appreciate any comments/suggestions

Great! this really works. This solution is also valid for [react-vtree](https://www.npmjs.com/package/react-vtree) version 3.0.0-beta.3 which is built on top of react-window.

**Comment by adarshares** [comment]
> React-window is amazing library.
> 
> But as pointed in many issues, when scrolling fast, user will wee whitespace.
> 
>  DefaultVirtualScroll.mp4 
> Cause of this is clear. React Window is rendering items while user is scrolling. And it takes time to render. So if user scrolls fast, items will not have time to render and user will see white space. Items should contain as little html elements as possible to be rendered fast. But all these will not eliminate whitespace completely.
> 
> Alternative approach can be to scroll only when items have been rendered (user moves scroll thumb -> items rendered -> scroll position changed). Drawback of this approach is that scroll will not be smooth, but will jump in small steps. But user will not see white space at all
> 
>  SyncVirtualScroll.mp4 
> I have implemented possible solution https://codesandbox.io/s/virtualscroll-kn9ic
> 
> The idea behind this implementation:
> 
> * Custom inner element is provided (`VirtualScrollInner`). It renders two `div`'s: first `div` have `sticky` position and hold children. Second `div` is React Window default inner element which has height large enough to show scroll bar
> * Custom outer element is provided (`VirtualScrollOuter`). It does not bind to React Window's `onScroll` handler but use custom `onScroll`
> * And all magic is happening in custom `VitualScrollList` component which is wrapper around `FixedSizedList`. It provide custom `onScroll` event handler to outer element. When scroll event is fired, it saves new scroll top position and calls `FixedSizedList`'s `scrollTo` method. Until list items are rendered (which is detected by `onScroll` callback of `FixedSizedList`) for all new scroll events, `scrollTop` is saved and not real scroll happens.
> * Custom `ListItemWrapper` which adjust items positions on sticky inner `div`
> 
> I can further elaborate on this approach.
> 
> My idea is to include such rendering style as an option for React Windows scrolling behavior
> 
> I will appreciate any comments/suggestions

I was trying to implement the same with variable size grid but idk why the handleOnScroll was not getting called?

**Comment by bhavinzwt** [comment]
@adarshares we are facing this same react-virtuoso. Is there any example to fix this type of issue in react-virtuoso.?

**Comment by adarshares** [comment]
I don't know how to do it in react virtuoso, although finally in the project I ended up using react window with caching, you can check the code of react virtualized, cache is implemented there one can implement cache inside the code of react window and use it. It produced much better results, white spaces were not as frequent as it happened normally.

**Comment by adarshares** [comment]
> @adarshares we are facing this same issue in react-virtuoso. Is there any example to fix this type of issue in react-virtuoso.?

I don't know how to do it in react virtuoso, although finally in the project I ended up using react window with caching, you can check the code of react virtualized, cache is implemented there one can implement cache inside the code of react window and use it. It produced much better results, white spaces were not as frequent as it happened normally.
