### ISSUE TITLE
`scrollToItem` does not work correctly with sticky items

### ISSUE THREAD

**Issue by jonsmithers** [bvaughn/react-window#586]
When I follow the readme's example on sticky items, the `scrollToItem` fails to scroll items into view when scrolling up. The method does not account for the shrunken viewport caused by the sticky items.

https://codesandbox.io/s/great-ganguly-1821j

In the above sandbox, the `scroll to row 2` button should cause `Row 2` to be scrolled into view, but the table only scrolls up enough for `Row 4` to be visible.

Maybe this is intended behavior and the only fix is for us to implement our own `scrollToItem` which accounts for the sticky items' offset.

**Comment by codebycarlos** [comment]
Having the same issue

**Comment by Dodie324** [comment]
Not surprised. Sticky rows doesn't even seem to work in general. Has anyone figured out a better, working solution for sticky rows?
