### ISSUE TITLE
How to know itemSize before mounting?

### ISSUE THREAD

**Issue by mimiqkz** [bvaughn/react-window#590]
As I know that `VariableSizeList` needs to have itemSize as an input. However , if the component being dynamically generated ([for example](https://stackoverflow.com/questions/68593473/how-to-get-element-height-and-width-from-reactnode)), then there is no way the itemSize is known before mounting. So how can you know the itemSize before hand at all?

**Comment by codingedgar** [comment]
you have the index, if, with the index you cannot deterministically know the items data, I think you could render, measure and update (keeping the items last known size in a memorized variable somewhere).

I honestly just went with https://github.com/petyosi/react-virtuoso for those cases (sorry if it is not cool of me to recommend another library)

**Comment by DWboutin** [comment]
@codingedgar Thank you, this lib looks more maintained
