### ISSUE TITLE
Append huge number of rows dynamically

### ISSUE THREAD

**Issue by KillerKiwiJuice** [bvaughn/react-window#597]
I have an application that receives almost 8000 messages per second via websocket. I need a window to display each message that comes in through the websocket in real time. Is there a performant way of accomplishing this via react-window? If not, I'm kindly wondering if there is another similar library to do this task.

**Comment by captainkovalsky** [comment]
@KillerKiwiJuice what's the issue do you have exactly?

**Comment by KillerKiwiJuice** [comment]
> @KillerKiwiJuice what's the issue do you have exactly?

I went with Ag-Grid instead and use their transaction update feature.
