### ISSUE TITLE
Padding top doesn't work properly for big padding size

### ISSUE THREAD

**Issue by natcohen** [bvaughn/react-window#601]
After playing a bit with the official example: https://codesandbox.io/s/react-window-list-padding-dg0pq adding a padding size of `150` or bigger makes it buggy. Simply change the `PADDING_SIZE` to `150` to reproduce the bug.

**Comment by dev-tom-0108** [comment]
Could you use inner style

**Comment by linecept** [comment]
I'm having the same issue. Any thoughts on this anyone?
