### ISSUE TITLE
[Feature request] Support customize getEstimatedTotalWidth

### ISSUE THREAD

**Issue by jameswhf** [bvaughn/react-window#605]
Here is a variable size grid we met: every column's width and every row's height is predefined.  
For a grid with many columns, when user drag the scrollbar, the scrollbar's size and position jump until all columns show up, this is weird.  The reason is react-window try to estimate unmounted columns with **getEstimatedTotalWidth**, this function is defined in VariableSizeGrid and can't be changed or customized. 
 Customized getEstimatedTotalWidth can support upper scenario and makes react-window more powerful

**Comment by tanin47** [comment]
I would like this for both width and height. I made a hacky version that supports this but I'm not sure if it is the right design
