### ISSUE TITLE
Use InfiniteLoader + AutoSizer + FixedSizeGrid all together

### ISSUE THREAD

**Issue by justinasfour04** [bvaughn/react-window#609]
I'm trying to do the following but nothing seems to render and I can't figure out why
```typescript
return (
    <InfiniteLoader
      ref={listRef}
      isItemLoaded={isItemLoaded}
      itemCount={itemCount}
      loadMoreItems={loadMoreItems}
    >
      {
        ({ ref, onItemsRendered }) => (
          <AutoSizer>
            {
              ({ height, width }) => (
                <Grid
                  ref={ref}
                  className="Grid"
                  columnCount={Math.floor(width / 200)}
                  columnWidth={200}
                  height={height}
                  width={width}
                  rowCount={rowCount}
                  rowHeight={200}
                  onItemsRendered={itemRenderer(onItemsRendered)}
                >
                  {
                    ({ columnIndex, rowIndex, style }) => (
                      <Cell
                        columnIndex={columnIndex}
                        rowIndex={rowIndex}
                        style={style}
                        columnCount={columnCount}
                        items={items}
                        isItemLoaded={isItemLoaded}
                      />
                    )
                  }
                </Grid>
              )
            }
          </AutoSizer>
        )
      }
    </InfiniteLoader>
  );
  ```
  
  Can these three elements be used together?

**Comment by xh3b4sd** [comment]
Hey, I think I ran into the same problem you did. I figured you have to render within the dom directly. Returning the component doesn't work for some reason. I don't know anything about react so I just fiddled a bit until it worked. The items appear to be loaded and removed when scrolling. Somebody please give feedback if this approach is wrong or could be improved by any means. Hope the snipped below helps. 

```js
const Cell = ({ columnIndex, rowIndex, style }) => (
  < div style={style} >
    // cour content here
  </div >
);

const Example = () => (
  <AutoSizer>
    {({ height, width }) => (
      <InfiniteLoader
        isItemLoaded={isItemLoaded}
        itemCount={1000}
        loadMoreItems={loadMoreItems}
      >
        {({ onItemsRendered, ref }) => (
          <Grid
            className="Grid"
            columnCount={3}
            columnWidth={width / 3}
            height={height}
            onItemsRendered={onItemsRendered}
            ref={ref}
            rowCount={60}
            rowHeight={width / 3}
            width={width}
          >
            {Cell}
          </Grid>
        )}
      </InfiniteLoader>
    )}
  </AutoSizer>
);

render(<Example />, document.getElementById("root"));
```

**Comment by justinasfour04** [comment]
I figured out what the issue was, I need to put all that in a div with height and width. It wasn't rendering anything because height was 0px

**Comment by umagon** [comment]
> I'm trying to do the following but nothing seems to render and I can't figure out why
> 
> ```ts
> return (
>     <InfiniteLoader
>       ref={listRef}
>       isItemLoaded={isItemLoaded}
>       itemCount={itemCount}
>       loadMoreItems={loadMoreItems}
>     >
>       {
>         ({ ref, onItemsRendered }) => (
>           <AutoSizer>
>             {
>               ({ height, width }) => (
>                 <Grid
>                   ref={ref}
>                   className="Grid"
>                   columnCount={Math.floor(width / 200)}
>                   columnWidth={200}
>                   height={height}
>                   width={width}
>                   rowCount={rowCount}
>                   rowHeight={200}
>                   onItemsRendered={itemRenderer(onItemsRendered)}
>                 >
>                   {
>                     ({ columnIndex, rowIndex, style }) => (
>                       <Cell
>                         columnIndex={columnIndex}
>                         rowIndex={rowIndex}
>                         style={style}
>                         columnCount={columnCount}
>                         items={items}
>                         isItemLoaded={isItemLoaded}
>                       />
>                     )
>                   }
>                 </Grid>
>               )
>             }
>           </AutoSizer>
>         )
>       }
>     </InfiniteLoader>
>   );
> ```
> 
> Can these three elements be used together?

Mine is not calling `loadMoreItems`. It complaints about `onItemsRendered` type not being compatible with `GridOnItemsRendered`. The one that comes from `InfiniteLoader` is of type `GridOnItemsRendered`. What's that `itemRenderer` function you've got there?

**Comment by ervin-sungkono** [comment]
Hello, just in case anyone is looking for how to use grid with infinite loader, here is my setup:

```js
<AutoSizer>
      {({ width, height }) => (
        <InfiniteLoader
          itemCount={hasNextPage ? items.length + 1 : items.length}
          loadMoreItems={loadMore}
          isItemLoaded={isItemLoaded}
        >
           {({ onItemsRendered, ref }) => (
              <FixedSizeGrid
                rowHeight={180}
                rowCount={items.length / COLUMN_CNT}
                columnWidth={width / COLUMN_CNT}
                columnCount={COLUMN_CNT}
                height={height}
                width={width}
                itemData={items}
                style={{willChange: 'initial'}}
                ref={ref}
                onItemsRendered={(props) => onItemsRendered({
                  overscanStartIndex: props.overscanRowStartIndex * COLUMN_CNT + props.overscanColumnStartIndex, 
                  overscanStopIndex: props.overscanRowStopIndex * COLUMN_CNT + props.overscanColumnStopIndex, 
                  visibleStartIndex: props.visibleRowStartIndex * COLUMN_CNT + props.visibleColumnStartIndex, 
                  visibleStopIndex: props.visibleRowStopIndex * COLUMN_CNT + props.visibleColumnStopIndex
                })}
              >
                {MemoizedRow}
              </FixedSizeGrid>
           )}
        </InfiniteLoader>
      )}
</AutoSizer>
```

`COLUMN_CNT` here is a fixed variable for amount of column
