### ISSUE TITLE
No items displayed while scrolling also scroll bar keeps moving

### ISSUE THREAD

**Issue by samundrak** [bvaughn/react-window#61]
I am facing a problem like No items displayed while scrolling also scroll bar keeps moving,
I just followed the guide from the site, other lib i used are `antd` and `styled-components`;
Here is codesandbox example: https://codesandbox.io/s/7579z7om6

**Comment by bvaughn** [comment]
You're not using the `style` parameter.

https://codesandbox.io/s/j7xkvk8x7y
