### ISSUE TITLE
use autosizer + infinitescroll does not trigger loadMoreItem

### ISSUE THREAD

**Issue by iamtmoe** [bvaughn/react-window#610]
![image](https://user-images.githubusercontent.com/41809433/143667699-f3647330-f9ed-4b8c-bd11-a395fb7619c3.png)
when use autosize as outer component of infiniteLoader, react-window-infinite-loader seems to only works when itemCount * itemSize  great enough(maybe greater than 2000px?), anyone know reason? i issue here because  react-window-infinite-loader cannot new issue

**Comment by aritzmetal** [comment]
You need to put a div between the Autosizer and the InfiniteLoader component. At least that worked for me.

**Comment by iamtmoe** [comment]
> You need to put a div between the Autosizer and the InfiniteLoader component. At least that worked for me.

Thanks for your reply. I haven't coded for a long time, so haven't reply until now. I test again and find that I misunderstood the meaning of itemCount, I set it to the number of current loaded items, so the method `LoadMoreItems` is not triggered. It actually stand for all items, including unloaded items. And It has nothing to do with `AutoSizer`. I change my code as follows, it works for me at least.
```react
const [itemCount, setItemCount] = useState(10000)
const loadNextPage = () => {
    console.log('loadNextPage')
    if(!hasNext) return
    setIsNextPageLoading(true)
    let query = {cursor: cursor || 0, take: 10}
    return request({path: '/accountHistories', query}).then(res => {
      if(res.code == 0) {
        setAccountHistories(accountHistories.concat(res.accountHistories))
        if(res.accountHistories.length < 10) {
          setHasNext(false)
        }
        if(res.accountHistories.length > 0) {
          setCursor(res.accountHistories[res.accountHistories.length - 1].id)
        }
        setIsNextPageLoading(false)
        setItemCount(res.total)
      }
    })
  }
<AutoSizer>
  {({ height, width }) => (
    <InfiniteLoader
      isItemLoaded={isItemLoaded}
      itemCount={itemCount}
      loadMoreItems={loadMoreItems}
    >
      {({ onItemsRendered, ref }) => (
        <FixedSizeList
          height={height}
          itemCount={itemCount}
          itemSize={window.innerWidth <= 800 ? 150 : 60}
          onItemsRendered={onItemsRendered}
          ref={ref}
          width={width}
        >
          {Item}
        </FixedSizeList>
      )}
    </InfiniteLoader>
  )}
</AutoSizer>
```

https://user-images.githubusercontent.com/41809433/212810526-8e68eca2-7ae7-4fbb-a43f-e595e6317212.mov
