### ISSUE TITLE
Scrollbar drift

### ISSUE THREAD

**Issue by codeMonkey82** [bvaughn/react-window#611]
So I am attempting to implement react window in my current project and have noticed quite a bit of scrollbar drift. What I mean by this is when grabbing the scrollbar and moving up and down the cursor seems to drift away from the scroll bar handle. This can be seen within the demo example below, 2 out of the 3 attempts made this do exactly what it is doing in my solution, any ideas ?

Interestingly I have tested this within firefox and the issue is not present, testing it in chrome and safari shows the issue.

https://user-images.githubusercontent.com/56395581/144414748-5a604c41-6cc8-4bff-a14f-91dc885a3d2c.mov

Additionally I also can show this using the existing variable size list code in code sandbox. The first time scrolling will result in the cursor moving faster away from the scroll handle. Once all items have been rendered at least once this is no longer a problem.

https://user-images.githubusercontent.com/56395581/144426354-8e821ca9-de7d-4b8f-bbb1-1a3a1f718069.mov

**Comment by jthrilly** [comment]
Just wanted to add that I also see this issue in our implementation. It seems like it has to be due to variable height elements (logically speaking, the scroll position can't be known before all elements height is known, can it?).

**Comment by fonty422** [comment]
I think it might be linked to the `estimatedIOtemSize`... At least with the `VariableSizeList` component. If I set that to the minimum size I expect to get then it appears to work well.
