### ISSUE TITLE
Is it possible to add onBlur on VariableSizeList ?  

### ISSUE THREAD

**Issue by tomekxoxo** [bvaughn/react-window#614]
![Screenshot 2021-12-23 at 14 52 39](https://user-images.githubusercontent.com/45947389/147249818-434fff56-df2b-42b5-99fe-4d899dccabcc.png)

I would like to obtain result like that,
I've got elements in dropdown that are checkboxes and I would like to be able close dropdown by clicking outside of dropdown.

**Comment by tomekxoxo** [comment]
I fixed problem

**Comment by mashraf-cognna** [comment]
@tomekxoxo how did you fix it ? plz share
