### ISSUE TITLE
 a wrong import about bpfrpt_proptype_WindowScroller

### ISSUE THREAD

**Issue by yizhizhua** [bvaughn/react-window#621]
the first time i install this and run my project there is a resolve error about bpfrpt_proptype_WindowScroller and then i annotation the last line in es/WindowScroller/utils/onScroll and it worked. so is there a history import and it do not be used in anywhere ?

**Comment by OancaAndrei** [comment]
Hi,
I've faced the same issue while having `react-window`, `react-virtualized-auto-sizer` and `react-virtualized` installed. Removing `react-virtualized` seems to fix the issue for me.
