### ISSUE TITLE
When will react 18 be supported?

### ISSUE THREAD

**Issue by F-happy** [bvaughn/react-window#623]

**Comment by qiutian00** [comment]
react 18 version has not release

**Comment by itdhsc** [comment]
This would be interesting for us, too. Is React 18 support on the roadmap for further development?

**Comment by ximex** [comment]
didn't test if anything else needed
```json
"peerDependencies": {
  "react": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0",
  "react-dom": "^15.0.0 || ^16.0.0 || ^17.0.0 || ^18.0.0"
}
```

**Comment by bvaughn** [comment]
If the only thing required is to update the peer dependencies, I could publish a release with that bump. There may be other warnings or things though– in which case, I don't have the time to dig into them.

**Comment by bvaughn** [comment]
Version 1.8.7 has been published with the peer dependencies updated.
