### ISSUE TITLE
Scroll bar return to the top when expanding the next item 

### ISSUE THREAD

**Issue by raghvendradeshpande** [bvaughn/react-window#626]
![image](https://user-images.githubusercontent.com/11072871/154294086-7049fced-7fb2-4771-8114-df91fedf3b96.png)

List of rows - Each row is expandable. We show VariableSizeList when row is selected.
Click first row, Expanded view will show the VariableSizeList Table, Move scroll to middle or bottom. 

Selecting next row, Scroll bar of previous row Table moves to top.

**Comment by TaylorBruening** [comment]
second this. We are having a similar issue with our project
