### ISSUE TITLE
Can we have columns with varying widths on the same row?

### ISSUE THREAD

**Issue by shivaksk1** [bvaughn/react-window#627]
Hi, I am evaluating if I can use react-window to create an EPG (Electronic Program Guide) which has the following layout.

![image](https://user-images.githubusercontent.com/12125989/155946075-c84528cc-51fe-489a-9b80-aeee1e9eea39.png)

Each column in a row can have a different width (column indicates an event. column width is proportional the event duration, in seconds).

I went through the documentation, examples and also tried using the library by configuring parameters/functions like **columnWidth**, but couldn't find a way to do it.

Could you please let me know if react-window can be used to achieve the above layout?

**Comment by Charles-XD** [comment]
@shivaksk1 You can use VariableSizeList for each row and sync their scrolls. Take a look at this: https://stackblitz.com/edit/react-ts-c7hjyp?file=EpgList.tsx&view=preview

**Comment by shivaksk1** [comment]
@Charles-XD yes, this meets my requirement. Thank you very much for the proposal, and the working code.
