### ISSUE TITLE
Calling scrollTo on a VariableSizeGrid causes a crash/loop

### ISSUE THREAD

**Issue by ptlm500** [bvaughn/react-window#63]
Calling `scrollTo` on a `VariableSizeGrid` component seems to cause the page to crash, as seen in the following example:

https://codesandbox.io/s/ypq502woz9

I did notice, however, that there are no test cases for `scrollTo` on `VariableSizeGrid` components, so apologies if the two aren't meant to work together!

**Comment by ptlm500** [comment]
So it looks like this happens when either `scrollLeft` or `scrollTop` are not passed to `scrollTo`. 
Editing the sandbox to always provide a

**Comment by bvaughn** [comment]
The `scrollTo` method for `Grid` requires both `scrollLeft` and `scrollTop` values.

But I can see where it might be useful in some cases to only update one dimension. I'll add a test and fix for this.

**Comment by bvaughn** [comment]
Implemented in 7c481d6

**Comment by bvaughn** [comment]
This fix was included in the [1.2.0 release](https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md#120)

**Comment by savabozo** [comment]
Hi @bvaughn 
Please update the docs with proper interface.
 
For example interface at https://react-window.now.sh/#/api/FixedSizeGrid
`scrollTo({scrollLeft: number, scrollTop: number}): void`
should be
`scrollTo({scrollLeft?: number, scrollTop?: number}): void`
