### ISSUE TITLE
Scrolls to top on rerender

### ISSUE THREAD

**Issue by tommhuth** [bvaughn/react-window#632]
I'm using `react-window` with Mui's `Autocomplete` and it almost works, except for one thing: when a user makes a selection and the select list stays open (via the `disableCloseOnSelect` prop), `react-window` scrolls to the top of the list. 

Is this expected behavior? How can I get my list to stay where it is even when parent rerenders?

**Comment by tommhuth** [comment]
For anyone finding this: the problem was my `ListboxComponent` component on the Mui `Autocomplete` not being referentially stable (inline arrow function). Moving the definition out of the render function solved the problem.

**Comment by jakeledoux** [comment]
Thank you for coming back and posting your solution! It helped me :)

**Comment by simon-c-wong** [comment]
Hey @tommhuth and @jakeledoux 

I believe I'm having the same issue that you guys had experienced. Upon scrolling and on any click (state updates) within `FixedSizeGrid`, it would scroll back to the very top and very left, essentially the [0,0] indices. 

I have a sandbox up if you wouldn't mind taking a look: https://codesandbox.io/s/happy-pascal-cmmhnv
