### ISSUE TITLE
Did the 'react-window' support react 18?

### ISSUE THREAD

**Issue by wesley7891** [bvaughn/react-window#634]
Hi guys,

When I installed 'react-window' in react 18.0 project, I got this problem.

![image](https://user-images.githubusercontent.com/94120374/161474237-1e45076d-ac05-4775-9c0a-86518aa35172.png)

Did the 'react-window' support react 18.0 ?

**Comment by Danscho** [comment]
There already is an open issue: https://github.com/bvaughn/react-window/issues/623 concerning React 18.

**Comment by bvaughn** [comment]
Version 1.8.7 has been published with the peer dependencies updated.
