### ISSUE TITLE
Does 'react-window' work with 'vw' not 'px'

### ISSUE THREAD

**Issue by DanielWLam** [bvaughn/react-window#635]
Does 'react-window' work with 'vw'?

**Comment by rrajaste** [comment]
AFAIK no. You should be able to convert VW to PX with a little bit of JavaScript or use the auto-sizer plugin and restrict the container to whatever size you want.

**Comment by bvaughn** [comment]
No. It only works with pixel numbers, not percentage based units (like "%" or vh/vw).
