### ISSUE TITLE
Add an example of using this library alongside react-dnd

### ISSUE THREAD

**Issue by mutaimwiti** [bvaughn/react-window#644]
Anyone that has worked on this, your help would be very appreciated

**Comment by dandresfg** [comment]
You can try with **react beautiful dnd**

https://codesandbox.io/s/react-beautiful-dnd-react-virtualized-i7kju

**Comment by Charles-XD** [comment]
I used react-dnd for selecting a range of items but if you need something like changing the order I suggest using react-beautiful-dnd.
[https://codesandbox.io/s/priceless-glitter-7swgen](https://codesandbox.io/s/priceless-glitter-7swgen)
