### ISSUE TITLE
Momentum scroll is not available when asymmetric radius has been set on chrome 102

### ISSUE THREAD

**Issue by fioleto** [bvaughn/react-window#646]
# About
Since chrome version 102, Momentum scroll is not available.

# Reproduce
Set asymmetric border-radius css property to outer box. 
[CodeSandbox](https://codesandbox.io/s/exciting-fire-x138dz?file=/index.js)

# Environment
OS: macOS Monterey at least
Browser: google chrome (also electron 19)

## Chrome version 101
![Chrome_101](https://user-images.githubusercontent.com/62394223/170847309-7888ce42-cb4c-47d0-9ce7-0aa9fbcfc289.gif)

## Chrome version 102
![Chrome_102](https://user-images.githubusercontent.com/62394223/170847312-ab68f506-4eb7-4a33-8682-e37e3083c1ad.gif)

Thanks in advance.

**Comment by markogresak** [comment]
There is a bug report in Chromium for this issue, seems like it’s not limited to react-window

https://bugs.chromium.org/p/chromium/issues/detail?id=1330045

**Comment by alexandrzavalii** [comment]
Managed to replicate the issue.

https://codesandbox.io/s/immutable-sunset-8vyj53?file=/index.js

**Comment by fioleto** [comment]
@markogresak
@alexandrzavalii 

Thank you for identifying the root causes of the issue.
In this case, I have no options left without waiting for a solve chromium bug. 

This issue does not cause by the react-window.
Therefore I am thinking of closing this issue in a day, If there is no inconvenience.  

Thank you for taking your time.
