### ISSUE TITLE
Total count above 645277 does-not work 

### ISSUE THREAD

**Issue by source-ram** [bvaughn/react-window#647]
I have my own web-socket implementation to read and parse large files. Even though i have only 1000 lines in memory, i was using the index as a pointer for line number. When the itemCount is set above 700K the react-window component don't show any rows after 645277.

itemCount={totalrows}
itemSize={26}
overscanCount={50} 

`<div style="position: absolute; left: 0px; top: 1.67772e+07px; height: 26px; width: 100%;"><table class="table table-sm table-hover"><tbody><tr><td style="width: 50px; color: rgb(67, 160, 71);">645278</td><td></td></tr></tbody></table></div>
`

**Comment by source-ram** [comment]
This issue is not there in react-virtualized.

**Comment by bmingles** [comment]
I can reproduce this with roughly 419K items as well with itemSize set to `40`. My inner container div seems to have a computed `height: 1.67772e+07px`. Basically, things no longer scroll once I get to item 419,430

**Comment by JunsikLee** [comment]
The same problem occurs

**Comment by mrdulin** [comment]
+1
