### ISSUE TITLE
Poor performance when scrolling with Chrome or Safari

### ISSUE THREAD

**Issue by marcotisi** [bvaughn/react-window#652]
Scrolling performance has declined significantly when using the latest version of Chrome (v102) or Safari (v15.4).
This happens only if you scroll using the mouse wheel or the keyboard, it works when using scrollbars.
In addition, when scrolling using the keyboard, the table loses its focus after a random number of scrolled rows.

Chrome:

https://user-images.githubusercontent.com/2930004/172585611-be2b185f-1667-4c2a-9a1a-97eb2deba4ae.mov

Safari:

https://user-images.githubusercontent.com/2930004/172585668-874564ca-f923-4bf5-82cb-dd7e5eeeacf2.mov

This issue does not occur using the latest version of Firefox (v101), as you can see from this video:

https://user-images.githubusercontent.com/2930004/172586206-37966635-6c10-441c-8635-d02c9b0767a6.mov

The table is the one from this example: https://react-window.vercel.app/#/examples/list/fixed-size

**Comment by chriswoodley** [comment]
I can confirm that I am having the same issue.

**Comment by dfrsol** [comment]
Ditto - as per the issue in TanStack it appears to be an issue with the latest version of Chromium see https://bugs.chromium.org/p/chromium/issues/detail?id=1332962

**Comment by jackblanc** [comment]
Has anyone found a workaround for this issue?

**Comment by chandlerprall** [comment]
The linked chromium bug was marked as a duplicate of another bug stating the issue was resolved in canary builds. I grabbed the latest canary and our react-window usages work as expected there. Looks like it may be 2 or 3 major Chrome releases away, however (chromium issue said v104, I grabbed v105, current Chrome is v102).

**Comment by marcotisi** [comment]
Closing this issue as it's not directly related to `react-window`
