### ISSUE TITLE
A bug about using autofocus

### ISSUE THREAD

**Issue by special-wen** [bvaughn/react-window#660]
It works perfectly fine when not adding autoFocus. However, when autoFocus property is added, I just found this situation as displayed in video.

Please check out this video for detailed bug info:

https://user-images.githubusercontent.com/27426408/181714174-f2753779-fbf1-47ca-8fed-013bd3c9a9f4.mp4

**Comment by gaoyuan1223m** [comment]
I also encountered the same problem. I really desire the Virtual List that support editing in `autofocus` input. 

hope and appreciate @davidgarsan feedback~~~
