### ISSUE TITLE
react-virtualized-auto-sizer does not support react 18 yet

### ISSUE THREAD

**Issue by L-u-k-e** [bvaughn/react-window#661]
Hi! This package's README suggests using  [`react-virtualized-auto-sizer`](https://github.com/bvaughn/react-virtualized-auto-sizer) to make a list/grid [fill 100% height of the page](https://github.com/bvaughn/react-window#can-a-list-or-a-grid-fill-100-the-width-or-height-of-a-page). 

Unfortunately, the [`react-virtualized-auto-sizer`](https://github.com/bvaughn/react-virtualized-auto-sizer) package does not  yet support React 18. Also, it apparently does not have an "Issues" tab, so I can't report this there. 

Is there a new recommended way to work around this for those of us using React 18?

**Comment by lloy0076** [comment]
https://github.com/bvaughn/react-virtualized-auto-sizer/pull/40

**Comment by colin969** [comment]
At what point do you remove it from the description?

Why even mention something in the readme that can't merge a 2 line change in the space of 3 months?
