### ISSUE TITLE
Any Functionality like WindowScroller in react-window

### ISSUE THREAD

**Issue by gaoyuan1223m** [bvaughn/react-window#662]
I would wonder why WindowScroller is removed from 'react-window' or is there any alternative to WindowScroller in 'react-window'?

**Comment by charkour** [comment]
I'm interested as well. Perhaps this package will work: https://github.com/FedericoDiRosa/react-window-scroller

**Comment by gaoyuan1223m** [comment]
> 

@charkour Thanks a lot!

**Comment by epurban** [comment]
Hey @charkour @gaoyuan1223m , were either of you able to get this working? For me, introducing react-window-scroller causes the cell components to unmount on every render, which leads to terrible performance.

**Comment by charkour** [comment]
Hey @epurban, I ended up switching to [TanStack/virtual](https://github.com/TanStack/virtual) since it is newer, receiving active support, and is smaller. It solved my issue. 

Sorry I cannot be much help, but figured I'd like you know how I moved forward.

**Comment by patorjk** [comment]
I'm also wondering about this. The react-window package is fantastic, but for one of my use cases I wound up with a list that needed to be scrolled by its container. Basically the use case seen here: https://codesandbox.io/p/sandbox/7yzzw92xw1?file=%2Fsrc%2FUsers.jsx

I wound up add react-virtualized to my project too, and while it works, but I feel a bit strange having both in my project and worry that react-virtualized may be on its way out. The react-window-scroller package mentioned above doesn't look like its maintained anymore.

**Comment by epurban** [comment]
Hey @patorjk, as @charkour recommended, I also switched to tanstack virtual for most of my virtualized list use cases.

**Comment by patorjk** [comment]
That library turned out to be awesome. I did not expect it to handle my exact use case but it's literally their first example. I'm going to need to test some more but thank you for seconding that recommendation!
