### ISSUE TITLE
Flicker and compressed items

### ISSUE THREAD

**Issue by ErrorEater** [bvaughn/react-window#666]
Items flicker despite the added "style" tag and data source not being updated.
Items are compressed giving the look below.

How can I solve the problems?

![image](https://user-images.githubusercontent.com/8914034/184759329-d13432d7-f534-4248-b2b9-2492698b44ad.png)

**Comment by joshdev8** [comment]
Try the itemSize prop.

**Comment by elhedgie** [comment]
> Try the itemSize prop.

that doesnt help at all
