### ISSUE TITLE
different height for every options

### ISSUE THREAD

**Issue by leadstar116** [bvaughn/react-window#675]
I see that I need to pass `itemSize` prop which makes all items have the same height.
How can I manage if all items are having different heights? Is there any way to handle it?

**Comment by viktor-ulyankin** [comment]
May be VariableSizeList ( https://react-window.vercel.app/#/examples/list/variable-size ) will help you?

**Comment by leadstar116** [comment]
@viktor-ulyankin 
I am not sure I can get the height of the item without rendering...

**Comment by Aliendreamer** [comment]
this is why you render them and in useLayoutEffects you actually get the window.getclientrect.. and get the real sizes and that is, you set some basic width and height for start and then update it.
