### ISSUE TITLE
Browser compability

### ISSUE THREAD

**Issue by morewings** [bvaughn/react-window#68]
Is it compatibe with IE11?

**Comment by bvaughn** [comment]
You should be able to confirm this by trying the demo site in IE11 😉

**Comment by miguelbermudez** [comment]
Apologies for commenting on a closed issue but the demo site is reporting an error in IE11. 

![screen shot 2019-01-15 at 10 50 45 am](https://user-images.githubusercontent.com/456538/51192037-a9e3c500-18b3-11e9-8685-6f998ede8dd5.png)

More Detail:
![screen shot 2019-01-15 at 10 51 23 am](https://user-images.githubusercontent.com/456538/51192065-bcf69500-18b3-11e9-9c30-170976d91024.png)

Looks like `Array.includes` need to be polyfilled.

**Comment by bvaughn** [comment]
These APIs are only used in the demo website FWIW. I removed `Array.prototype.includes` in 84f5792 and re-deployed, but then hit a problem with `Array.prototype.fill`– which I removed with f8cf9fa.

I'm not sure I actively care enough to support IE11 on the docs website, to be honest. 😅 but it should work again now.

**Comment by jeffal** [comment]
Horizontal scrolling does not work in IE11, see [the demo site](https://react-window.now.sh/#/examples/grid/fixed-size).
