### ISSUE TITLE
Where should I place the code for async fetch/axios data for the <List>?

### ISSUE THREAD

**Issue by yelnyafacee** [bvaughn/react-window#685]
I checked all the sandboxes for `react-window` (`react-virtualized-auto-sizer`, `react-window-infinite-loader`)

They both use mock data

Where should I place the code for async fetch/axios data for the `<List>`?

**Comment by SachinJadeja** [comment]
Given the requirement, you can perform the Axios fetch in useEffect and on .then() store it inside a state.

**Comment by leo1104** [comment]
Make the API call in a separate use effect and store the fetched data in a state, after that pass the data to ItemData in the list component.
