### ISSUE TITLE
Custom properties and event handlers

### ISSUE THREAD

**Issue by JoshClose** [bvaughn/react-window#693]
The documentation shows to set custom properties and event handlers using `outerElementType`. Is there any reason why it can't/shouldn't be attached to the item?

```jsx
<VariableSizeGrid {...otherProps}>
    {props => <Cell {...props} onClick={handleClick} />}
</VariableSizeGrid>
```

**Comment by jasontlouro** [comment]
Thank you for this, this is a far better approach and should be in the docs.
