### ISSUE TITLE
Scroll indicator jumps when scrolling through a VariableSizeList

### ISSUE THREAD

**Issue by wilcoschoneveld** [bvaughn/react-window#70]
Example:
https://codesandbox.io/s/vnn4z83313

When scrolling down you can see the scrolling indicator jump up and it becomes more and more pronounced when reaching the bottom of the container

**Comment by wilcoschoneveld** [comment]
I figured you can set `estimatedItemSize` to the average value of sizes. In my case I know all sizes beforehand so would it be able to make use the exact value instead of 'estimates'?

**Comment by bvaughn** [comment]
No, sorry. There's no support for that. And I think it's probably an
uncommon enough use case that I don't think I want to add any complexity to
support it. 😅 Hope you understand

**Comment by wilcoschoneveld** [comment]
Yeah it's cool. Thanks for the reply!

**Comment by bvaughn** [comment]
No problem. Thanks for being understanding.
