### ISSUE TITLE
scrollToItem only if the item is not visible?

### ISSUE THREAD

**Issue by icd2k3** [bvaughn/react-window#710]
Is this possible? I only want to scroll to an item if it's outside of the viewable area.

**Comment by timminata** [comment]
Pretty sure this is already possible, I was playing with it today:
You can use the "smart" option:

`listRef.current?.scrollToItem(scrollToIndex, 'smart');`

From the JSDocs:
```
- smart
 If the item is already visible, don't scroll at all.
 If it is less than one viewport away, scroll as little as possible so that it becomes visible.
 If it is more than one viewport away, scroll so that it is centered within the list.
```
