### ISSUE TITLE
scrollToItem causing infinite rerender and page to crash

### ISSUE THREAD

**Issue by CosmicSpectrum** [bvaughn/react-window#711]
hey i've tried to make a list that gets a prop of an item index.. and when using scrolltoitem function to make it scroll to it in a use effect to make it scroll on load causing infinite rerender and my app to crash.. any ideas why?

**Comment by CosmicSpectrum** [comment]
hey, after testing for a while i figured out that this problem occurs to me when using scrolltoitem on a variablesizelist.. is there a known problem with this implementation? does anyone know how to make scrolltoitem work with variablesizelist?

**Comment by crapthings** [comment]
same same~
