### ISSUE TITLE
List of Lists

### ISSUE THREAD

**Issue by sandha6000** [bvaughn/react-window#714]
I need to render a list of lists using react-window library to optimize the rendering process by only rendering the list items that are currently in the viewport.The list item is also a react-window list. (Inner list and outer list). Is this approach correct and scalable for my use case?Does it have any Limitation?

**Comment by sikhaman** [comment]
Hello @sandha6000 I have same task ) and started to experiment on it. here is my [code sandbox](https://codesandbox.io/s/goofy-glitter-lp2hcd) I think it is pretty ok to use nested lists inside lists. Same as table or grid inside grid like do react-virtualized. I measured performance everything it seems ok. at least for 3000 elements )

**Comment by sandha6000** [comment]
Thank you @sikhaman .

**Comment by thunderfreak** [comment]
Hi @sikhaman do you still have the code sandbox? I think the list if expired.

**Comment by thunderfreak** [comment]
Thanks @sikhaman . What I'm trying to do is render a nested list (ie: searchresults but there are 4 types of search results, and each type has multiple matches). Do you know if virtualization can be a suitable solution in this case?
