### ISSUE TITLE
hook API for  existing components

### ISSUE THREAD

**Issue by Am1rArsalan** [bvaughn/react-window#717]
Hi, 

Since react-window is the most loved package and mostly is being used in projects, I was wondering if we could have the hooks API for existing components that we have right now. Is there any plan for that? 

example: 
``` tsx 
import { useFixedSizeList  } from 'react-window';

const Example = () => { 
  const { items }  = useFixedSizeList({ 
        height: 150,
        itemCount: 1000,
        itemSize: 35,
        width: 300,
   });
  
 return (  
    <div>
      {items.map((virtualRow) => { 
           return (
               <div style={style}>Row {virtualRow.index}</div> 
           ) 
      })
    </div>
   ) 
};
```

**Comment by SepehrGouran** [comment]
Take a look at this headless library [https://tanstack.com/virtual/v3](https://tanstack.com/virtual/v3)

**Comment by AmirAhmadzadeh** [comment]
https://tanstack.com/virtual/v3 is still in beta, and my suggestion was to have hook APIs for the `react-window`  package.
