### ISSUE TITLE
Code samples on website do not match displayed element

### ISSUE THREAD

**Issue by Vinnl** [bvaughn/react-window#72]
For example, on the example of the Fixed Size List, items in the row are labelled "Item _n_" in the demo, but `Row {index}` in the code sample.

![image](https://user-images.githubusercontent.com/4251/46918983-c6344500-cfd8-11e8-8693-ee9de456eb79.png)

I wanted to submit [a PR to fix this](https://github.com/bvaughn/react-window/compare/master...Vinnl:issues/72?expand=1), but since code examples are reused (e.g. FixedSizeList in both Fixed Size List as Scrolling to an item), I couldn't simply modify them, and since the horizontal and vertical versions of the Fixed Size List both reuse the code that labels them with "Item", I could change the demo elements either. (I also didn't manage to quickly get it to run locally by following the instructions in website/README either, btw...)

**Comment by bvaughn** [comment]
To be honest, I think this is fine. I don't think they need to match 100%. The Code Sandboxes are just meant to give people something simple, that works, to then fork and play around. 😄

Thanks for offering to help though!

> since code examples are reused (e.g. FixedSizeList in both Fixed Size List as Scrolling to an item)

I don't think any code examples or Code Sandboxes are shared between the docs pages. Please correct me if I'm wrong.
