### ISSUE TITLE
Dynamic heights on each item

### ISSUE THREAD

**Issue by vientang** [bvaughn/react-window#73]
Hi, 

What I'm looking to do is have each items height be dynamic based on it's content. 

This can be achieved by getting the `clientHeight` value from the refs of list items, capturing that to state (as an array or map object) and passing that value back to the `itemSize` function. However, a value `itemSize` is initially required. If I give it a value, then the `clientHeight` will always be that value. 

Can anyone point me in the right direction? Much appreciated, thanks!

**Comment by TrySound** [comment]
WIP here https://github.com/bvaughn/react-window/issues/6
You may try alpha here `yarn add react-window@next`

**Comment by bvaughn** [comment]
This overlaps with issue #6, as @TrySound has pointed out. Follow along on that issue for updates 😄it's not supported officially yet.
