### ISSUE TITLE
`.forceUpdate` is not working for VariableSizeList

### ISSUE THREAD

**Issue by timminata** [bvaughn/react-window#731]
I have seen several users commenting that dynamic heights that might change as your data changes are not working. Furthermore, we have tried to fix this issue by using the `.forceUpdate()` method, but it seems like even though the method is called, no change is observed. Only the first render is correct, then as data changes nothing is updating. I would appreciate if someone could point us in the right direction:

Here is a code sandbox illustrating that the heights do not change, as the "data" (in this case a simple modulus) changes: 
https://codesandbox.io/s/proud-leaf-9c38ch?file=/index.js

**Comment by timminata** [comment]
If anyone stumbles on this, it just so happens that after posting this I managed to fix my issue by using `.resetAfterIndex(0)`, which resets and triggers an update. I'm leaving the issue open though as I would still like to understand why `.forceUpdate()` does not do what I would expect it to do.

**Comment by aovchinn** [comment]
>  I would still like to understand why .forceUpdate() does not do what I would expect it to do.

it was just https://legacy.reactjs.org/docs/react-component.html#forceupdate 
without resetting inner caches that does nothing, docs do mention that 

> reset... should be called whenever a row's ... changes. (Note that this is not a typical occurrance.)

https://web.archive.org/web/20241225003549/https://react-window.vercel.app/#/api/VariableSizeGrid

Sorry for ressurecting this old thread, just stumbled upon this myself
