### ISSUE TITLE
FixedSizeList padding

### ISSUE THREAD

**Issue by khlieng** [bvaughn/react-window#74]
Is there a way to have padding at the top and bottom of a list? If I do `10px 0` on the outer div I get `20px` of padding at the bottom, I can make it look proper by adding a `10px` top margin to the list items but that just shifts the windowing off-center.

**Comment by bvaughn** [comment]
No, padding like that isn't really supported. If you want padding around the entire list, put the list inside of a padded container.

If you literally just want 10px

**Comment by khlieng** [comment]
Ah ok, I wanted the padding inside the list like this https://jsfiddle.net/9wpd58mx/6/, I could just do it with a VariableSizeList.

**Comment by ahtcx** [comment]
This can be fixed by adding `position: relative;` to the list, should I make a PR with a fix @bvaughn ?

**Comment by henryoliver** [comment]
Just subtract a given `offset` from the grid `height`:

```
const HEADER_OFFSET = 72;
...
return (
  <FixedSizeGrid
    ref={photoGridRef}
    width={width}
    height={height - HEADER_OFFSET}
    rowCount={rowCount}
    rowHeight={rowHeight}
    ...
```
