### ISSUE TITLE
content flashes when scrolling the last item

### ISSUE THREAD

**Issue by hoanghiaquyen** [bvaughn/react-window#740]
Browser: Chrome

Hi @bvaughn. Thank you sharing library. Today, I have used it but when I test it then I saw content flashes when scrolling the last item. Can you advice me? Have a nice day.

Source code: [Code](https://codesandbox.io/s/react-window-with-table-elements-forked-huti6?file=/src/index.tsx)
Video: https://easyupload.io/rtykd7

**Comment by zhongmeizhi** [comment]
me too, How did you solve the problem? @w7en
