### ISSUE TITLE
Scrolling up in VariableSizeList causes major scroll jitters when using scrollToItem.

### ISSUE THREAD

**Issue by shaunchander** [bvaughn/react-window#741]
If you create a `VariableSizeList` and scroll to a certain element in it using `listRef.current.scrollToItem(200);` then attempt to scroll up, there is a very visible jitter. I believe this happens because components of dynamic height are rendering and being upserted into the DOM above where the user is currently positioned.

The components I'm working with a dynamically sized, unlike into the demo on the docs where each element in the variable list has its heighted pre-calculated.

I'll create a minimum-reproducible-demo shortly!

**Comment by niemal** [comment]
Very interesting, are you using a shadow-DOM like technique with opacity: 0 to calculate everything? I am very curious into this, thanks.

**Comment by niemal** [comment]
The clutter is gone doing what I mentioned above:

Just above my list component:
```typescript
        {!heightsCalculated && (
          <ShadowHeightCalculator messages={localMessages} />
        )}
 ```
 
 `ShadowHeightCalculator` component looks like:
 ```typescript
 
function ShadowHeightCalculator({
  messages,
}: {
  messages: Array<MyDataType>;
}) {
  return (
    <div style={{ position: "relative", opacity: 0, height: "1px" }}>
      {messages.map((message, idx) => (
        <ListItem
          key={`shadow-height-${idx}`}
          index={idx}
          style={{
            position: "absolute",
            left: 0,
            top: 0,
          }}
        />
      ))}
    </div>
  );
}
 ```
 
 And I am running a loop somewhere (a `useInterval` hook) checking it like so:
 ```typescript
   const checkHeightsCalculated = (messages: Array<MyDataType>) => {
      const heightsCalculated = messages.some(
        (msg) =>
          rowHeights?.current &&
          typeof rowHeights.current[msg.hash ?? ""] !== "number"
      );

      return heightsCalculated;
  };
 ```

**Comment by pcty-thezachcannon** [comment]
Any updates on your solution, I have the same thing happening @shaunchander @niemal
