### ISSUE TITLE
Can I replace the blank spaces which is caused by scrolling fast with other components?

### ISSUE THREAD

**Issue by Derigion** [bvaughn/react-window#743]
Since items in a virtualized list only change when the user scrolls, blank space can briefly flash as newer entries are about to be displayed. I want to replace the blank spaces with some components to tell the users it's rendering.

**Comment by alejandrorascovan** [comment]
In your row component definition, you could first check if data[index] is undefined for example. I do something like this:

```
const Row = ({ data, index, style }) => {
	if (data[index] === undefined) return (<div style={style}><LoadingOrError /></div>);
...
```

**Comment by rishabhchand007** [comment]
> In your row component definition, you could first check if data[index] is undefined for example. I do something like this:
> 
> ```
> const Row = ({ data, index, style }) => {
> 	if (data[index] === undefined) return (<div style={style}><LoadingOrError /></div>);
> ...
> ```

Didnt work for me.
