### ISSUE TITLE
Remove nodes in pairs to avoid zebra stripe flashing

### ISSUE THREAD

**Issue by jasonbarry** [bvaughn/react-window#744]
If a table has zebra-style rows declared by :odd or :even CSS selectors, scrolling will remove nodes from the top of the DOM tree one-by-one, making the previously odd rows even and vice versa. 

It would be nice if we could specify to remove nodes in pairs, so odd-numbered rows would stay odd, and even-numbered rows would stay even, as the user scrolled. 

Otherwise, a zebra stripe flashing occurs on scroll.

**Comment by szszoke** [comment]
A workaround is to apply the even/odd styling based on the index.
