### ISSUE TITLE
Confusing example wording.

### ISSUE THREAD

**Issue by gc** [bvaughn/react-window#75]
Hopefully this image illustrates the slightly confusing wording:

![chrome_2018-10-22_13-16-20](https://user-images.githubusercontent.com/30398469/47275769-ea59dc80-d5fd-11e8-8700-5505e2fe3b25.png)

The code on the right uses `Row {index}` while what seems to be the result of that code uses `Item {index}`,  same with `Column {index}`. Perhaps this is intentional but it caused me a tiny bit of confusion. Willing to make a PR if you want!

**Comment by gc** [comment]
I just noticed there's a closed issue regarding this, although I don't think the issue is about any difference between the website code vs sandbox code (although I do wonder why they'd be different), but rather that the website user sees a code and then the output/demo of the code next to it, except it seems like a mismatch because the output is slightly different than what they'd expect it to be. It confused me enough to think there was an error in the website code or perhaps an outdated example.

In either case thanks for your work. P.S I like your tweets about optimizing and improving react-window

**Comment by bvaughn** [comment]
Hey. 😄

That's good feedback. I've fixed this with 70b66ae.
