### ISSUE TITLE
Can't use react-window in vite react-ts

### ISSUE THREAD

**Issue by Osmon11** [bvaughn/react-window#753]
Tab hangs.
[repro](https://stackblitz.com/edit/vite-react-ts-bc4yvg?file=src%2FApp.tsx)

**Comment by TmanTman** [comment]
@Osmon11 I use the same setup as per your reproduction successfully in a vite/react/ts project.

I'm not sure what exactly "tab hangs" means but I briefly opened the reproduction in Chrome and it seems to work.
