### ISSUE TITLE
Input is losing focus , when wrapped with VariableSizeList

### ISSUE THREAD

**Issue by pst37** [bvaughn/react-window#755]
I have wrapped a input element  inside VariableSizeList. When there is change in input component, the input component is losing focus , because whole component is getting remounted or i can say react is re-creating whole new tree. 

I have added the example here.
[Example here](https://stackblitz.com/edit/stackblitz-starters-tdvwky?description=A%20create-react-app%20project%20based%20on%20react%20and%20react-dom&file=src%2FApp.js&title=React%20Starter)

Steps:-
1.) Open Element tab in dev-tools
2.) type anything in any input box 

You will notice the wrapper of all new input is getting updated ...

**Comment by Dimitrov-Codes** [comment]
I am facing the same issue . Are there any workarounds to this??

**Comment by h7y** [comment]
Moving the renderer 👇 to a separate function as shown in the docs would fix this :)


```javascript
{({ index }) => (
  <div className="test">
    <input
      type="text"
      placeholder="search"
      value={searchText[index]}
      onChange={(e) => onChange(e, index)}
    />
  </div>
)}
```

**Comment by sunpcm** [comment]
https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335
