### ISSUE TITLE
onClick inside <List /> element doesn't work

### ISSUE THREAD

**Issue by CopsLikeDonuts** [bvaughn/react-window#759]
Hey, I spotted problem that onClick element prop in <List /> component doesn't work.

My env:

Apple M3 Pro
18 GB
macOs Sonoma 14.1

at other envs it works good.

my code:

{Boolean(dataToDisplay.length) && (
              <List
                itemCount={dataToDisplay.length}
                height={370}
                itemSize={60}
                width="100%"
              >
                {({index, style}: {index: number; style: CSSProperties}) => {
                  const asset = dataToDisplay[index];
                  return (
                    <button
                      onClick={() => onTokenSelect(asset)}
                      className={assetOptionContainer}
                      style={style}
                      onTouchEnd={() => onTokenSelect(asset)}
                      key={index}
                    >....</button>)}})}
                    
Did anyone face with this problem?

**Comment by kjohn-acx** [comment]
I'm currently having this issue as well

**Comment by priyanshushh** [comment]
> Hey, I spotted problem that onClick element prop in component doesn't work.
> 
> My env:
> 
> Apple M3 Pro 18 GB macOs Sonoma 14.1
> 
> at other envs it works good.
> 
> my code:
> 
> {Boolean(dataToDisplay.length) && ( {({index, style}: {index: number; style: CSSProperties}) => { const asset = dataToDisplay[index]; return ( <button onClick={() => onTokenSelect(asset)} className={assetOptionContainer} style={style} onTouchEnd={() => onTokenSelect(asset)} key={index} >....)}})}
> 
> Did anyone face with this problem?

did you found some solution for this ? i am facing a similar issue..
