### ISSUE TITLE
Blanks appear on fast scrolling in react 18 use createRoot

### ISSUE THREAD

**Issue by boris-w** [bvaughn/react-window#761]
I upgraded the react in the example to 18 and used `createRoot` instead of `ReactDOM.render`, and then there is a noticeable blank area when scrolling quickly.
Here's my example: https://codesandbox.io/p/sandbox/suspicious-black-nwhqkr?file=%2Findex.js%3A13%2C8

**Comment by kevinhaas** [comment]
This issue has existed since at least 2020 looking back, and I also ran into it. None of the issues were properly resolved.

Just use [this](https://github.com/petyosi/react-virtuoso) as it's actively maintained. I did a clean swap and don't have flashing content anymore.

**Comment by parth-chovatiya** [comment]
I was also getting this issue. Is there any way to fix this..?

**Comment by vmatyagin** [comment]
up
demo from readme
https://codesandbox.io/s/3vnx878jk5
my fork with react 18
https://codesandbox.io/p/sandbox/bvaughn-react-window-fixed-size-list-vertical-forked-pqhjw6

It can be fixed by adding flushSync on scroll event
