### ISSUE TITLE
add new item error when use VariableSizeList

### ISSUE THREAD

**Issue by 2239559319** [bvaughn/react-window#762]
How to reproduce?

Go to this [codesandbox](https://codesandbox.io/p/sandbox/react-window-test-styvtt?file=%2Fsrc%2FApp.tsx%3A2%2C10-2%2C26), click add

What is the expectation?

The list increases after clicking `add` button, list should be `0` to `5`

What actually happened？

`0` `1` and `2` item lost

**Comment by ches4117** [comment]
Your numbers disappear because you use `ref?.current?.scrollTo((newData.length - 1) * 37);`,
You could try to use `ref?.current?.scrollTo(0);`, or shorten the `List` height like `height={100}`, it will be scrollable.
