### ISSUE TITLE
Allow canceling scroll

### ISSUE THREAD

**Issue by viveleroi** [bvaughn/react-window#763]
I would like a way to disallow a user to scroll the content.

We have a tree component (using react-vtree) that allows editing tree nodes. We plan to prompt a user to save or reject their changes when they start scrolling the tree (because there are too many UX gotchas otherwise). However I see no way to do this and I can't use the native `onScroll` props on the react-window elements.

For now I'm using the outerRef and cancelling the mouse wheel events, but it would be ideal if there was a way to preventDefault on the custom onScroll

**Comment by bvaughn** [comment]
I don't think this is something I want to support in more of a built-in way. I would recommend using a ref like you have described.
