### ISSUE TITLE
On each change, whole grid is getting re-rendered !

### ISSUE THREAD

**Issue by sravaniPrism** [bvaughn/react-window#770]
We have table structure , where each row is component and we have state in parent component , whenever I am editing it, it re-renders the entire table even though we have already used useMemo() to prevent unnecessary re renders . While it gets re rendered , it is getting automatically change to initial state. I want solution to prevent this multiple re renders on each edit.

P.s: We can't shift state from parent to child as it is complex.  
![image](https://github.com/bvaughn/react-window/assets/173976819/ff442587-287c-4bed-b705-13b51e8b386d)

**Comment by bvaughn** [comment]
Please don't file duplicate questions. This was already asked in #769
