### ISSUE TITLE
How to set List init index?

### ISSUE THREAD

**Issue by BingCoke** [bvaughn/react-window#773]
I have a large list, and will remember history.So i need go to last position when reopen it.
For example, the last item I viewed was the 200th item. When I reopen this list, I hope to start rendering from item 200 again, and only when I scroll up will it start rendering the 199th item. Currently, the documentation for the List seems to start rendering from 0, rendering from item 0 to item 200, and it is not possible to immediately scroll to the 200th item. When using scrollToItem, sometimes it cannot accurately scroll to the desired position, perhaps stopping at the 10th item.

**Comment by BingCoke** [comment]
And the height of the item is unknown; I will only know the height when I actually render it.

**Comment by bvaughn** [comment]
There is no way to set that via props. You would have to use a ref and call the `scrollToItem` method from a layout effect (see [the docs page](https://react-window.vercel.app/#/api/FixedSizeList) for more on `scrollToItem`)

**Comment by BingCoke** [comment]
> There is no way to set that via props. You would have to use a ref and call the `scrollToItem` method from a layout effect (see [the docs page](https://react-window.vercel.app/#/api/FixedSizeList) for more on `scrollToItem`)

i used `scrollToItem` method.As what i had said, When using scrollToItem, sometimes it cannot accurately scroll to the desired position, perhaps stopping at the 10th item but I want to go to 200th item !

**Comment by bvaughn** [comment]
I can't really help with this because you haven't shared any code.

**Comment by BingCoke** [comment]
> I can't really help with this because you haven't shared any code.
sorry i forget this.

**Comment by BingCoke** [comment]
> I can't really help with this because you haven't shared any code.

Here are the sample codes. I need each row's height to be dynamic. When I click the "goto 200" button, I get the result shown in the image below, which is not what I want. Are there any issues with the code or areas that could be optimized?
<img width="693" alt="image" src="https://github.com/user-attachments/assets/619eafd2-b3cb-4664-8a7e-3365008bdfd5">

**Comment by bvaughn** [comment]
This is not a repro. I can’t run that or debug it.

**Comment by BingCoke** [comment]
My apologies for forgetting to include the link earlier. Here is the code link: https://codesandbox.io/p/sandbox/window-example-5r3dnj

**Comment by bvaughn** [comment]
Gotcha.

Hm. Not sure. If I click a second time, it seems to scroll to the correct row. Seems like maybe there's a race or something that's causing it not to re-scroll after measuring the items initially.

If you'd like to submit a PR I'll be happy to review it. Doubtful I'll have time to look into it though.
