### ISSUE TITLE
Scroll to index

### ISSUE THREAD

**Issue by rullymartanto** [bvaughn/react-window#774]
How to scrool to index?
in the react virualize we able to do that
https://github.com/bvaughn/react-virtualized/blob/ff2e15c87ed1f52891682c0764b7c27549aa9cba/docs/List.md#prop-types

**Comment by bvaughn** [comment]
Check out the docs: https://react-window.vercel.app/#/api/FixedSizeList

> `scrollToItem(index: number, align: string = "auto"): void`
> Scroll to the specified item.
> 
> By default, the List will scroll as little as possible to ensure the item is visible. You can control the alignment of the item though by specifying a second alignment parameter. Acceptable values are:
> 
> * `"auto"` (default) - Scroll as little as possible to ensure the item is visible. (If the item is already visible, it won't scroll at all.)
> * `"smart"` - If the item is already visible, don't scroll at all. If it is less than one viewport away, scroll as little as possible so that it becomes visible. If it is more than one viewport away, scroll so that it is centered within the list.
> * `"center"` - Center align the item within the list.
> * `"end"` - Align the item to the end of the list (the bottom for vertical lists or the right for horizontal lists).
> * `"start"` - Align the item to the beginning of the list (the top for vertical lists or the left for horizontal lists).

Here is an example/demo page: https://react-window.vercel.app/#/examples/list/scroll-to-item
