### ISSUE TITLE
Endless scrolling on Safari

### ISSUE THREAD

**Issue by mikeszutu** [bvaughn/react-window#776]
We have a implementation using VariableSizeGrid that scrolling using arrow keys up or down doesn't work after the initial press. I need re-focus on the component for the arrow keys to work again? This is also an issue on the demo examples

**Comment by bvaughn** [comment]
> after the initial press

I don't know what this means.

The docs pages work for me after a single click (to focus) and then typing arrow keys. Tested both Chrome and Safari.

Since there's no repro with this issue I'm going to close it.
