### ISSUE TITLE
Wrong types documentation.

### ISSUE THREAD

**Issue by iuuukhueeee** [bvaughn/react-window#778]
According to the document at link https://react-window.vercel.app/#/api/FixedSizeList

`height` was expecting either a `number` or a `string` type.

```js
        <FixedSizeList
          height='50%'
          width='20vw'
          itemSize={46}
          itemCount={200}
          overscanCount={5}
          className='explorer-scrollbar'
        >
          {renderRow}
        </FixedSizeList>
```

## Expected behavior 
Working normally and do not throw an Error.

## Actual behavior
Thrown error `Uncaught Error: An invalid "height" prop has been specified. Vertical lists must specify a number for height. "string" was specified.`

**Comment by bvaughn** [comment]
Vertical lists require a number for _height_ but will support either a number or string for width. Horizontal lists require a number for _width_ but will support a number or string for height. I'm not sure how to make that clearer in the docs (and DEV warnings) but you're welcome to submit a PR to update the docs if you have suggestions.
