### ISSUE TITLE
react-window if provided itemCount as 5 mil only renders upto 1.6 million 

### ISSUE THREAD

**Issue by psurana-flextrade** [bvaughn/react-window#780]
Hi,

thanks for creating react-window, i find it very good and alternative solution to react-virtualized rendering performance is better in react-window and its very optimized

thing is i have to show log lines in my project, log lines ranges from around 1mil to 10 mil when i tried the react-window Fixed or Variable list, it only renders upto 1677720

i have a created a sandbox environment to check

https://codesandbox.io/p/sandbox/epic-dream-3v89z5

am i missing something here?

**Comment by shaadansari** [comment]
Hi @psurana-flextrade , 
The issue you're experiencing where the last rendered <div> element appears at top: 3.35545e+07px (which is approximately 33,554,432 pixels) and no further rows are rendered afterward is related to the maximum scroll height limitation in browsers.
![Screenshot 2024-09-10 105753](https://github.com/user-attachments/assets/e53114ce-2626-4614-a433-28411028b360)

**Comment by shaadansari** [comment]
if you reduce the item size to 10, the number of rendered items will double. There are no issues with React Window.

**Comment by psurana-flextrade** [comment]
hi @shaadansari thanks for looking into this one.
I get it now due to browser limitation of height, we could not render more rows.

Maybe this can resolved using offset value, adding offset to index would definitely show all the rows

i have updated the codepen if anyone needs it
https://codesandbox.io/p/sandbox/epic-dream-3v89z5

are you planning to introduce feature like maybe offset to support any number of rows for VariableSizeGrid?

**Comment by shaadansari** [comment]
Hi, can you please explain the solution you mentioned?
 Yes, I'm interested in contributing a feature.
