### ISSUE TITLE
[question] Why does the itemKey function keep executing?

### ISSUE THREAD

**Issue by CorgiTT** [bvaughn/react-window#786]
![image](https://github.com/user-attachments/assets/78c9a238-f9a9-46d4-8647-ee5d6d9b3da3)
--- 
Although this function is always performing rendering, there doesn't seem to be any page performance issues. Is it because ListRender is a function, in the AutoSizer component?

![image](https://github.com/user-attachments/assets/c03b82eb-cb38-4d4e-af92-b3427fe95e72)

**Comment by bvaughn** [comment]
As you scroll, the list needs to render a bunch of items. To know whether it needs to update or recreate an item, it queries the item's "key". If you're seeing it happen a ton on mount then that might indicate that you're over invalidating bc of how your `setItemSize`/`getItemSize` code works but I don't know what you're doing there.
