### ISSUE TITLE
Strings do not work with FixedSizeList height.

### ISSUE THREAD

**Issue by creativebull** [bvaughn/react-window#788]
I want to set the height like '50%' or 'calc(100vh - 100px)' but I get the following error:

`Error: An invalid "height" prop has been specified. Vertical lists must specify a number for height. "string" was specified.`

But the doc said so

> height: number | string
> Height of the list.
> 
> For vertical lists, this must be a number. It affects the number of rows that will be rendered (and displayed) at any given time.
> 
> For horizontal lists, this can be a number or a string (e.g. "50%").

**What's the problem?** Is there a problem with the documentation or codebase?

**Comment by bvaughn** [comment]
The error message says the problem. If your list is vertical, `height` needs to be a number. "100%" is not a number.
