### ISSUE TITLE
Move CodeSandbox examples to GitHub

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-window#8]
This would make them easier to update when the API changes.

Ideally I would like to avoid embedding them into the CRA website though since this would bloat the website size significantly.

Maybe I could use something like CodeSandboxer to create lightweight links to CS:
https://github.com/Noviny/codesandboxer/tree/master/packages/codesandboxer

**Comment by wuweiweiwu** [comment]
I can pick this up. codesandboxer seems cool!

**Comment by bvaughn** [comment]
I haven't really thought through this fully yet. (I haven't looked into how codesandboxer works.) My goals are just:
* Make it easier to update all of the docs examples (of which there will be many more over time) any time the API changes. For this reason, it's nice if those examples live within the repo so I can find-and-replace or run a codemod on them. Also they would be revisioned along with the change, if I wanted to play with changes in a branch but not merge it to mater until later.
* Don't bloat the size of the demo site unnecessarily. I would go with an approach like the Gatbsy plugin I created ([`gatsby-remark-code-repls`](https://www.gatsbyjs.org/packages/gatsby-remark-code-repls/)) except that would inject all of the sample code as links and cause the bundle to grow. I think codesandboxer runs in the browser, so it would also add weight to the side. (Because of this it's not _definitely_ a good choice, just something to consider. We may have a lighter weight option here, given that we have fewer use cases to support.)

**Comment by bvaughn** [comment]
There's also this: https://github.com/codesandbox-app/codesandbox-importers/tree/master/packages/git-extractor

That seems promising, because it seems like we might be able to just point Code Sandbox directly at our GitHub repo and have it load the examples that way.

**Comment by bvaughn** [comment]
I'm going to try a quick test using the git extractor...

**Comment by bvaughn** [comment]
I just pushed a new branch:
https://github.com/bvaughn/react-window/tree/code-sandbox-git-extractor-test/example/sandboxes/fixed-size-list-vertical

And it seems to just work when I link to:
https://codesandbox.io/s/github/bvaughn/react-window/tree/code-sandbox-git-extractor-test/example/sandboxes/fixed-size-list-vertical

Man, Code Sandbox sure is nice 😄

**Comment by wuweiweiwu** [comment]
Wow. everyday i'm more impressed with ives. He's also super awesome to work with. 

So we would just have to update the examples in the corresponding folder and the codesandbox would update automatically?

**Comment by bvaughn** [comment]
He is awesome!

Yeah, I'm going to just finish this really quickly since I've already started it 😄

**Comment by wuweiweiwu** [comment]
Sounds good. I think I'll use this for react-sortable-tree documentation too!

**Comment by bvaughn** [comment]
Committed with be40600
