### ISSUE TITLE
VariableSizeList render all items after resetAfterIndex

### ISSUE THREAD

**Issue by alexesDev** [bvaughn/react-window#87]
I try to create a catalog page with the following structure:
```
row0: category title
      products[0:6]
      more button

row1: products[6:12] with height: 0 by state
row2: products[12:18] with height: 0

... other categories
```
after click to "more" I change height for all rows to 400 and call `this._list.resetAfterIndex(index)` and this call render of all products in the category and hidden after first render... How I can fix this behavior?

~~I think if you skip the render [here](https://github.com/bvaughn/react-window/blob/master/src/createListComponent.js#L252) (if height === 0), everything will be fine.~~

**Comment by alexesDev** [comment]
Currently I skip the first render to avoid this behavior.
```js
class CategoryRow extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      skip: props.skipFirstFrame === undefined ? true : props.skipFirstFrame,
    };
  }

  componentDidMount() {
    this.mounted = true;

    requestAnimationFrame(() => {
      if (this.mounted) {
        this.setState({ skip: false });
      }
    });
  }

  componentDidUnmount() {
    this.mounted = false;
  }

  render() {
    if (this.state.skip) {
      return null;
    }
    // ...
  }
}
```

**Comment by bvaughn** [comment]
Sorry, I'm not really sure what you're asking or reporting. Please point me at a Code Sandbox that shows me what you're doing and the unexpected behavior.

**Comment by alexesDev** [comment]
I realized that using dynamic height is a very bad idea and sorry for this issue, its stupid. But this code shows the unexpected behavior:
https://codesandbox.io/s/r34199j6p (demo)

**Comment by bvaughn** [comment]
Well thanks for the update!
