### ISSUE TITLE
Please support react 16 and remove componentWillReceiveProps

### ISSUE THREAD

**Issue by hajdun** [bvaughn/react-window#88]
Using React 16 with react-window will log this to console:

warning.js?6327:33 Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

List uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
printWarning @ warning.js?6327:33
warning @ warning.js?6327:57
constructClassInstance @ react-dom.development.js?cada:6841
updateClassComponent @ react-dom.development.js?cada:8336
beginWork @ react-dom.development.js?cada:8982
performUnitOfWork @ react-dom.development.js?cada:11814
workLoop @ react-dom.development.js?cada:11843
renderRoot @ react-dom.development.js?cada:11874
performWorkOnRoot @ react-dom.development.js?cada:12449
performWork @ react-dom.development.js?cada:12370
performSyncWork @ react-dom.development.js?cada:12347
requestWork @ react-dom.development.js?cada:12247
scheduleWorkImpl @ react-dom.development.js?cada:12122
scheduleWork @ react-dom.development.js?cada:12082
scheduleRootUpdate @ react-dom.development.js?cada:12710
updateContainerAtExpirationTime @ react-dom.development.js?cada:12738
updateContainer @ react-dom.development.js?cada:12765
module.exports.webpackJsonp../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js?cada:16069
legacyRenderSubtreeIntoContainer @ react-dom.development.js?cada:16503
render @ react-dom.development.js?cada:16543
renderReactElement @ index.js?aef3:435
_callee4$ @ index.js?aef3:177
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:36
(anonymous) @ asyncToGenerator.js?7b11:14
doRender @ index.js?aef3:190
_callee2$ @ index.js?aef3:44
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:36
(anonymous) @ asyncToGenerator.js?7b11:14
render @ index.js?aef3:74
(anonymous) @ index.js?aef3:410
(anonymous) @ router.js?0272:771
(anonymous) @ _collection.js?aa8e:40
notify @ router.js?0272:770
set @ router.js?0272:525
_callee3$ @ router.js?0272:357
tryCatch @ runtime.js?4a57:62
invoke @ runtime.js?4a57:296
prototype.(anonymous function) @ runtime.js?4a57:114
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:28
Promise.then (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:36
(anonymous) @ asyncToGenerator.js?7b11:14
change @ router.js?0272:381
push @ router.js?0272:255
SingletonRouter.(anonymous function) @ index.js?121a:70
linkClicked @ link.js?7ba6:123
wrappedMethod @ react-hot-loader.development.js?280f:502
callCallback @ react-dom.development.js?cada:100
invokeGuardedCallbackDev @ react-dom.development.js?cada:138
invokeGuardedCallback @ react-dom.development.js?cada:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?cada:201
executeDispatch @ react-dom.development.js?cada:466
executeDispatchesInOrder @ react-dom.development.js?cada:488
executeDispatchesAndRelease @ react-dom.development.js?cada:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js?cada:597
forEachAccumulated @ react-dom.development.js?cada:567
runEventsInBatch @ react-dom.development.js?cada:728
runExtractedEventsInBatch @ react-dom.development.js?cada:737
handleTopLevel @ react-dom.development.js?cada:4201
batchedUpdates @ react-dom.development.js?cada:12537
batchedUpdates @ react-dom.development.js?cada:1939
dispatchEvent @ react-dom.development.js?cada:4282
interactiveUpdates @ react-dom.development.js?cada:12592
interactiveUpdates @ react-dom.development.js?cada:1958
dispatchInteractiveEvent @ react-dom.development.js?cada:4259

Please get rid of componentWillReceiveProps as written here: https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops
or by adding corresponding "key" props where update is needed on prop change (key={somethingfromthepropwhichwillchange}).

**Comment by TrySound** [comment]
@hajdun This project does not use `componentWillReceiveProps`.
https://unpkg.com/react-window@1.2.4/dist/index.esm.js

**Comment by bvaughn** [comment]
I believe you're mistaken, @hajdun.

> List uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
componentWillReceiveProps

If the "List" that error method refers to is the one from react-window, then maybe something in your app is trying to extend the prototype in some way that it shouldn't? Hard to say without a full repro.

If you can point me at your code, I'll take a look, but I'm going to close this issue for now.
