### ISSUE TITLE
Expandable item

### ISSUE THREAD

**Issue by smuk3c** [bvaughn/react-window#92]
I am working on smaller list where we need an option to expand item (and change height of it). It seems like current api doesn't support that. `resetAfterIndex` is causing re-rendering, but not refreshing the height of the actual item. Does `react-window` currently support this option?

**Comment by bvaughn** [comment]
`resetAfterIndex` should work for what you're describing. In fact, [there are unit tests for this](https://github.com/bvaughn/react-window/blob/902c1aa57916941fe7961203e84ba3b254a3c79a/src/__tests__/VariableSizeList.js#L195-L282).

Can you please point me at a repro that shows what's not working for you? [Here's a Code Sandbox you can fork to get started.](https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/variable-size-list-vertical)

**Comment by IOuser** [comment]
I added expandable items to Brian's example and it work's: https://codesandbox.io/s/kmzrylpx7o
Hope it helps.

**Comment by bvaughn** [comment]
I'm going to close this for now. Will re-open if repro steps are provided. 😄

**Comment by fonty422** [comment]
I know this is closed for now, but what about an animated expanding div. Not just something with 2 hard coded values. I have a need to use the `material-ui` `ExpansionPanel`, but implementing this leaves me with a panel that expands but doesn't displace the rest of the list.

**Comment by PQALAB** [comment]
Thanks for this, it helped me a bunch

**Comment by itayganor** [comment]
@fonty422 Have you ever found a solution for animated expanding divs?

**Comment by fonty422** [comment]
@itayganor I ended up using a different package (react-virtuoso) and going through the less painful (but still painful) method of providing a pre-culled list of items. Also, the material-ui page discussed it as a recommendation (along with react-window) for large lists. The [demo page](https://virtuoso.dev/) will show you if it's any good for your purposes.

**Comment by itayganor** [comment]
@fonty422 This is amazing. So simple. Thank you!

I actually have a question but I don't want to spam *this* discussion, so I'm creating it [over there](https://github.com/petyosi/react-virtuoso/issues/141).

**Comment by theconnectionist** [comment]
> 
> 
> @itayganor I ended up using a different package (react-virtuoso) and going through the less painful (but still painful) method of providing a pre-culled list of items. Also, the material-ui page discussed it as a recommendation (along with react-window) for large lists. The [demo page](https://virtuoso.dev/) will show you if it's any good for your purposes.

@fonty422 @itayganor do you have sample code of how you implemented nested lists using react-virtuoso? I'm not able to find examples of how it is done.

**Comment by robertfmath** [comment]
> @itayganor I ended up using a different package (react-virtuoso) and going through the less painful (but still painful) method of providing a pre-culled list of items. Also, the material-ui page discussed it as a recommendation (along with react-window) for large lists. The [demo page](https://virtuoso.dev/) will show you if it's any good for your purposes.

Thank you for bringing my attention to this library. It worked perfectly for my team's use case. Simple and easy to implement.

**Comment by fonty422** [comment]
> > @itayganor I ended up using a different package (react-virtuoso) and going through the less painful (but still painful) method of providing a pre-culled list of items. Also, the material-ui page discussed it as a recommendation (along with react-window) for large lists. The [demo page](https://virtuoso.dev/) will show you if it's any good for your purposes.
> 
> @fonty422 Thank you for bringing my attention to this package. It worked perfectly for my team's use case. Simple and easy to implement.

You're welcome. It's still my preferred package for this work for exactly this reason.
