### ISSUE TITLE
[Feature Suggestion] Expose onItemsRendered value as props to rendered cells

### ISSUE THREAD

**Issue by Bnaya** [bvaughn/react-window#98]
I have a specific use-case*, that i need to know the value that i would get from `onItemsRendered`
The thing is, the onItemsRendered callback is called only after the items was rendered.

I assume that, when render calls are made to render cells, the library already knows the values it will pass to onItemsRendered. as it uses them to calculate which cells to render.

So, the lib can pass it as an additional prop to the cell component.

* My use case is:
I'm trying to build a grid with fixed header, footer, and left-most visual column.

Code example of what i need:
https://github.com/bvaughn/react-window/compare/master...Bnaya:iterations?expand=1
I'n going to try and see if its helps me

**Comment by bvaughn** [comment]
Adding a parameter like this to item renderers would break memoization. (Since the range of items being rendered change as the user scrolls, if we were to pass that range to individual items– we would need to **re-render every item** any time we added or removed an item.)

This could be a pretty big performance hit, so it's not a change I'm willing to make to the API currently. Hope you'll understand! 🙇 

> I'm trying to build a grid with fixed header, footer, and left-most visual column.

Have you seen issue #86 by chance? You should be able to create a fixed header/footer type layout using the existing `onItemsRendered` callback. Here is a Code Sandbox showing the technique:
https://codesandbox.io/s/y3pyp85zm1

**Comment by Bnaya** [comment]
I completely understand your concerns,
If i had that data *before* the actual rendering that would also helpful.
Maybe willRenderItems?

I've managed to create fixed header and left column grid using single modded `FixedSizeGrid`, `position: sticky`.

Right now the code is tangled with internal data, but i hope later i will be able to show a demo!

**Comment by bvaughn** [comment]
> If i had that data before the actual rendering that would also helpful.
Maybe willRenderItems?

I think this request is *reasonable* but it's also the type of feature that can add up and makes a library hard to maintain or refactor. This happened with react-window's predecessor, react-virtualized, and I'm trying very hard to avoid it happening with this library.

The way I try to think about possible new features is admittedly a bit subjective, but I basically ask myself:
* Is there an existing way to accomplish what this person is trying to do without the added feature? (In this case, I think the answer is "yes".)
* If added, would this feature be useful to a significant percentage of react-window users? (In this case, I think that seems unlikely.)

**Comment by Bnaya** [comment]
I wanted to finally share what i'm using these props for:
![demo2](https://user-images.githubusercontent.com/1304862/58754471-398fb600-84d9-11e9-9c8d-975f7a58c527.gif)

https://codesandbox.io/s/github/Bnaya/sticky-eurovision/
And some of the story behind it:
https://github.com/Bnaya/sticky-eurovision#sticky-eurovision-technology-demonstrator-for-css-sticky-dom-virtualization-and-react-hooks

I think its important to have these value as the lib renders, and not after.
Maybe if these props will be exposed using context, and not props it won't hurt memoization? 
I can try to make a PR it it makes sense.

Thank you very much for the lib!

**Comment by bvaughn** [comment]
Right now, this library supports React v15+. Adding a feature that relied on context would essentially require me to drop support for <16.3, which is not something I am that open to doing.

And as you mentioned, passing them as props would break memoization in a big way.

You're always welcome to create a PR an we can talk about more specifics. All the same concerns I mentioned in my comment above still apply of course 😅

**Comment by Bnaya** [comment]
What about optional user-provided memo key produced, that gets these values
as param, and can choose if to invalidate cells.
You will have optional overhead of a function call, and only opt-in
overhead of react updates

**Comment by bvaughn** [comment]
I don't understand what you're suggesting, but React memoization considers props too, not just the key.

**Comment by Bnaya** [comment]
I will rephrase, If i understand correctly:

The concern is that adding this prop will hurt `areEqual` that supplied as the recommended memo function.

So what if the implementation of  `areEqual` will explicitly ignore the given `itemsRenderedCallbackParams`, and the user will be able to write his own function if he needs to depended on that updated data.
I personally also don't need it check on that data on every cell, but only for some of them. (I'm aiming for the first and last overscan items to make them sticky)

Also, Sending `itemsRenderedCallbackParams` param to `itemKey` as is, won't add any significant overhead (if i'm not missing anything).  I think that can be enough.

**Comment by bvaughn** [comment]
The concern isn't about `areEqual`. That memoization helper exists to keep the wrapper object around styles from breaking memoization. It works because the values within the styles wrapper object don't change though. What you're describing _would_ be a change, so memoization couldn't just ignore it without breaking the items.

I still don't understand what you're suggesting about the key. The `itemKey` _must_ be stable or react-window will throw away and recreate items every time the items rendered values change.

**Comment by Bnaya** [comment]
My goal:
I need to give special behaviour to the first and last rendered cells vertical and horizontal.
The way i can tell that a cell is first/last is comparing `item.rowIndex === item.itemsRenderedCallbackParams.overscanRowStartIndex`

The idea is: even tho cell X,Y is changing, rowIndex === overscanRowStartIndex, I give it a named key, `first-in-column:first-in-row`, `first-in-column:1-in-row` etc.
That's only if its a "special" cell. 
And that's how react uses the same DOM element even that the X,Y is different.

Let's say i don't have `overscanRowStartIndex` data as props, i can play with the key to force re-mount my edges cells by adding also x and y to the named key, something like: `first-in-column-4:first-in-row-5`. it will be less performant for me, but i think its reasonable.

Please see my itemKeyProvider:
https://github.com/Bnaya/sticky-eurovision/blob/master/src/implementations/WithReactWindowAndSticky/WithReactWindowAndSticky.tsx#L50-L86
itemKey
I hope it will be more clear

Aside of that, i still think its possible to implement areEqual is way that ignores `overscan...Index` values and treats them as never changed, but the developer can opt-in to it.
Something like:
```ts
export default function areEqual(
  prevProps: Object,
  nextProps: Object
): boolean {
  const { overScanInfo: prevOverScanInfo, style: prevStyle, ...prevRest } = prevProps;
  const { overScanInfo: nextOverScanInfo, style: nextStyle, ...nextRest } = nextProps;

  // we don't care about you by default!!! 
  // shallowDiffers(prevOverScanInfo, nextOverScanInfo)

  return (
    !shallowDiffers(prevStyle, nextStyle) && !shallowDiffers(prevRest, nextRest)
  );
}

```

**Comment by bvaughn** [comment]
> Aside of that, i still think its possible to implement areEqual is way that ignores overscan...Index values and treats them as never changed, but the developer can opt-in to it.

It _could be_ implemented that way, but I'm not comfortable wit treating something that _changes_ as though it doesn't change. I think it could lead to broken/unexpected behavior. The reason this is _okay_ with `style` is that it _only changes shallowly_ but that would not be the case with the indices you're describing.

I think we're going in a circles a little at this point. 😄 If you'd like to create a PR for me to consider, I will make time to look at it. (Can't promise it will be merged, but I will look at it.)
